import type{FastifyInstance}from'fastify';import{PERMISSIONS}from'@erp/contracts';import{requirePermission}from'../../core/security.js';import{AppError}from'../../core/errors.js';import{TimetableSlot}from'./models.js';import{detectTimetableConflict}from'./service.js';import{writeAudit}from'../../core/audit.js';
export async function timetableRoutes(app:FastifyInstance){
 app.get('/api/timetable/slots',{preHandler:requirePermission(PERMISSIONS.TIMETABLE_READ)},async(request:any)=>{const filter:any={};for(const k of['sessionId','sectionId','teacherId','day'])if(request.query?.[k])filter[k]=request.query[k];return{success:true,data:await TimetableSlot.find(filter).sort({day:1,period:1}).lean()}});
 app.post('/api/timetable/validate',{preHandler:requirePermission(PERMISSIONS.TIMETABLE_WRITE)},async(request:any)=>({success:true,data:{conflicts:await detectTimetableConflict(request.body)}}));
 app.post('/api/timetable/slots',{preHandler:requirePermission(PERMISSIONS.TIMETABLE_WRITE)},async(request:any)=>{const conflicts=await detectTimetableConflict(request.body);if(conflicts.length)throw new AppError(409,'TIMETABLE_CONFLICT','Teacher, section or room is already occupied',conflicts);const item=await TimetableSlot.create(request.body);await writeAudit({action:'timetable.create',entity:'timetable-slot',entityId:String(item._id),after:item.toObject(),ip:request.ip});return{success:true,data:item}});
 app.patch('/api/timetable/slots/:id',{preHandler:requirePermission(PERMISSIONS.TIMETABLE_WRITE)},async(request:any)=>{const conflicts=await detectTimetableConflict(request.body,request.params.id);if(conflicts.length)throw new AppError(409,'TIMETABLE_CONFLICT','Teacher, section or room is already occupied',conflicts);return{success:true,data:await TimetableSlot.findByIdAndUpdate(request.params.id,{$set:{...request.body,updatedAt:new Date()}},{new:true,runValidators:true})}});
 app.delete('/api/timetable/slots/:id',{preHandler:requirePermission(PERMISSIONS.TIMETABLE_WRITE)},async(request:any)=>{await TimetableSlot.findByIdAndUpdate(request.params.id,{$set:{deletedAt:new Date()}});return{success:true,data:{id:request.params.id}}});
 app.post('/api/timetable/publish',{preHandler:requirePermission(PERMISSIONS.TIMETABLE_WRITE)},async(request:any)=>{const r=await TimetableSlot.updateMany({sessionId:request.body?.sessionId},{$set:{published:true,updatedAt:new Date()}});return{success:true,data:{published:r.modifiedCount}}});
}
