import type{FastifyInstance}from'fastify';
import{Types}from'mongoose';
import{PERMISSIONS}from'@erp/contracts';
import{requirePermission}from'../../core/security.js';import{AppError,forbidden}from'../../core/errors.js';import{TimetableSlot}from'./models.js';import{detectTimetableConflict}from'./service.js';import{writeAudit}from'../../core/audit.js';
import{AcademicClass,AcademicSession,Section,Subject,TeacherSubjectMap}from'../academics/models.js';import{Guardian,Student,Teacher}from'../people/models.js';
const validId=(value:any)=>Types.ObjectId.isValid(String(value||''));
async function roleScope(request:any){const role=request.auth?.role;if(role==='STUDENT'){if(!request.auth?.profileId)throw forbidden('Student profile is not linked');const student:any=await Student.findById(request.auth.profileId).select('sectionId').lean();if(!student?.sectionId)return{_id:{$exists:false}};return{sectionId:student.sectionId,published:true}}if(role==='PARENT'){if(!request.auth?.profileId)throw forbidden('Parent profile is not linked');const guardian:any=await Guardian.findById(request.auth.profileId).select('studentIds').lean();const students=guardian?.studentIds?.length?await Student.find({_id:{$in:guardian.studentIds}}).select('sectionId').lean():[];const sectionIds=students.map((student:any)=>student.sectionId).filter(Boolean);return sectionIds.length?{sectionId:{$in:sectionIds},published:true}:{_id:{$exists:false}}}if(role==='TEACHER'){if(!request.auth?.profileId)throw forbidden('Teacher profile is not linked');return{teacherId:new Types.ObjectId(String(request.auth.profileId))}}return{}}
async function validateReferences(input:any){for(const[key,label]of[['sessionId','session'],['classId','class'],['sectionId','section'],['subjectId','subject'],['teacherId','teacher']]as const)if(!validId(input[key]))throw new AppError(400,'INVALID_TIMETABLE_REFERENCE',`Valid ${label} is required`);const[session,klass,section,subject,teacher]=await Promise.all([AcademicSession.findById(input.sessionId).select('_id').lean(),AcademicClass.findById(input.classId).select('_id').lean(),Section.findById(input.sectionId).select('_id classId').lean(),Subject.findById(input.subjectId).select('_id').lean(),Teacher.findById(input.teacherId).select('_id').lean()]);if(!session||!klass||!section||!subject||!teacher)throw new AppError(404,'TIMETABLE_REFERENCE_NOT_FOUND','A timetable reference does not exist in this school');if(String((section as any).classId)!==String(input.classId))throw new AppError(409,'SECTION_CLASS_MISMATCH','Section does not belong to the selected class');const assignment=await TeacherSubjectMap.findOne({teacherId:input.teacherId,classId:input.classId,sectionId:input.sectionId,subjectId:input.subjectId}).select('_id').lean();if(!assignment)throw new AppError(409,'TEACHER_SUBJECT_NOT_ASSIGNED','Teacher is not assigned to this subject/class/section')}
function validateTime(input:any){if(!Number.isInteger(Number(input.day))||Number(input.day)<1||Number(input.day)>7||!Number.isInteger(Number(input.period))||Number(input.period)<1)throw new AppError(400,'INVALID_SLOT','Day and period are invalid');const pattern=/^(?:[01]\d|2[0-3]):[0-5]\d$/;if(!pattern.test(String(input.startTime||''))||!pattern.test(String(input.endTime||''))||String(input.startTime)>=String(input.endTime))throw new AppError(400,'INVALID_TIME','Use HH:mm times and ensure end time is after start time')}
export async function timetableRoutes(app:FastifyInstance){
 app.get('/api/timetable/slots',{preHandler:requirePermission(PERMISSIONS.TIMETABLE_READ)},async(request:any)=>{const scope:any=await roleScope(request),filter:any={...scope};for(const key of['sessionId','day']as const)if(request.query?.[key])filter[key]=request.query[key];if(!['STUDENT','PARENT','TEACHER'].includes(request.auth?.role)){for(const key of['sectionId','teacherId']as const)if(request.query?.[key])filter[key]=request.query[key]}const data=await TimetableSlot.find(filter).sort({day:1,period:1}).populate('classId','name').populate('sectionId','name').populate('subjectId','name code').populate('teacherId','firstName lastName employeeNo').populate('sessionId','name isActive').lean();return{success:true,data}});
 app.post('/api/timetable/validate',{preHandler:requirePermission(PERMISSIONS.TIMETABLE_WRITE)},async(request:any)=>{validateTime(request.body??{});await validateReferences(request.body??{});return{success:true,data:{conflicts:await detectTimetableConflict(request.body)}}});
 app.post('/api/timetable/slots',{preHandler:requirePermission(PERMISSIONS.TIMETABLE_WRITE)},async(request:any)=>{validateTime(request.body??{});await validateReferences(request.body??{});const conflicts=await detectTimetableConflict(request.body);if(conflicts.length)throw new AppError(409,'TIMETABLE_CONFLICT','Teacher, section or room is already occupied',conflicts);const item=await TimetableSlot.create({...request.body,published:false});await writeAudit({action:'timetable.create',entity:'timetable-slot',entityId:String(item._id),after:item.toObject(),ip:request.ip});return{success:true,data:item}});
 app.patch('/api/timetable/slots/:id',{preHandler:requirePermission(PERMISSIONS.TIMETABLE_WRITE)},async(request:any)=>{const current:any=await TimetableSlot.findById(request.params.id).lean();if(!current)throw new AppError(404,'NOT_FOUND','Timetable slot not found');const next={...current,...request.body,_id:current._id,schoolId:current.schoolId,deletedAt:current.deletedAt,updatedAt:new Date()};validateTime(next);await validateReferences(next);const conflicts=await detectTimetableConflict(next,request.params.id);if(conflicts.length)throw new AppError(409,'TIMETABLE_CONFLICT','Teacher, section or room is already occupied',conflicts);const before=current;const item=await TimetableSlot.findByIdAndUpdate(request.params.id,{$set:{sessionId:next.sessionId,day:next.day,period:next.period,startTime:next.startTime,endTime:next.endTime,classId:next.classId,sectionId:next.sectionId,subjectId:next.subjectId,teacherId:next.teacherId,room:next.room,published:false,updatedAt:new Date()}},{new:true,runValidators:true});await writeAudit({action:'timetable.update',entity:'timetable-slot',entityId:request.params.id,before,after:item?.toObject(),ip:request.ip});return{success:true,data:item}});
 app.delete('/api/timetable/slots/:id',{preHandler:requirePermission(PERMISSIONS.TIMETABLE_WRITE)},async(request:any)=>{const before=await TimetableSlot.findById(request.params.id).lean();if(!before)throw new AppError(404,'NOT_FOUND','Timetable slot not found');await TimetableSlot.findByIdAndUpdate(request.params.id,{$set:{deletedAt:new Date(),updatedAt:new Date()}});await writeAudit({action:'timetable.delete',entity:'timetable-slot',entityId:request.params.id,before,after:{deletedAt:true},ip:request.ip});return{success:true,data:{id:request.params.id}}});
 app.post('/api/timetable/publish',{preHandler:requirePermission(PERMISSIONS.TIMETABLE_WRITE)},async(request:any)=>{if(!validId(request.body?.sessionId))throw new AppError(400,'INVALID_SESSION','Valid sessionId is required');const session=await AcademicSession.findById(request.body.sessionId).select('_id').lean();if(!session)throw new AppError(404,'SESSION_NOT_FOUND','Academic session not found');const r=await TimetableSlot.updateMany({sessionId:request.body.sessionId},{$set:{published:true,updatedAt:new Date()}});await writeAudit({action:'timetable.publish',entity:'timetable-slot',after:{sessionId:request.body.sessionId,published:r.modifiedCount},ip:request.ip});return{success:true,data:{published:r.modifiedCount}}});
}
