import type{FastifyInstance}from'fastify';
import { createHash } from 'node:crypto';
import { PERMISSIONS } from '@erp/contracts';
import { requirePermission } from '../../core/security.js';
import { AppError } from '../../core/errors.js';
import { runWithTenant } from '../../core/tenant-context.js';
import { writeAudit } from '../../core/audit.js';
import { School } from '../tenancy/models.js';
import { CustomForm,CustomFormSubmission } from './models.js';

const slugPattern=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const keyPattern=/^[A-Za-z][A-Za-z0-9_]{0,59}$/;
const clean=(value:any,max=5000)=>String(value??'').trim().slice(0,max);
function safeSlug(value:any){const slug=clean(value,80).toLowerCase();if(!slugPattern.test(slug))throw new AppError(400,'INVALID_SLUG','Slug may contain lowercase letters, numbers and hyphens');return slug}
function sanitizeFields(value:any){if(!Array.isArray(value)||value.length<1||value.length>60)throw new AppError(400,'INVALID_FIELDS','Form needs 1 to 60 fields');const keys=new Set<string>();return value.map((raw:any,index:number)=>{const key=clean(raw?.key,60),label=clean(raw?.label,120),type=String(raw?.type||'').toUpperCase();if(!keyPattern.test(key)||keys.has(key))throw new AppError(400,'INVALID_FIELD',`Field ${index+1} has an invalid or duplicate key`);keys.add(key);if(!label)throw new AppError(400,'INVALID_FIELD',`Field ${key} needs a label`);if(!['TEXT','TEXTAREA','EMAIL','PHONE','NUMBER','DATE','SELECT','RADIO','CHECKBOX'].includes(type))throw new AppError(400,'INVALID_FIELD_TYPE',`Unsupported field type for ${key}`);const options=Array.isArray(raw?.options)?[...new Set(raw.options.map((x:any)=>clean(x,120)).filter(Boolean))]:[];if(['SELECT','RADIO'].includes(type)&&!options.length)throw new AppError(400,'FIELD_OPTIONS_REQUIRED',`${key} needs at least one option`);if(options.length>100)throw new AppError(400,'TOO_MANY_OPTIONS',`${key} has too many options`);const defaultMax=type==='TEXTAREA'?5000:500,maxLength=raw?.maxLength===undefined?defaultMax:Math.min(5000,Math.max(1,Number(raw.maxLength)||defaultMax));return{key,label,type,required:Boolean(raw?.required),options,placeholder:clean(raw?.placeholder,180)||undefined,maxLength}})}
function formData(request:any,current:any={}){const body=request.body??{},name=body.name===undefined?current.name:clean(body.name,180),slug=body.slug===undefined?current.slug:safeSlug(body.slug);if(!name)throw new AppError(400,'INVALID_FORM','Form name is required');const status=body.status===undefined?(current.status||'DRAFT'):String(body.status);if(!['DRAFT','PUBLISHED','ARCHIVED'].includes(status))throw new AppError(400,'INVALID_STATUS','Invalid form status');const fields=body.fields===undefined?(current.fields||[]):sanitizeFields(body.fields);if(status==='PUBLISHED'&&!fields.length)throw new AppError(400,'EMPTY_FORM','Published form needs fields');return{name,slug,purpose:body.purpose===undefined?(current.purpose||'GENERAL'):clean(body.purpose,80)||'GENERAL',description:body.description===undefined?current.description:clean(body.description,2000)||undefined,fields,status,public:body.public===undefined?Boolean(current.public):Boolean(body.public),successMessage:body.successMessage===undefined?current.successMessage:clean(body.successMessage,500)||undefined,createdBy:current.createdBy||request.auth.sub,updatedAt:new Date()}}
function validateValue(field:any,raw:any){if(raw===undefined||raw===null||raw===''){if(field.required)throw new AppError(422,'FIELD_REQUIRED',`${field.label} is required`);return undefined}switch(field.type){case'TEXT':case'TEXTAREA':{const value=clean(raw,field.maxLength||500);if(field.required&&!value)throw new AppError(422,'FIELD_REQUIRED',`${field.label} is required`);return value}case'EMAIL':{const value=clean(raw,254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))throw new AppError(422,'INVALID_EMAIL',`${field.label} is not a valid email`);return value}case'PHONE':{const value=clean(raw,30);if(!/^\+?[0-9][0-9\s()-]{6,28}$/.test(value))throw new AppError(422,'INVALID_PHONE',`${field.label} is not a valid phone number`);return value}case'NUMBER':{const value=Number(raw);if(!Number.isFinite(value))throw new AppError(422,'INVALID_NUMBER',`${field.label} must be a number`);return value}case'DATE':{const value=String(raw);if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number.isNaN(new Date(`${value}T00:00:00Z`).getTime()))throw new AppError(422,'INVALID_DATE',`${field.label} must be a valid date`);return value}case'SELECT':case'RADIO':{const value=clean(raw,120);if(!field.options?.includes(value))throw new AppError(422,'INVALID_OPTION',`${field.label} has an invalid option`);return value}case'CHECKBOX':{if(typeof raw==='boolean')return raw;if(raw==='true'||raw==='1'||raw===1)return true;if(raw==='false'||raw==='0'||raw===0)return false;throw new AppError(422,'INVALID_CHECKBOX',`${field.label} must be true or false`)}default:throw new AppError(422,'INVALID_FIELD','Unsupported form field')}}
function submissionValues(form:any,input:any){if(!input||typeof input!=='object'||Array.isArray(input))throw new AppError(400,'INVALID_VALUES','values must be an object');const allowed=new Set((form.fields||[]).map((field:any)=>field.key)),unknown=Object.keys(input).filter(key=>!allowed.has(key));if(unknown.length)throw new AppError(422,'UNKNOWN_FIELDS',`Unknown form fields: ${unknown.slice(0,5).join(', ')}`);const values:any={};for(const field of form.fields||[]){const value=validateValue(field,input[field.key]);if(value!==undefined)values[field.key]=value}return values}
function publicShape(form:any,school:any){return{id:form._id,name:form.name,slug:form.slug,purpose:form.purpose,description:form.description,fields:(form.fields||[]).map((field:any)=>({key:field.key,label:field.label,type:field.type,required:field.required,options:field.options,placeholder:field.placeholder,maxLength:field.maxLength})),successMessage:form.successMessage,school:{name:school.name,code:school.code,logoUrl:school.logoUrl}}}
async function resolvePublicSchool(code:any){const school:any=await School.findOne({code:String(code||'').trim().toUpperCase(),status:{$in:['ACTIVE','TRIAL']}}).lean();if(!school||!(school.enabledModules||[]).includes('custom-forms'))throw new AppError(404,'FORM_NOT_FOUND','Public form not found');return school}

export async function customFormRoutes(app:FastifyInstance){
 app.get('/api/public/forms/:schoolCode/:slug',{config:{rateLimit:{max:120,timeWindow:'1 minute'}}},async(request:any)=>{const school=await resolvePublicSchool(request.params.schoolCode);return runWithTenant({schoolId:String(school._id),requestId:request.id},async()=>{const form:any=await CustomForm.findOne({slug:safeSlug(request.params.slug),status:'PUBLISHED',public:true}).lean();if(!form)throw new AppError(404,'FORM_NOT_FOUND','Public form not found');return{success:true,data:publicShape(form,school)}})});
 app.post('/api/public/forms/:schoolCode/:slug/submissions',{config:{rateLimit:{max:12,timeWindow:'10 minutes'}}},async(request:any)=>{const school=await resolvePublicSchool(request.params.schoolCode);if(clean(request.body?._website,200))return{success:true,data:{accepted:true}};return runWithTenant({schoolId:String(school._id),requestId:request.id},async()=>{const form:any=await CustomForm.findOne({slug:safeSlug(request.params.slug),status:'PUBLISHED',public:true}).lean();if(!form)throw new AppError(404,'FORM_NOT_FOUND','Public form not found');const values=submissionValues(form,request.body?.values),ipHash=createHash('sha256').update(`${school._id}:${String(request.ip||'')}`).digest('hex'),item=await CustomFormSubmission.create({formId:form._id,values,status:'NEW',source:'PUBLIC',ipHash,userAgent:clean(request.headers['user-agent'],500)||undefined});return{success:true,data:{id:item._id,accepted:true,message:form.successMessage||'Your response has been received.'}}})});
 app.get('/api/custom-forms',{preHandler:requirePermission(PERMISSIONS.CUSTOM_FORM_READ)},async(request:any)=>{const q=clean(request.query?.q,100),filter:any={};if(q)filter.$or=[{name:{$regex:q,$options:'i'}},{slug:{$regex:q,$options:'i'}}];return{success:true,data:await CustomForm.find(filter).sort({updatedAt:-1}).limit(300).lean()}});
 app.get('/api/custom-forms/:id',{preHandler:requirePermission(PERMISSIONS.CUSTOM_FORM_READ)},async(request:any)=>{const item=await CustomForm.findById(request.params.id).lean();if(!item)throw new AppError(404,'NOT_FOUND','Form not found');return{success:true,data:item}});
 app.post('/api/custom-forms',{preHandler:requirePermission(PERMISSIONS.CUSTOM_FORM_WRITE)},async(request:any)=>{const data=formData(request),item=await CustomForm.create(data);await writeAudit({action:'custom-form.create',entity:'custom-form',entityId:String(item._id),after:{name:item.name,slug:item.slug,status:item.status,public:item.public},ip:request.ip});return{success:true,data:item}});
 app.patch('/api/custom-forms/:id',{preHandler:requirePermission(PERMISSIONS.CUSTOM_FORM_WRITE)},async(request:any)=>{const item:any=await CustomForm.findById(request.params.id);if(!item)throw new AppError(404,'NOT_FOUND','Form not found');const before={name:item.name,slug:item.slug,status:item.status,public:item.public,fields:item.fields},data=formData(request,item);Object.assign(item,data);await item.save();await writeAudit({action:'custom-form.update',entity:'custom-form',entityId:String(item._id),before,after:{name:item.name,slug:item.slug,status:item.status,public:item.public,fields:item.fields},ip:request.ip});return{success:true,data:item}});
 app.get('/api/custom-form-submissions',{preHandler:requirePermission(PERMISSIONS.CUSTOM_FORM_READ)},async(request:any)=>{const filter:any={};if(request.query?.formId)filter.formId=request.query.formId;if(request.query?.status){const status=String(request.query.status);if(!['NEW','REVIEWED','CONVERTED','REJECTED'].includes(status))throw new AppError(400,'INVALID_STATUS','Invalid submission status');filter.status=status}return{success:true,data:await CustomFormSubmission.find(filter).sort({createdAt:-1}).limit(500).lean()}});
 app.post('/api/custom-form-submissions/:id/review',{preHandler:requirePermission(PERMISSIONS.CUSTOM_FORM_WRITE)},async(request:any)=>{const status=String(request.body?.status||'');if(!['REVIEWED','REJECTED'].includes(status))throw new AppError(400,'INVALID_STATUS','Use REVIEWED or REJECTED');const item:any=await CustomFormSubmission.findById(request.params.id);if(!item)throw new AppError(404,'NOT_FOUND','Submission not found');if(!['NEW','REVIEWED'].includes(item.status))throw new AppError(409,'SUBMISSION_LOCKED','Submission cannot be reviewed in its current state');const before={status:item.status};item.status=status;item.reviewedBy=request.auth.sub;item.reviewedAt=new Date();item.reviewNote=clean(request.body?.note,2000)||undefined;item.updatedAt=new Date();await item.save();await writeAudit({action:'custom-form.review',entity:'custom-form-submission',entityId:String(item._id),before,after:{status:item.status,reviewNote:item.reviewNote},ip:request.ip});return{success:true,data:item}});
}
