import type { FastifyInstance } from 'fastify';
import { PERMISSIONS } from '@erp/contracts';
import { registerCrud } from '../../core/crud.js';
import { requirePermission } from '../../core/security.js';
import { Student } from '../people/models.js';
import { assertStudentAccessible } from '../people/access.js';
import { Exam,Mark } from '../examinations/models.js';
import { Attendance } from '../attendance/models.js';
import { ReportCard,ReportTemplate } from './models.js';
import { AppError } from '../../core/errors.js';

export async function reportCardRoutes(app:FastifyInstance){
 await registerCrud(app,{prefix:'/api/report-templates',model:ReportTemplate,entity:'report-template',readPermission:PERMISSIONS.REPORT_CARD_READ,writePermission:PERMISSIONS.REPORT_CARD_WRITE,searchable:['name']});
 app.post('/api/report-cards/generate',{preHandler:requirePermission(PERMISSIONS.REPORT_CARD_WRITE)},async(request:any)=>{const{studentId,examId,templateId}=request.body??{};const[student,exam,marks,attendance]=await Promise.all([Student.findById(studentId).lean(),Exam.findById(examId).lean(),Mark.find({studentId,examId}).lean(),Attendance.find({studentId}).lean()]);if(!student||!exam)throw new AppError(404,'NOT_FOUND','Student or exam not found');if(!['LOCKED','PUBLISHED'].includes(exam.status))throw new AppError(409,'EXAM_NOT_FINAL','Report cards can be generated only after marks are locked');const configs:any[]=exam.subjectConfigs||[];if(configs.length&&marks.length<configs.length)throw new AppError(409,'INCOMPLETE_MARKS','Marks are incomplete for this student');const obtained=marks.reduce((sum:any,mark:any)=>sum+Number(mark.total||0),0),max=configs.reduce((sum:any,config:any)=>sum+Number(config.maxMarks||0),0),percentage=max?Math.round((obtained/max)*10000)/100:0,present=attendance.filter((row:any)=>row.status==='PRESENT').length,attendancePercentage=attendance.length?Math.round((present/attendance.length)*10000)/100:0,grade=percentage>=90?'A+':percentage>=80?'A':percentage>=70?'B+':percentage>=60?'B':percentage>=50?'C':percentage>=40?'D':'E';const configBySubject=new Map(configs.map((config:any)=>[String(config.subjectId),config]));const failed=marks.some((mark:any)=>Number(mark.total||0)<Number((configBySubject.get(String(mark.subjectId)) as any)?.passMarks||0));const snapshot={student,exam,marks,attendance:{total:attendance.length,present,percentage:attendancePercentage},totals:{obtained,max,percentage,grade}};const card=await ReportCard.findOneAndUpdate({studentId,examId},{$set:{templateId,snapshot,percentage,grade,result:failed?'FAIL':'PASS',publishedAt:exam.status==='PUBLISHED'?new Date():undefined}},{new:true,upsert:true,setDefaultsOnInsert:true});return{success:true,data:card}});
 app.get('/api/report-cards/:studentId/:examId',{preHandler:requirePermission(PERMISSIONS.REPORT_CARD_READ)},async(request:any)=>{await assertStudentAccessible(request,request.params.studentId);const exam:any=await Exam.findById(request.params.examId).select('status').lean();if(!exam)throw new AppError(404,'NOT_FOUND','Exam not found');if(['STUDENT','PARENT'].includes(request.auth?.role)&&exam.status!=='PUBLISHED')throw new AppError(404,'NOT_FOUND','Published report card not found');const card=await ReportCard.findOne({studentId:request.params.studentId,examId:request.params.examId}).lean();if(!card)throw new AppError(404,'NOT_FOUND','Report card not found');return{success:true,data:card}});
}
