import { AppError } from '../../core/errors.js';
import { getTenantContext } from '../../core/tenant-context.js';
import { AcademicClass,Section,Subject } from '../academics/models.js';
import { Attendance } from '../attendance/models.js';
import { Exam,Mark } from '../examinations/models.js';
import { Student } from '../people/models.js';
import { School } from '../tenancy/models.js';

export async function buildReportCardData(studentId:string,examId:string){
 const [student,exam]=await Promise.all([Student.findById(studentId).lean(),Exam.findById(examId).lean()]);if(!student||!exam)throw new AppError(404,'NOT_FOUND','Student or exam not found');if(!['LOCKED','PUBLISHED'].includes(exam.status))throw new AppError(409,'EXAM_NOT_FINAL','Report cards can be generated only after marks are locked');
 const configs:any[]=exam.subjectConfigs||[],configuredIds=configs.map(config=>String(config.subjectId));const [marks,attendance,academicClass,section,subjects]=await Promise.all([Mark.find({studentId,examId}).lean(),Attendance.find({studentId,sessionId:exam.sessionId}).lean(),student.classId?AcademicClass.findById(student.classId).lean():null,student.sectionId?Section.findById(student.sectionId).lean():null,configuredIds.length?Subject.find({_id:{$in:configuredIds}}).lean():[]]);
 const markBySubject=new Map(marks.map((mark:any)=>[String(mark.subjectId),mark]));const missing=configuredIds.filter(id=>!markBySubject.has(id));if(missing.length)throw new AppError(409,'INCOMPLETE_MARKS','Marks are incomplete for this student',{missingSubjectIds:missing});
 const subjectById=new Map(subjects.map((subject:any)=>[String(subject._id),subject]));
 const subjectRows=(configs.length?configs:marks.map((mark:any)=>({subjectId:mark.subjectId,maxMarks:mark.total||0,passMarks:0}))).map((config:any)=>{const mark:any=markBySubject.get(String(config.subjectId))||{},maximum=Number(config.maxMarks||0),obtained=Number(mark.total||0);return{subjectId:String(config.subjectId),name:String((subjectById.get(String(config.subjectId)) as any)?.name||'Subject'),maximum,obtained,theory:Number(mark.theory||0),practical:Number(mark.practical||0),internal:Number(mark.internal||0),grade:String(mark.grade||''),remark:String(mark.remark||''),passMarks:Number(config.passMarks||0)}});
 const obtained=subjectRows.reduce((sum,row)=>sum+row.obtained,0),maximum=subjectRows.reduce((sum,row)=>sum+row.maximum,0),percentage=maximum?Math.round((obtained/maximum)*10000)/100:0,present=attendance.filter((row:any)=>row.status==='PRESENT').length,attendancePercentage=attendance.length?Math.round((present/attendance.length)*10000)/100:0,grade=percentage>=90?'A+':percentage>=80?'A':percentage>=70?'B+':percentage>=60?'B':percentage>=50?'C':percentage>=40?'D':'E',failed=subjectRows.some(row=>row.obtained<row.passMarks);
 const schoolId=getTenantContext()?.schoolId;if(!schoolId)throw new AppError(403,'TENANT_REQUIRED','School context required');const school=await School.findById(schoolId).lean();if(!school)throw new AppError(404,'NOT_FOUND','School not found');const schoolAddress=[school.address?.line1,school.address?.line2,school.address?.city,school.address?.state,school.address?.pincode,school.address?.country].map(value=>String(value||'').trim()).filter(Boolean).join(', ');
 const snapshot={student:{id:String(student._id),firstName:student.firstName,lastName:student.lastName||'',admissionNo:student.admissionNo,rollNo:student.rollNo||'',className:academicClass?.name||'',sectionName:section?.name||''},exam:{id:String(exam._id),name:exam.name,term:exam.term||'',sessionId:String(exam.sessionId),status:exam.status},subjects:subjectRows,attendance:{total:attendance.length,present,percentage:attendancePercentage},totals:{obtained,maximum,percentage,grade,result:failed?'FAIL':'PASS'},school:{name:school.name,address:schoolAddress}};
 return{snapshot,percentage,grade,result:failed?'FAIL' as const:'PASS' as const,render:{schoolName:String(school.name),schoolAddress,studentName:`${student.firstName} ${student.lastName||''}`.trim(),admissionNo:String(student.admissionNo||''),rollNo:String(student.rollNo||''),className:String(academicClass?.name||''),sectionName:String(section?.name||''),examName:String(exam.name),term:String(exam.term||''),subjects:subjectRows.map(row=>({name:row.name,maxMarks:row.maximum,obtained:row.obtained,grade:row.grade,remark:row.remark})),obtained,maximum,percentage,grade,result:failed?'FAIL':'PASS',attendancePercentage,attendancePresent:present,attendanceTotal:attendance.length,published:exam.status==='PUBLISHED'}};
}
