import type { FastifyInstance } from 'fastify';
import bcrypt from 'bcryptjs';
import { School } from '../tenancy/models.js';
import { User,Session } from './models.js';
import { AppError,unauthorized } from '../../core/errors.js';
import { newSessionId,hashToken,signAccessToken,signRefreshToken,verifyRefreshToken,authenticate,requirePermission } from '../../core/security.js';
import { runWithTenant } from '../../core/tenant-context.js';
import { env } from '../../config/env.js';
import { DEFAULT_ROLE_PERMISSIONS,PERMISSIONS } from '@erp/contracts';
import { passwordResetRoutes } from './password-reset.js';
function setCookies(reply:any,access:string,refresh:string){const base={httpOnly:true,secure:env.NODE_ENV==='production',sameSite:'lax' as const,path:'/',domain:env.COOKIE_DOMAIN||undefined};reply.setCookie('access_token',access,{...base,maxAge:15*60});reply.setCookie('refresh_token',refresh,{...base,maxAge:env.REFRESH_TOKEN_TTL_DAYS*24*60*60});}
export async function identityRoutes(app:FastifyInstance){
 await passwordResetRoutes(app);
 app.post('/api/auth/login',{config:{rateLimit:{max:10,timeWindow:'1 minute'}}},async(request:any,reply)=>{const{schoolCode,login,password}=request.body??{};if(!schoolCode||!login||!password)throw new AppError(400,'INVALID_INPUT','schoolCode, login and password are required');const school=await School.findOne({code:String(schoolCode).toUpperCase()}).lean();if(!school||school.status==='SUSPENDED')throw unauthorized('School unavailable');return runWithTenant({schoolId:String(school._id),requestId:request.id},async()=>{const user=await User.findOne({$or:[{email:String(login).toLowerCase()},{username:String(login).toLowerCase()}]}).select('+passwordHash');if(!user||!user.isActive||!(await bcrypt.compare(password,user.passwordHash)))throw unauthorized('Invalid credentials');const claims:any={sub:String(user._id),schoolId:String(school._id),role:user.role,type:'school',permissions:user.permissions,profileId:user.profileId?String(user.profileId):undefined,profileType:user.profileType,mustChangePassword:user.mustChangePassword};const jti=newSessionId();const[access,refresh]=await Promise.all([signAccessToken(claims),signRefreshToken(claims,jti)]);await Session.create({userId:user._id,refreshTokenHash:hashToken(refresh),userAgent:request.headers['user-agent'],ip:request.ip,expiresAt:new Date(Date.now()+env.REFRESH_TOKEN_TTL_DAYS*86400000)});user.lastLoginAt=new Date();await user.save();setCookies(reply,access,refresh);return{success:true,data:{accessToken:access,user:{id:user._id,firstName:user.firstName,lastName:user.lastName,role:user.role,permissions:user.permissions,profileId:user.profileId,profileType:user.profileType,mustChangePassword:user.mustChangePassword},school:{id:school._id,name:school.name,code:school.code}}};});});
 app.post('/api/auth/refresh',async(request:any,reply)=>{const raw=request.cookies.refresh_token;if(!raw)throw unauthorized();const claims=await verifyRefreshToken(raw).catch(()=>null);if(!claims?.schoolId)throw unauthorized();const school=await School.findById(claims.schoolId).lean();if(!school||school.status==='SUSPENDED')throw unauthorized('School unavailable');return runWithTenant({schoolId:claims.schoolId,userId:claims.sub,requestId:request.id},async()=>{const session=await Session.findOne({refreshTokenHash:hashToken(raw),revokedAt:null,expiresAt:{$gt:new Date()}});if(!session)throw unauthorized('Session revoked');const user=await User.findById(claims.sub);if(!user?.isActive)throw unauthorized();const next:any={sub:String(user._id),schoolId:claims.schoolId,role:user.role,type:'school',permissions:user.permissions,profileId:user.profileId?String(user.profileId):undefined,profileType:user.profileType,mustChangePassword:user.mustChangePassword};const jti=newSessionId();const[access,refresh]=await Promise.all([signAccessToken(next),signRefreshToken(next,jti)]);session.revokedAt=new Date();await session.save();await Session.create({userId:user._id,refreshTokenHash:hashToken(refresh),userAgent:request.headers['user-agent'],ip:request.ip,expiresAt:new Date(Date.now()+env.REFRESH_TOKEN_TTL_DAYS*86400000)});setCookies(reply,access,refresh);return{success:true,data:{accessToken:access,user:{id:user._id,firstName:user.firstName,lastName:user.lastName,role:user.role,permissions:user.permissions,profileId:user.profileId,profileType:user.profileType,mustChangePassword:user.mustChangePassword}}};});});
 app.post('/api/auth/logout',async(request:any,reply)=>{const raw=request.cookies.refresh_token;if(raw){const claims=await verifyRefreshToken(raw).catch(()=>null);if(claims?.schoolId)await runWithTenant({schoolId:claims.schoolId,userId:claims.sub},()=>Session.updateOne({refreshTokenHash:hashToken(raw)},{$set:{revokedAt:new Date()}}));}reply.clearCookie('access_token',{path:'/'});reply.clearCookie('refresh_token',{path:'/'});return{success:true,data:{loggedOut:true}};});
 app.get('/api/users',{preHandler:requirePermission(PERMISSIONS.USER_MANAGE)},async()=>({success:true,data:await User.find().select('-passwordHash').sort({createdAt:-1}).lean()}));
 app.post('/api/users',{preHandler:requirePermission(PERMISSIONS.USER_MANAGE)},async(request:any)=>{const{email,username,password,firstName,lastName,role,permissions,profileId,profileType}=request.body??{};if(!password||String(password).length<8)throw new AppError(400,'WEAK_PASSWORD','Password must be at least 8 characters');const user=await User.create({email:email?.toLowerCase(),username:username?.toLowerCase(),passwordHash:await bcrypt.hash(password,12),firstName,lastName,role,permissions:permissions??DEFAULT_ROLE_PERMISSIONS[role as keyof typeof DEFAULT_ROLE_PERMISSIONS]??[],profileId,profileType,mustChangePassword:true});return{success:true,data:{id:user._id,email:user.email,username:user.username,firstName:user.firstName,lastName:user.lastName,role:user.role}}});
 app.patch('/api/users/:id/status',{preHandler:requirePermission(PERMISSIONS.USER_MANAGE)},async(request:any)=>({success:true,data:await User.findByIdAndUpdate(request.params.id,{$set:{isActive:Boolean(request.body?.isActive),updatedAt:new Date()}},{new:true})}));
 app.post('/api/account/change-password',{preHandler:authenticate},async(request:any)=>{const user=await User.findById(request.auth.sub).select('+passwordHash');if(!user)throw unauthorized();if(!(await bcrypt.compare(String(request.body?.currentPassword||''),user.passwordHash)))throw unauthorized('Current password is incorrect');const next=String(request.body?.newPassword||'');if(next.length<8)throw new AppError(400,'WEAK_PASSWORD','New password must be at least 8 characters');user.passwordHash=await bcrypt.hash(next,12);user.mustChangePassword=false;user.updatedAt=new Date();await user.save();await Session.updateMany({userId:user._id,revokedAt:null},{$set:{revokedAt:new Date()}});return{success:true,data:{changed:true,reauthenticate:true}}});
}
