import type { FastifyInstance } from 'fastify';
import bcrypt from 'bcryptjs';
import { School } from '../tenancy/models.js';
import { User,Session } from './models.js';
import { AppError,unauthorized } from '../../core/errors.js';
import { newSessionId,hashToken,signAccessToken,signRefreshToken,verifyRefreshToken,authenticate,requirePermission } from '../../core/security.js';
import { runWithTenant } from '../../core/tenant-context.js';
import { env } from '../../config/env.js';
import { DEFAULT_ROLE_PERMISSIONS,PERMISSIONS,SCHOOL_ROLES,type SchoolRole } from '@erp/contracts';
import { passwordResetRoutes } from './password-reset.js';
import { writeAudit } from '../../core/audit.js';

const validRoles=new Set<string>(SCHOOL_ROLES),validPermissions=new Set<string>(Object.values(PERMISSIONS));
function cookieBase(){return{httpOnly:true,secure:env.NODE_ENV==='production',sameSite:'strict' as const,path:'/',domain:env.COOKIE_DOMAIN||undefined}}
function setCookies(reply:any,access:string,refresh:string){const base=cookieBase();reply.setCookie('access_token',access,{...base,maxAge:15*60});reply.setCookie('refresh_token',refresh,{...base,maxAge:env.REFRESH_TOKEN_TTL_DAYS*24*60*60})}
function clearCookies(reply:any){const base=cookieBase();reply.clearCookie('access_token',base);reply.clearCookie('refresh_token',base)}
function userView(user:any){return{id:user._id,firstName:user.firstName,lastName:user.lastName,role:user.role,permissions:user.permissions,profileId:user.profileId,profileType:user.profileType,mustChangePassword:user.mustChangePassword}}
function normalizeAccess(roleValue:any,permissionsValue:any){const role=String(roleValue||'');if(!validRoles.has(role))throw new AppError(400,'INVALID_ROLE','Invalid school role');let permissions:any[]=permissionsValue===undefined?[...(DEFAULT_ROLE_PERMISSIONS[role as SchoolRole]||[])]:permissionsValue;if(!Array.isArray(permissions)||permissions.some(value=>!validPermissions.has(String(value))))throw new AppError(400,'INVALID_PERMISSIONS','One or more permissions are invalid');permissions=[...new Set(permissions.map(String))];return{role,permissions}}

export async function identityRoutes(app:FastifyInstance){
 await passwordResetRoutes(app);
 app.post('/api/auth/login',{config:{rateLimit:{max:10,timeWindow:'1 minute'}}},async(request:any,reply)=>{const{schoolCode,login,password}=request.body??{};if(!schoolCode||!login||!password)throw new AppError(400,'INVALID_INPUT','schoolCode, login and password are required');const school=await School.findOne({code:String(schoolCode).toUpperCase()}).lean();if(!school||school.status==='SUSPENDED')throw unauthorized('School unavailable');return runWithTenant({schoolId:String(school._id),requestId:request.id},async()=>{const user=await User.findOne({$or:[{email:String(login).toLowerCase()},{username:String(login).toLowerCase()}]}).select('+passwordHash');if(!user||!user.isActive||!(await bcrypt.compare(String(password),user.passwordHash)))throw unauthorized('Invalid credentials');const claims:any={sub:String(user._id),schoolId:String(school._id),role:user.role,type:'school',permissions:user.permissions,profileId:user.profileId?String(user.profileId):undefined,profileType:user.profileType,mustChangePassword:user.mustChangePassword};const jti=newSessionId();const[access,refresh]=await Promise.all([signAccessToken(claims),signRefreshToken(claims,jti)]);await Session.create({userId:user._id,refreshTokenHash:hashToken(refresh),userAgent:request.headers['user-agent'],ip:request.ip,expiresAt:new Date(Date.now()+env.REFRESH_TOKEN_TTL_DAYS*86400000)});user.lastLoginAt=new Date();await user.save();setCookies(reply,access,refresh);return{success:true,data:{user:userView(user),school:{id:school._id,name:school.name,code:school.code}}};});});
 app.post('/api/auth/refresh',{config:{rateLimit:{max:30,timeWindow:'1 minute'}}},async(request:any,reply)=>{const raw=request.cookies.refresh_token;if(!raw)throw unauthorized();const claims=await verifyRefreshToken(raw).catch(()=>null);if(!claims?.schoolId)throw unauthorized();const school=await School.findById(claims.schoolId).lean();if(!school||school.status==='SUSPENDED')throw unauthorized('School unavailable');return runWithTenant({schoolId:claims.schoolId,userId:claims.sub,requestId:request.id},async()=>{const session=await Session.findOne({refreshTokenHash:hashToken(raw),revokedAt:null,expiresAt:{$gt:new Date()}});if(!session)throw unauthorized('Session revoked');const user=await User.findById(claims.sub);if(!user?.isActive)throw unauthorized();const next:any={sub:String(user._id),schoolId:claims.schoolId,role:user.role,type:'school',permissions:user.permissions,profileId:user.profileId?String(user.profileId):undefined,profileType:user.profileType,mustChangePassword:user.mustChangePassword};const jti=newSessionId();const[access,refresh]=await Promise.all([signAccessToken(next),signRefreshToken(next,jti)]);session.revokedAt=new Date();await session.save();await Session.create({userId:user._id,refreshTokenHash:hashToken(refresh),userAgent:request.headers['user-agent'],ip:request.ip,expiresAt:new Date(Date.now()+env.REFRESH_TOKEN_TTL_DAYS*86400000)});setCookies(reply,access,refresh);return{success:true,data:{user:userView(user)}};});});
 app.post('/api/auth/logout',async(request:any,reply)=>{const raw=request.cookies.refresh_token;if(raw){const claims=await verifyRefreshToken(raw).catch(()=>null);if(claims?.schoolId)await runWithTenant({schoolId:claims.schoolId,userId:claims.sub,requestId:request.id},()=>Session.updateOne({refreshTokenHash:hashToken(raw)},{$set:{revokedAt:new Date()}}));}clearCookies(reply);return{success:true,data:{loggedOut:true}};});
 app.get('/api/users',{preHandler:requirePermission(PERMISSIONS.USER_MANAGE)},async()=>({success:true,data:await User.find().select('-passwordHash').sort({createdAt:-1}).lean()}));
 app.post('/api/users',{preHandler:requirePermission(PERMISSIONS.USER_MANAGE)},async(request:any)=>{const{email,username,password,firstName,lastName,profileId,profileType}=request.body??{};if(!password||String(password).length<8)throw new AppError(400,'WEAK_PASSWORD','Password must be at least 8 characters');if(!String(firstName||'').trim())throw new AppError(400,'INVALID_NAME','First name is required');const access=normalizeAccess(request.body?.role,request.body?.permissions);const user=await User.create({email:email?String(email).trim().toLowerCase():undefined,username:username?String(username).trim().toLowerCase():undefined,passwordHash:await bcrypt.hash(String(password),12),firstName:String(firstName).trim().slice(0,100),lastName:String(lastName||'').trim().slice(0,100),...access,profileId,profileType,mustChangePassword:true});await writeAudit({action:'user.create',entity:'user',entityId:String(user._id),after:{email:user.email,username:user.username,role:user.role,permissions:user.permissions,profileId:user.profileId},ip:request.ip});return{success:true,data:userView(user)}});
 app.patch('/api/users/:id/status',{preHandler:requirePermission(PERMISSIONS.USER_MANAGE)},async(request:any)=>{if(typeof request.body?.isActive!=='boolean')throw new AppError(400,'INVALID_STATUS','isActive must be boolean');if(String(request.params.id)===String(request.auth.sub)&&request.body.isActive===false)throw new AppError(409,'SELF_DEACTIVATION','You cannot deactivate your own active session');const user:any=await User.findById(request.params.id);if(!user)throw new AppError(404,'NOT_FOUND','User not found');const before={isActive:user.isActive};user.isActive=request.body.isActive;user.updatedAt=new Date();await user.save();if(!user.isActive)await Session.updateMany({userId:user._id,revokedAt:null},{$set:{revokedAt:new Date()}});await writeAudit({action:'user.status',entity:'user',entityId:String(user._id),before,after:{isActive:user.isActive},ip:request.ip});return{success:true,data:userView(user)}});
 app.patch('/api/users/:id/access',{preHandler:requirePermission(PERMISSIONS.USER_MANAGE)},async(request:any)=>{if(String(request.params.id)===String(request.auth.sub))throw new AppError(409,'SELF_ACCESS_CHANGE','Use another School Admin to change your own role or permissions');const user:any=await User.findById(request.params.id);if(!user)throw new AppError(404,'NOT_FOUND','User not found');const before={role:user.role,permissions:user.permissions},access=normalizeAccess(request.body?.role??user.role,request.body?.permissions);user.role=access.role;user.permissions=access.permissions;user.updatedAt=new Date();await user.save();await Session.updateMany({userId:user._id,revokedAt:null},{$set:{revokedAt:new Date()}});await writeAudit({action:'user.access',entity:'user',entityId:String(user._id),before,after:{role:user.role,permissions:user.permissions},ip:request.ip});return{success:true,data:userView(user),meta:{sessionsRevoked:true}}});
 app.post('/api/account/change-password',{preHandler:authenticate},async(request:any)=>{const user=await User.findById(request.auth.sub).select('+passwordHash');if(!user)throw unauthorized();if(!(await bcrypt.compare(String(request.body?.currentPassword||''),user.passwordHash)))throw unauthorized('Current password is incorrect');const next=String(request.body?.newPassword||'');if(next.length<8)throw new AppError(400,'WEAK_PASSWORD','New password must be at least 8 characters');if(await bcrypt.compare(next,user.passwordHash))throw new AppError(400,'PASSWORD_REUSE','New password must be different from the current password');user.passwordHash=await bcrypt.hash(next,12);user.mustChangePassword=false;user.updatedAt=new Date();await user.save();await Session.updateMany({userId:user._id,revokedAt:null},{$set:{revokedAt:new Date()}});await writeAudit({action:'account.password-change',entity:'user',entityId:String(user._id),after:{sessionsRevoked:true},ip:request.ip});return{success:true,data:{changed:true,reauthenticate:true}}});
}
