import { afterAll,afterEach,beforeAll,describe,expect,it } from 'vitest';
import { connectDb,disconnectDb } from '../src/core/db.js';
import { runWithTenant } from '../src/core/tenant-context.js';
import { School } from '../src/modules/tenancy/models.js';
import { AcademicClass,Section,Subject,TeacherSubjectMap } from '../src/modules/academics/models.js';
import { Guardian,Student,Teacher } from '../src/modules/people/models.js';
import { assertStudentAccessible,studentReadScope } from '../src/modules/people/access.js';
let schoolId='';
beforeAll(async()=>{await connectDb();const school=await School.create({name:'Privacy School',code:`P${Date.now()}`,status:'ACTIVE'});schoolId=String(school._id)});
afterEach(async()=>{await runWithTenant({isPlatform:true},async()=>{await Promise.all([Student.deleteMany({}),Guardian.deleteMany({}),Teacher.deleteMany({}),TeacherSubjectMap.deleteMany({}),Section.deleteMany({}),AcademicClass.deleteMany({}),Subject.deleteMany({})])})});
afterAll(async()=>{await School.findByIdAndDelete(schoolId);await disconnectDb()});
async function seed(){return runWithTenant({schoolId},async()=>{const klass=await AcademicClass.create({name:'10'}),sectionA=await Section.create({name:'A',classId:klass._id}),sectionB=await Section.create({name:'B',classId:klass._id}),subject=await Subject.create({name:'Maths',code:'MATH'});const a=await Student.create({firstName:'Asha',admissionNo:'A1',classId:klass._id,sectionId:sectionA._id}),b=await Student.create({firstName:'Bharat',admissionNo:'B1',classId:klass._id,sectionId:sectionB._id}),parent=await Guardian.create({firstName:'Parent',relation:'Mother',studentIds:[a._id]}),teacher=await Teacher.create({firstName:'Teach',employeeNo:'T1'});await TeacherSubjectMap.create({teacherId:teacher._id,classId:klass._id,sectionId:sectionA._id,subjectId:subject._id});return{a,b,parent,teacher}})}
describe('same-tenant data scopes',()=>{it('student scope contains only the authenticated student',async()=>{const{a,b}=await seed();await runWithTenant({schoolId},async()=>{const scope=await studentReadScope({auth:{role:'STUDENT',profileId:String(a._id)}});const rows=await Student.find(scope).lean();expect(rows.map(r=>String(r._id))).toEqual([String(a._id)]);await expect(assertStudentAccessible({auth:{role:'STUDENT',profileId:String(a._id)}},b._id)).rejects.toMatchObject({statusCode:404})})});it('parent sees linked children only',async()=>{const{a,b,parent}=await seed();await runWithTenant({schoolId},async()=>{const scope=await studentReadScope({auth:{role:'PARENT',profileId:String(parent._id)}});const rows=await Student.find(scope).lean();expect(rows.map(r=>String(r._id))).toEqual([String(a._id)]);await expect(assertStudentAccessible({auth:{role:'PARENT',profileId:String(parent._id)}},b._id)).rejects.toMatchObject({statusCode:404})})});it('teacher sees students only in mapped sections',async()=>{const{a,teacher}=await seed();await runWithTenant({schoolId},async()=>{const scope=await studentReadScope({auth:{role:'TEACHER',profileId:String(teacher._id)}});const rows=await Student.find(scope).lean();expect(rows.map(r=>String(r._id))).toEqual([String(a._id)])})});it('school admin remains tenant-wide',async()=>{await seed();await runWithTenant({schoolId},async()=>{const scope=await studentReadScope({auth:{role:'SCHOOL_ADMIN'}});expect(scope).toEqual({});expect(await Student.countDocuments(scope)).toBe(2)})})});
