import { afterAll,afterEach,beforeAll,describe,expect,it } from 'vitest';
import { connectDb,disconnectDb } from '../src/core/db.js';
import { runWithTenant } from '../src/core/tenant-context.js';
import { School } from '../src/modules/tenancy/models.js';
import { AcademicClass,AcademicSession,Section,Subject,TeacherSubjectMap } from '../src/modules/academics/models.js';
import { Guardian,Student,Teacher } from '../src/modules/people/models.js';
import { assertTeacherCanEnterMarks,examReadScope,validateMarkRecord,validateSubjectConfigs } from '../src/modules/examinations/access.js';
let schoolId='';
beforeAll(async()=>{await connectDb();const school=await School.create({name:'Exam Scope',code:`E${Date.now().toString(36)}`,status:'ACTIVE'});schoolId=String(school._id)});
afterEach(async()=>{await runWithTenant({isPlatform:true},async()=>Promise.all([TeacherSubjectMap.deleteMany({}),Guardian.deleteMany({}),Student.deleteMany({}),Teacher.deleteMany({}),Section.deleteMany({}),AcademicClass.deleteMany({}),AcademicSession.deleteMany({}),Subject.deleteMany({})]))});
afterAll(async()=>{if(schoolId)await School.findByIdAndDelete(schoolId);await disconnectDb()});
describe('exam authorization and validation',()=>{
 it('scopes student and parent exam reads to their own published class/section exams',async()=>{await runWithTenant({schoolId},async()=>{const klass=await AcademicClass.create({name:'9'}),section=await Section.create({name:'A',classId:klass._id}),student=await Student.create({firstName:'Learner',admissionNo:'EX-1',classId:klass._id,sectionId:section._id}),guardian=await Guardian.create({firstName:'Guardian',relation:'Mother',studentIds:[student._id]});for(const request of [{auth:{role:'STUDENT',profileId:String(student._id)}},{auth:{role:'PARENT',profileId:String(guardian._id)}}]){const scope:any=await examReadScope(request);expect(scope.$or).toHaveLength(1);expect(scope.$or[0].status).toBe('PUBLISHED');expect(String(scope.$or[0].classId)).toBe(String(klass._id));expect(String(scope.$or[0].sectionIds)).toBe(String(section._id))}})});
 it('returns an empty exam scope when a student or parent has no linked profile',async()=>{expect(await examReadScope({auth:{role:'STUDENT'}})).toEqual({_id:{$in:[]}});expect(await examReadScope({auth:{role:'PARENT'}})).toEqual({_id:{$in:[]}})});
 it('validates subject config and server-computed marks',()=>{const[config]=validateSubjectConfigs([{subjectId:'abc',maxMarks:100,passMarks:33,weightage:100}]);expect(validateMarkRecord({theory:60,internal:20},config)).toMatchObject({total:80,grade:'A'});expect(()=>validateMarkRecord({theory:90,internal:20},config)).toThrow(/maximum/i);expect(()=>validateSubjectConfigs([{subjectId:'abc',maxMarks:20,passMarks:30}])).toThrow()});
 it('teacher can enter marks only for mapped section and subject',async()=>{await runWithTenant({schoolId},async()=>{const klass=await AcademicClass.create({name:'10'}),section=await Section.create({name:'A',classId:klass._id}),other=await Section.create({name:'B',classId:klass._id}),math=await Subject.create({name:'Maths',code:'MATH'}),science=await Subject.create({name:'Science',code:'SCI'}),teacher=await Teacher.create({firstName:'T',employeeNo:'T1'}),allowedStudent=await Student.create({firstName:'A',admissionNo:'A1',classId:klass._id,sectionId:section._id}),otherStudent=await Student.create({firstName:'B',admissionNo:'B1',classId:klass._id,sectionId:other._id});await TeacherSubjectMap.create({teacherId:teacher._id,classId:klass._id,sectionId:section._id,subjectId:math._id});const request={auth:{role:'TEACHER',profileId:String(teacher._id)}};await expect(assertTeacherCanEnterMarks(request,[{studentId:allowedStudent._id,subjectId:math._id}])).resolves.toBeUndefined();await expect(assertTeacherCanEnterMarks(request,[{studentId:allowedStudent._id,subjectId:science._id}])).rejects.toMatchObject({statusCode:403});await expect(assertTeacherCanEnterMarks(request,[{studentId:otherStudent._id,subjectId:math._id}])).rejects.toMatchObject({statusCode:403})})})
});
