import { afterAll,afterEach,beforeAll,describe,expect,it } from 'vitest';
import { connectDb,disconnectDb } from '../src/core/db.js';
import { runWithTenant } from '../src/core/tenant-context.js';
import { School } from '../src/modules/tenancy/models.js';
import { Student } from '../src/modules/people/models.js';
import { FeeInvoice,FeePayment,FeeRefund } from '../src/modules/fees/models.js';
import { collectManualPayment,requestRefund } from '../src/modules/fees/service.js';
let schoolId='';
beforeAll(async()=>{await connectDb();const school=await School.create({name:'Fee Test',code:`F${Date.now()}`,status:'ACTIVE'});schoolId=String(school._id)});
afterEach(async()=>{await runWithTenant({schoolId},()=>Promise.all([FeeRefund.deleteMany({}),FeePayment.deleteMany({}),FeeInvoice.deleteMany({}),Student.deleteMany({})]))});
afterAll(async()=>{await School.findByIdAndDelete(schoolId);await disconnectDb()});
async function invoice(total=1000){return runWithTenant({schoolId},async()=>{const student=await Student.create({firstName:'Fee',admissionNo:`A${Date.now()}`});return FeeInvoice.create({invoiceNo:`INV-${Date.now()}`,studentId:student._id,total,balance:total,paid:0})})}
describe('fee ledger idempotency',()=>{it('applies a retried manual collection only once',async()=>{await runWithTenant({schoolId},async()=>{const inv=await invoice();const input={invoiceId:inv._id,amount:400,mode:'CASH',idempotencyKey:'cash_payment_001',collectedBy:null};const first=await collectManualPayment(input);const second=await collectManualPayment(input);expect(first.payment._id.toString()).toBe(second.payment._id.toString());const current:any=await FeeInvoice.findById(inv._id).lean();expect(current.paid).toBe(400);expect(current.balance).toBe(600);expect(current.appliedPaymentKeys).toEqual(['cash_payment_001']);expect(await FeePayment.countDocuments()).toBe(1)})});it('rejects reuse of a key with different money',async()=>{await runWithTenant({schoolId},async()=>{const inv=await invoice();await collectManualPayment({invoiceId:inv._id,amount:200,mode:'CASH',idempotencyKey:'cash_payment_002',collectedBy:null});await expect(collectManualPayment({invoiceId:inv._id,amount:300,mode:'CASH',idempotencyKey:'cash_payment_002',collectedBy:null})).rejects.toMatchObject({statusCode:409})})});it('prevents cumulative refund requests above the payment amount',async()=>{await runWithTenant({schoolId},async()=>{const inv=await invoice();const result=await collectManualPayment({invoiceId:inv._id,amount:500,mode:'CASH',idempotencyKey:'cash_payment_003',collectedBy:null});await requestRefund({paymentId:result.payment._id,amount:300,idempotencyKey:'refund_req_001',requestedBy:null});await expect(requestRefund({paymentId:result.payment._id,amount:250,idempotencyKey:'refund_req_002',requestedBy:null})).rejects.toMatchObject({statusCode:409})})})});
