import { PutObjectCommand,type S3Client } from '@aws-sdk/client-s3';
import { createHash } from 'node:crypto';
import { PDFDocument,StandardFonts,rgb,type PDFFont,type PDFPage } from 'pdf-lib';

export type ReportJobData={reportCardId:string;schoolId:string;bucket:string;key:string;fileName:string;render:{schoolName:string;schoolAddress?:string;studentName:string;admissionNo:string;rollNo?:string;className?:string;sectionName?:string;examName:string;term?:string;subjects:Array<{name:string;maxMarks:number;obtained:number;grade?:string;remark?:string}>;obtained:number;maximum:number;percentage:number;grade:string;result:string;attendancePercentage:number;attendancePresent:number;attendanceTotal:number;published:boolean}};
type InternalPost=(path:string,body:unknown)=>Promise<unknown>;
const PAGE:[number,number]=[595.28,841.89],MARGIN=46;
function clipped(text:unknown,max=120){return String(text??'').replace(/[\r\n]+/g,' ').trim().slice(0,max)}
function drawRight(page:PDFPage,text:string,x:number,y:number,font:PDFFont,size:number){page.drawText(text,{x:x-font.widthOfTextAtSize(text,size),y,font,size,color:rgb(.16,.19,.26)})}

export async function renderReportCard(s3:S3Client,internalPost:InternalPost,data:ReportJobData){
 if(!data?.reportCardId||!data?.schoolId||!data?.bucket||!data?.key||!data?.render?.studentName)throw new Error('Invalid report job payload');const prefix=`schools/${data.schoolId}/report-cards/`;if(!data.key.startsWith(prefix)||!data.key.endsWith('.pdf'))throw new Error('Report destination is outside the approved school prefix');if(data.render.subjects.length>100)throw new Error('Report contains too many subject rows');
 await internalPost('/internal/report-cards/render-result',{reportCardId:data.reportCardId,schoolId:data.schoolId,key:data.key,status:'RENDERING'});
 try{
  const pdf=await PDFDocument.create(),regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);pdf.setTitle(`${data.render.examName} - ${data.render.studentName}`);pdf.setSubject('School report card');pdf.setProducer('ERP BY ANMOL report worker');pdf.setCreationDate(new Date());let page=pdf.addPage(PAGE),y=PAGE[1]-48;
  const center=(text:string,font:PDFFont,size:number)=>{const value=clipped(text,180);page.drawText(value,{x:(PAGE[0]-font.widthOfTextAtSize(value,size))/2,y,font,size,color:rgb(.07,.11,.19)});y-=size+7};
  const header=()=>{center(data.render.schoolName,bold,17);if(data.render.schoolAddress)center(data.render.schoolAddress,regular,8);y-=5;page.drawLine({start:{x:MARGIN,y},end:{x:PAGE[0]-MARGIN,y},thickness:.8,color:rgb(.82,.85,.9)});y-=27;center('REPORT CARD',bold,15);center(`${data.render.examName}${data.render.term?` · ${data.render.term}`:''}`,regular,10);y-=11};
  const continuation=()=>{page=pdf.addPage(PAGE);y=PAGE[1]-46;page.drawText(clipped(data.render.schoolName,100),{x:MARGIN,y,font:bold,size:10,color:rgb(.18,.22,.3)});drawRight(page,'Report card · continuation',PAGE[0]-MARGIN,y,regular,8);y-=28};
  header();const info=[['Student',data.render.studentName],['Admission no.',data.render.admissionNo],['Roll no.',data.render.rollNo||'—'],['Class / Section',[data.render.className,data.render.sectionName].filter(Boolean).join(' / ')||'—']];for(let i=0;i<info.length;i+=2){const left=info[i],right=info[i+1];page.drawText(left[0],{x:MARGIN,y,font:regular,size:8,color:rgb(.44,.48,.56)});page.drawText(clipped(left[1],75),{x:MARGIN+78,y,font:bold,size:9});page.drawText(right[0],{x:PAGE[0]/2+8,y,font:regular,size:8,color:rgb(.44,.48,.56)});page.drawText(clipped(right[1],60),{x:PAGE[0]/2+80,y,font:bold,size:9});y-=20}y-=8;
  const columns={subject:MARGIN,max:365,obtained:432,grade:510};const tableHeader=()=>{page.drawRectangle({x:MARGIN,y:y-5,width:PAGE[0]-MARGIN*2,height:22,color:rgb(.955,.965,.98)});page.drawText('Subject',{x:columns.subject+7,y,font:bold,size:8});page.drawText('Max',{x:columns.max,y,font:bold,size:8});page.drawText('Obtained',{x:columns.obtained,y,font:bold,size:8});page.drawText('Grade',{x:columns.grade,y,font:bold,size:8});y-=27};tableHeader();
  for(const subject of data.render.subjects){if(y<115){continuation();tableHeader()}page.drawText(clipped(subject.name,54),{x:columns.subject+7,y,font:regular,size:8.5});drawRight(page,String(Number(subject.maxMarks)||0),columns.max+30,y,regular,8.5);drawRight(page,String(Number(subject.obtained)||0),columns.obtained+43,y,bold,8.5);page.drawText(clipped(subject.grade||'—',8),{x:columns.grade,y,font:bold,size:8.5});page.drawLine({start:{x:MARGIN,y:y-7},end:{x:PAGE[0]-MARGIN,y:y-7},thickness:.35,color:rgb(.9,.92,.95)});y-=22}
  if(y<150)continuation();y-=8;page.drawRectangle({x:MARGIN,y:y-48,width:PAGE[0]-MARGIN*2,height:58,borderWidth:.7,borderColor:rgb(.82,.85,.9)});page.drawText('Academic summary',{x:MARGIN+10,y:y-7,font:bold,size:9});page.drawText(`Total: ${data.render.obtained} / ${data.render.maximum}`,{x:MARGIN+10,y:y-26,font:regular,size:9});page.drawText(`Percentage: ${Number(data.render.percentage).toFixed(2)}%`,{x:MARGIN+165,y:y-26,font:regular,size:9});page.drawText(`Grade: ${clipped(data.render.grade,8)}`,{x:MARGIN+330,y:y-26,font:bold,size:9});page.drawText(`Result: ${clipped(data.render.result,16)}`,{x:MARGIN+400,y:y-26,font:bold,size:9,color:data.render.result==='PASS'?rgb(.05,.42,.31):rgb(.66,.18,.15)});y-=70;
  page.drawText('Attendance',{x:MARGIN,y,font:bold,size:9});page.drawText(`${data.render.attendancePresent} present / ${data.render.attendanceTotal} records · ${Number(data.render.attendancePercentage).toFixed(2)}%`,{x:MARGIN+78,y,font:regular,size:9,color:rgb(.25,.29,.36)});page.drawText(data.render.published?'Published result':'Generated from locked marks',{x:MARGIN,y:38,font:regular,size:7.5,color:rgb(.46,.49,.56)});drawRight(page,`Report ID: ${data.reportCardId}`,PAGE[0]-MARGIN,38,regular,7.5);
  const bytes=await pdf.save(),checksum=createHash('sha256').update(bytes).digest('hex');await s3.send(new PutObjectCommand({Bucket:data.bucket,Key:data.key,Body:bytes,ContentType:'application/pdf',ContentDisposition:`attachment; filename="${String(data.fileName||'report-card.pdf').replace(/["\r\n]/g,'_')}"`,Metadata:{'report-card-id':data.reportCardId,'school-id':data.schoolId,'sha256':checksum}}));await internalPost('/internal/report-cards/render-result',{reportCardId:data.reportCardId,schoolId:data.schoolId,key:data.key,status:'READY',bytes:bytes.length,checksum});return{bytes:bytes.length,checksum};
 }catch(error){const detail=error instanceof Error?error.message:'Unknown report renderer error';await internalPost('/internal/report-cards/render-result',{reportCardId:data.reportCardId,schoolId:data.schoolId,key:data.key,status:'FAILED',detail}).catch(()=>undefined);throw error}
}
