import type{FastifyInstance}from'fastify';
import{Types}from'mongoose';
import{PERMISSIONS}from'@erp/contracts';
import{requirePermission}from'../../core/security.js';
import{AppError,forbidden}from'../../core/errors.js';
import{writeAudit}from'../../core/audit.js';
import{OasesExamConfig,OasesAnswerSheet,OasesEvaluation}from'./models.js';
import{Exam}from'../examinations/models.js';
import{Student}from'../people/models.js';
import{User}from'../identity/models.js';
import{FileAsset}from'../files/models.js';

const validId=(value:any)=>Types.ObjectId.isValid(String(value||''));
const clean=(value:any,max=2000)=>String(value??'').trim().slice(0,max);
function isAdmin(request:any){return request.auth?.role==='SCHOOL_ADMIN'}
function hasOasesRole(request:any,role:'SCAN_OPERATOR'|'EVALUATOR'|'HEAD_EXAMINER'){return isAdmin(request)||(request.auth?.oasesRoles||[]).includes(role)}
function requireOasesRole(...roles:('SCAN_OPERATOR'|'EVALUATOR'|'HEAD_EXAMINER')[]){return async(request:any)=>{if(!roles.some(role=>hasOasesRole(request,role)))throw forbidden(`OASES role required: ${roles.join(' or ')}`)}}
function questionScheme(value:any){if(!Array.isArray(value)||value.length<1||value.length>300)throw new AppError(400,'INVALID_SCHEME','Question scheme needs 1 to 300 questions');const seen=new Set<string>();const rows=value.map((raw:any,index:number)=>{const questionNo=clean(raw?.questionNo,40),maxMarks=Number(raw?.maxMarks),section=clean(raw?.section,80)||undefined;if(!questionNo||seen.has(questionNo))throw new AppError(400,'INVALID_QUESTION',`Question ${index+1} has an empty or duplicate number`);if(!Number.isFinite(maxMarks)||maxMarks<=0||maxMarks>1000)throw new AppError(400,'INVALID_MAX_MARKS',`Question ${questionNo} has invalid max marks`);seen.add(questionNo);return{questionNo,maxMarks:Math.round(maxMarks*100)/100,section}});return{rows,totalMaxMarks:Math.round(rows.reduce((sum,row)=>sum+row.maxMarks,0)*100)/100}}
function marksFor(config:any,value:any,complete:boolean){if(!Array.isArray(value)||value.length>config.questionScheme.length)throw new AppError(400,'INVALID_MARKS','Marks payload is invalid');const scheme=new Map((config.questionScheme||[]).map((q:any)=>[String(q.questionNo),Number(q.maxMarks)])),seen=new Set<string>(),marks=value.map((raw:any)=>{const questionNo=clean(raw?.questionNo,40),max=scheme.get(questionNo),marks=Number(raw?.marks);if(max===undefined||seen.has(questionNo)||!Number.isFinite(marks)||marks<0||marks>max)throw new AppError(422,'INVALID_MARK','Question marks exceed the configured scheme or contain duplicates');seen.add(questionNo);return{questionNo,marks:Math.round(marks*100)/100,remark:clean(raw?.remark,500)||undefined}});if(complete&&seen.size!==scheme.size)throw new AppError(422,'INCOMPLETE_EVALUATION','All configured questions must be marked before submission');return{marks,total:Math.round(marks.reduce((sum,row)=>sum+row.marks,0)*100)/100}}
async function readyAssets(ids:any){if(!Array.isArray(ids)||ids.length<1||ids.length>20||ids.some(id=>!validId(id)))throw new AppError(400,'INVALID_SCAN_ASSETS','Provide 1 to 20 valid scan asset IDs');const unique=[...new Set(ids.map(String))],assets:any[]=await FileAsset.find({_id:{$in:unique},purpose:'oases-scan',status:'READY',scanStatus:{$in:['CLEAN','SKIPPED']}}).select('_id').lean();if(assets.length!==unique.length)throw new AppError(422,'SCAN_NOT_READY','Every answer-sheet scan must be uploaded and malware-cleared');return unique.map(id=>new Types.ObjectId(id))}
async function configById(id:any){if(!validId(id))throw new AppError(400,'INVALID_CONFIG','Invalid OASES config');const config:any=await OasesExamConfig.findById(id);if(!config)throw new AppError(404,'CONFIG_NOT_FOUND','OASES config not found');return config}

export async function oasesRoutes(app:FastifyInstance){
 app.get('/api/oases/configs',{preHandler:requirePermission(PERMISSIONS.OASES_READ)},async()=>({success:true,data:await OasesExamConfig.find().sort({createdAt:-1}).limit(300).lean()}));
 app.post('/api/oases/configs',{preHandler:[requirePermission(PERMISSIONS.OASES_EVALUATE),requireOasesRole('HEAD_EXAMINER')]},async(request:any)=>{const name=clean(request.body?.name,180),examId=request.body?.examId;if(!name||!validId(examId)||!await Exam.findById(examId).select('_id').lean())throw new AppError(400,'INVALID_CONFIG','Name and a valid exam are required');const scheme=questionScheme(request.body?.questionScheme),item=await OasesExamConfig.create({name,examId,questionScheme:scheme.rows,totalMaxMarks:scheme.totalMaxMarks,status:'DRAFT',createdBy:request.auth.sub,createdAt:new Date(),updatedAt:new Date()});await writeAudit({action:'oases.config-create',entity:'oases-config',entityId:String(item._id),after:{name:item.name,examId:String(item.examId),totalMaxMarks:item.totalMaxMarks},ip:request.ip});return{success:true,data:item}});
 app.patch('/api/oases/configs/:id',{preHandler:[requirePermission(PERMISSIONS.OASES_EVALUATE),requireOasesRole('HEAD_EXAMINER')]},async(request:any)=>{const item=await configById(request.params.id);if(item.status!=='DRAFT')throw new AppError(409,'CONFIG_LOCKED','Question scheme can only change while config is DRAFT');const before={name:item.name,questionScheme:item.questionScheme,totalMaxMarks:item.totalMaxMarks};if(request.body?.name!==undefined){const name=clean(request.body.name,180);if(!name)throw new AppError(400,'INVALID_NAME','Config name is required');item.name=name}if(request.body?.questionScheme!==undefined){const scheme=questionScheme(request.body.questionScheme);item.questionScheme=scheme.rows;item.totalMaxMarks=scheme.totalMaxMarks}item.updatedAt=new Date();await item.save();await writeAudit({action:'oases.config-update',entity:'oases-config',entityId:String(item._id),before,after:{name:item.name,questionScheme:item.questionScheme,totalMaxMarks:item.totalMaxMarks},ip:request.ip});return{success:true,data:item}});
 app.post('/api/oases/configs/:id/transition',{preHandler:[requirePermission(PERMISSIONS.OASES_EVALUATE),requireOasesRole('HEAD_EXAMINER')]},async(request:any)=>{const item=await configById(request.params.id),next=String(request.body?.status||''),allowed:any={DRAFT:['SCANNING'],SCANNING:['EVALUATION'],EVALUATION:['MODERATION'],MODERATION:['PUBLISHED'],PUBLISHED:[]};if(!allowed[item.status]?.includes(next))throw new AppError(409,'INVALID_TRANSITION',`Cannot move OASES config from ${item.status} to ${next}`);const sheetCount=await OasesAnswerSheet.countDocuments({examConfigId:item._id});if(next==='EVALUATION'&&!sheetCount)throw new AppError(409,'NO_SHEETS','Upload answer sheets before evaluation');if(next==='MODERATION'&&await OasesAnswerSheet.exists({examConfigId:item._id,status:{$nin:['EVALUATED','MODERATED']}}))throw new AppError(409,'EVALUATION_INCOMPLETE','Every sheet must be evaluated before moderation');if(next==='PUBLISHED'&&(sheetCount===0||await OasesAnswerSheet.exists({examConfigId:item._id,status:{$ne:'MODERATED'}})))throw new AppError(409,'MODERATION_INCOMPLETE','Every sheet must be moderated before publishing');const before={status:item.status};item.status=next;if(next==='PUBLISHED')item.publishedAt=new Date();item.updatedAt=new Date();await item.save();await writeAudit({action:'oases.config-transition',entity:'oases-config',entityId:String(item._id),before,after:{status:next},ip:request.ip});return{success:true,data:item}});
 app.get('/api/oases/sheets',{preHandler:requirePermission(PERMISSIONS.OASES_READ)},async(request:any)=>{const filter:any={};if(request.query?.configId)filter.examConfigId=request.query.configId;if(request.query?.status)filter.status=request.query.status;if(hasOasesRole(request,'EVALUATOR')&&!hasOasesRole(request,'HEAD_EXAMINER')&&!isAdmin(request))filter.assignedEvaluatorId=request.auth.sub;return{success:true,data:await OasesAnswerSheet.find(filter).sort({createdAt:-1}).limit(1000).lean()}});
 app.post('/api/oases/sheets',{preHandler:[requirePermission(PERMISSIONS.OASES_EVALUATE),requireOasesRole('SCAN_OPERATOR','HEAD_EXAMINER')]},async(request:any)=>{const config=await configById(request.body?.examConfigId);if(!['SCANNING','EVALUATION'].includes(config.status))throw new AppError(409,'CONFIG_STATE','Sheets may only be uploaded during scanning/evaluation');const sheetCode=clean(request.body?.sheetCode,100).toUpperCase();if(!/^[A-Z0-9._/-]{3,100}$/.test(sheetCode))throw new AppError(400,'INVALID_SHEET_CODE','Invalid sheet code');let studentId:any=undefined;if(request.body?.studentId){if(!validId(request.body.studentId)||!await Student.findById(request.body.studentId).select('_id').lean())throw new AppError(404,'STUDENT_NOT_FOUND','Student not found');studentId=request.body.studentId}const scanAssetIds=await readyAssets(request.body?.scanAssetIds),item=await OasesAnswerSheet.create({examConfigId:config._id,studentId,sheetCode,scanAssetIds,status:'UPLOADED',createdBy:request.auth.sub,createdAt:new Date(),updatedAt:new Date()});await writeAudit({action:'oases.sheet-upload',entity:'oases-sheet',entityId:String(item._id),after:{configId:String(config._id),sheetCode,studentId,scanCount:scanAssetIds.length},ip:request.ip});return{success:true,data:item}});
 app.post('/api/oases/sheets/:id/assign',{preHandler:[requirePermission(PERMISSIONS.OASES_EVALUATE),requireOasesRole('HEAD_EXAMINER')]},async(request:any)=>{const evaluatorId=request.body?.evaluatorId;if(!validId(evaluatorId))throw new AppError(400,'INVALID_EVALUATOR','Valid evaluatorId is required');const evaluator:any=await User.findOne({_id:evaluatorId,isActive:true,oasesRoles:'EVALUATOR',permissions:PERMISSIONS.OASES_EVALUATE}).select('_id').lean();if(!evaluator)throw new AppError(404,'EVALUATOR_NOT_FOUND','Active evaluator with OASES permission not found');const sheet:any=await OasesAnswerSheet.findById(request.params.id);if(!sheet)throw new AppError(404,'SHEET_NOT_FOUND','Answer sheet not found');const config=await configById(sheet.examConfigId);if(config.status!=='EVALUATION')throw new AppError(409,'CONFIG_STATE','Evaluator assignment requires EVALUATION state');if(['EVALUATED','MODERATED'].includes(sheet.status))throw new AppError(409,'SHEET_LOCKED','Evaluated sheet cannot be reassigned');const before={assignedEvaluatorId:sheet.assignedEvaluatorId,status:sheet.status};sheet.assignedEvaluatorId=evaluator._id;sheet.assignedAt=new Date();sheet.status='ASSIGNED';sheet.updatedAt=new Date();await sheet.save();await writeAudit({action:'oases.sheet-assign',entity:'oases-sheet',entityId:String(sheet._id),before,after:{assignedEvaluatorId:String(evaluator._id),status:sheet.status},ip:request.ip});return{success:true,data:sheet}});
 app.get('/api/oases/evaluations',{preHandler:requirePermission(PERMISSIONS.OASES_READ)},async(request:any)=>{const filter:any={};if(request.query?.sheetId)filter.sheetId=request.query.sheetId;if(hasOasesRole(request,'EVALUATOR')&&!hasOasesRole(request,'HEAD_EXAMINER')&&!isAdmin(request))filter.evaluatorId=request.auth.sub;return{success:true,data:await OasesEvaluation.find(filter).sort({updatedAt:-1}).limit(1000).lean()}});
 app.post('/api/oases/evaluations',{preHandler:[requirePermission(PERMISSIONS.OASES_EVALUATE),requireOasesRole('EVALUATOR')]},async(request:any)=>{const sheet:any=await OasesAnswerSheet.findById(request.body?.sheetId);if(!sheet||String(sheet.assignedEvaluatorId||'')!==String(request.auth.sub))throw new AppError(404,'ASSIGNMENT_NOT_FOUND','Assigned answer sheet not found');const config=await configById(sheet.examConfigId);if(config.status!=='EVALUATION')throw new AppError(409,'CONFIG_STATE','Evaluation is not open');const existing:any=await OasesEvaluation.findOne({sheetId:sheet._id,evaluatorId:request.auth.sub});if(existing?.status!=='DRAFT'&&existing)throw new AppError(409,'EVALUATION_LOCKED','Submitted evaluation cannot be edited');const status=request.body?.status==='SUBMITTED'?'SUBMITTED':'DRAFT',validated=marksFor(config,request.body?.marks||[],status==='SUBMITTED'),item=await OasesEvaluation.findOneAndUpdate({sheetId:sheet._id,evaluatorId:request.auth.sub},{$set:{marks:validated.marks,total:validated.total,status,submittedAt:status==='SUBMITTED'?new Date():undefined,updatedAt:new Date()},$setOnInsert:{createdAt:new Date()}},{new:true,upsert:true,setDefaultsOnInsert:true});if(status==='SUBMITTED'){sheet.status='EVALUATED';sheet.updatedAt=new Date();await sheet.save();await writeAudit({action:'oases.evaluation-submit',entity:'oases-evaluation',entityId:String(item._id),after:{sheetId:String(sheet._id),total:item.total},ip:request.ip})}return{success:true,data:item}});
 app.post('/api/oases/evaluations/:id/moderate',{preHandler:[requirePermission(PERMISSIONS.OASES_EVALUATE),requireOasesRole('HEAD_EXAMINER')]},async(request:any)=>{const item:any=await OasesEvaluation.findById(request.params.id);if(!item)throw new AppError(404,'EVALUATION_NOT_FOUND','Evaluation not found');if(item.status==='MODERATED')return{success:true,data:item};if(item.status!=='SUBMITTED')throw new AppError(409,'EVALUATION_STATE','Only submitted evaluations can be moderated');const sheet:any=await OasesAnswerSheet.findById(item.sheetId);if(!sheet)throw new AppError(404,'SHEET_NOT_FOUND','Answer sheet not found');const config=await configById(sheet.examConfigId);if(config.status!=='MODERATION')throw new AppError(409,'CONFIG_STATE','Config is not in moderation');const validated=request.body?.marks?marksFor(config,request.body.marks,true):{marks:item.marks,total:item.total};item.moderatedMarks=validated.marks;item.moderatedTotal=validated.total;item.moderatedBy=request.auth.sub;item.moderationNote=clean(request.body?.note,2000)||undefined;item.moderatedAt=new Date();item.status='MODERATED';item.updatedAt=new Date();await item.save();sheet.status='MODERATED';sheet.updatedAt=new Date();await sheet.save();await writeAudit({action:'oases.evaluation-moderate',entity:'oases-evaluation',entityId:String(item._id),before:{total:item.total},after:{moderatedTotal:item.moderatedTotal,sheetId:String(sheet._id)},ip:request.ip});return{success:true,data:item}});
 app.get('/api/oases/results/:configId',{preHandler:requirePermission(PERMISSIONS.OASES_READ)},async(request:any)=>{const config=await configById(request.params.configId);if(config.status!=='PUBLISHED'&&!hasOasesRole(request,'HEAD_EXAMINER')&&!isAdmin(request))throw forbidden('OASES results are not published');const sheets:any[]=await OasesAnswerSheet.find({examConfigId:config._id}).select('_id sheetCode studentId status').lean(),ids=sheets.map(sheet=>sheet._id),evaluations:any[]=await OasesEvaluation.find({sheetId:{$in:ids},status:'MODERATED'}).lean(),bySheet=new Map(evaluations.map(item=>[String(item.sheetId),item]));return{success:true,data:sheets.map(sheet=>{const evaluation=bySheet.get(String(sheet._id));return{sheetCode:sheet.sheetCode,studentId:sheet.studentId,status:sheet.status,total:evaluation?.moderatedTotal??evaluation?.total??null,maxMarks:config.totalMaxMarks}})}});
}
