import type { FastifyInstance } from 'fastify';
import { PERMISSIONS } from '@erp/contracts';
import { requirePermission } from '../../core/security.js';
import { AppError } from '../../core/errors.js';
import { Student,Teacher,Staff } from '../people/models.js';
import { Admission } from '../admissions/models.js';
import { Attendance } from '../attendance/models.js';
import { Exam } from '../examinations/models.js';
import { FeeInvoice,FeePayment } from '../fees/models.js';
import { LeaveRequest } from '../leaves/models.js';

const money=(n:any)=>Math.round(Number(n||0)*100)/100;
function utcDay(date:Date){return new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate()))}
export async function analyticsRoutes(app:FastifyInstance){
 app.get('/api/analytics/overview',{preHandler:requirePermission(PERMISSIONS.ANALYTICS_READ)},async()=>{const today=utcDay(new Date()),tomorrow=new Date(today.getTime()+86400000);const[students,teachers,staff,admissionStages,pendingLeaves,feeAgg,paymentsToday,attendanceToday,examStages]=await Promise.all([Student.countDocuments({lifecycle:'ACTIVE',status:'ACTIVE'}),Teacher.countDocuments({status:'ACTIVE'}),Staff.countDocuments({status:'ACTIVE'}),Admission.aggregate([{$group:{_id:'$status',count:{$sum:1}}}]),LeaveRequest.countDocuments({status:'PENDING'}),FeeInvoice.aggregate([{$match:{status:{$ne:'CANCELLED'}}},{$group:{_id:null,total:{$sum:'$total'},paid:{$sum:'$paid'},balance:{$sum:'$balance'}}}]),FeePayment.aggregate([{$match:{status:'SUCCESS',createdAt:{$gte:today,$lt:tomorrow}}},{$group:{_id:null,amount:{$sum:'$amount'},count:{$sum:1}}}]),Attendance.aggregate([{$match:{date:{$gte:today,$lt:tomorrow}}},{$group:{_id:'$status',count:{$sum:1}}}]),Exam.aggregate([{$group:{_id:'$status',count:{$sum:1}}}])]);const stages:Record<string,number>=Object.fromEntries(admissionStages.map((row:any)=>[String(row._id),Number(row.count||0)])),attendance:Record<string,number>=Object.fromEntries(attendanceToday.map((row:any)=>[String(row._id),Number(row.count||0)])),exams:Record<string,number>=Object.fromEntries(examStages.map((row:any)=>[String(row._id),Number(row.count||0)])),fee=feeAgg[0]||{total:0,paid:0,balance:0},todayPayments=paymentsToday[0]||{amount:0,count:0},attendanceTotal=Object.values(attendance).reduce((sum:number,value:number)=>sum+value,0),present=Number(attendance.PRESENT||0)+Number(attendance.LATE||0);return{success:true,data:{people:{students,teachers,staff},admissions:{pending:Number(stages.APPLIED||0)+Number(stages.DOCUMENT_VERIFICATION||0)+Number(stages.UNDER_REVIEW||0),stages},leaves:{pending:pendingLeaves},fees:{total:money(fee.total),paid:money(fee.paid),balance:money(fee.balance),todayCollected:money(todayPayments.amount),todayReceipts:Number(todayPayments.count||0)},attendance:{total:attendanceTotal,present,absent:Number(attendance.ABSENT||0),late:Number(attendance.LATE||0),leave:Number(attendance.LEAVE||0),percentage:attendanceTotal?Math.round(present/attendanceTotal*10000)/100:0},exams}}});
 app.get('/api/analytics/trends',{preHandler:requirePermission(PERMISSIONS.ANALYTICS_READ)},async(request:any)=>{const days=Math.min(90,Math.max(7,Number(request.query?.days||30)));if(!Number.isInteger(days))throw new AppError(400,'INVALID_DAYS','days must be an integer');const start=utcDay(new Date(Date.now()-(days-1)*86400000)),end=new Date(utcDay(new Date()).getTime()+86400000);const[payments,attendance,admissions]=await Promise.all([FeePayment.aggregate([{$match:{status:'SUCCESS',createdAt:{$gte:start,$lt:end}}},{$group:{_id:{$dateToString:{format:'%Y-%m-%d',date:'$createdAt',timezone:'UTC'}},amount:{$sum:'$amount'},count:{$sum:1}}},{$sort:{_id:1}}]),Attendance.aggregate([{$match:{date:{$gte:start,$lt:end}}},{$group:{_id:{day:{$dateToString:{format:'%Y-%m-%d',date:'$date',timezone:'UTC'}},status:'$status'},count:{$sum:1}}},{$sort:{'_id.day':1}}]),Admission.aggregate([{$match:{createdAt:{$gte:start,$lt:end}}},{$group:{_id:{$dateToString:{format:'%Y-%m-%d',date:'$createdAt',timezone:'UTC'}},count:{$sum:1}}},{$sort:{_id:1}}])]);const byDay=new Map<string,any>();for(let i=0;i<days;i++){const day=new Date(start.getTime()+i*86400000).toISOString().slice(0,10);byDay.set(day,{day,collections:0,receipts:0,attendance:{present:0,absent:0,late:0,leave:0,total:0},admissions:0})}for(const row of payments){const item=byDay.get(row._id);if(item){item.collections=money(row.amount);item.receipts=row.count}}for(const row of attendance){const item=byDay.get(row._id.day);if(item){const key=String(row._id.status).toLowerCase();item.attendance[key]=row.count;item.attendance.total+=row.count}}for(const row of admissions){const item=byDay.get(row._id);if(item)item.admissions=row.count}for(const item of byDay.values()){const present=Number(item.attendance.present||0)+Number(item.attendance.late||0);item.attendance.percentage=item.attendance.total?Math.round(present/item.attendance.total*10000)/100:0}return{success:true,data:[...byDay.values()]}});
}
