import type { FastifyInstance } from 'fastify';
import { Types } from 'mongoose';
import { PERMISSIONS } from '@erp/contracts';
import { registerCrud } from '../../core/crud.js';
import { AppError } from '../../core/errors.js';
import { Teacher } from '../people/models.js';
import { AcademicSession,AcademicClass,Section,Subject,TeacherSubjectMap } from './models.js';
const validId=(value:any)=>Types.ObjectId.isValid(String(value||''));
const clean=(value:any,max=120)=>String(value??'').trim().slice(0,max);
function protectedUpdate(body:any){const next={...(body??{})};for(const field of['_id','schoolId','deletedAt','createdAt'] as const)delete next[field];next.updatedAt=new Date();return next}
function parsedDate(value:any,label:string){if(value===undefined||value===null||value==='')return undefined;const date=new Date(value);if(Number.isNaN(date.getTime()))throw new AppError(400,'INVALID_DATE',`${label} is invalid`);return date}
function validateDateRange(start:Date|undefined,end:Date|undefined){if(start&&end&&start>=end)throw new AppError(400,'INVALID_SESSION_RANGE','Session end date must be after start date')}
async function ensureClass(id:any){if(!validId(id))throw new AppError(400,'INVALID_CLASS','Valid class is required');const item=await AcademicClass.findById(id).select('_id').lean();if(!item)throw new AppError(404,'CLASS_NOT_FOUND','Class not found');return item}
async function ensureMapRefs(input:any){for(const key of['teacherId','classId','sectionId','subjectId'])if(!validId(input[key]))throw new AppError(400,'INVALID_ACADEMIC_MAPPING',`${key} is required`);const[teacher,klass,section,subject]=await Promise.all([Teacher.findById(input.teacherId).select('_id').lean(),AcademicClass.findById(input.classId).select('_id').lean(),Section.findById(input.sectionId).select('_id classId').lean(),Subject.findById(input.subjectId).select('_id').lean()]);if(!teacher||!klass||!section||!subject)throw new AppError(404,'ACADEMIC_REFERENCE_NOT_FOUND','Teacher, class, section or subject does not exist in this school');if(String((section as any).classId)!==String(input.classId))throw new AppError(409,'SECTION_CLASS_MISMATCH','Section does not belong to the selected class')}
async function teacherMapReadScope(request:any){if(request.auth?.role==='SCHOOL_ADMIN')return{};if(request.auth?.role==='TEACHER'&&validId(request.auth?.profileId))return{teacherId:new Types.ObjectId(String(request.auth.profileId))};return{_id:{$in:[]}}}
export async function academicsRoutes(app:FastifyInstance){
 await registerCrud(app,{prefix:'/api/academics/sessions',model:AcademicSession,entity:'academic-session',readPermission:PERMISSIONS.ACADEMICS_READ,writePermission:PERMISSIONS.ACADEMICS_WRITE,searchable:['name'],prepareCreate:async(request:any)=>{const body=request.body??{},startDate=parsedDate(body.startDate,'Start date'),endDate=parsedDate(body.endDate,'End date');validateDateRange(startDate,endDate);if(body.isCurrent)await AcademicSession.updateMany({isCurrent:true},{$set:{isCurrent:false,updatedAt:new Date()}});return{name:clean(body.name),startDate,endDate,isCurrent:Boolean(body.isCurrent),updatedAt:new Date()}},prepareUpdate:async(request:any)=>{const current:any=await AcademicSession.findById(request.params.id).lean();if(!current)throw new AppError(404,'NOT_FOUND','Academic session not found');const body=protectedUpdate(request.body),startDate=parsedDate(body.startDate??current.startDate,'Start date'),endDate=parsedDate(body.endDate??current.endDate,'End date');validateDateRange(startDate,endDate);if(body.isCurrent===true)await AcademicSession.updateMany({_id:{$ne:request.params.id},isCurrent:true},{$set:{isCurrent:false,updatedAt:new Date()}});if(body.name!==undefined)body.name=clean(body.name);if(body.startDate!==undefined)body.startDate=startDate;if(body.endDate!==undefined)body.endDate=endDate;return body}});
 await registerCrud(app,{prefix:'/api/academics/classes',model:AcademicClass,entity:'class',readPermission:PERMISSIONS.ACADEMICS_READ,writePermission:PERMISSIONS.ACADEMICS_WRITE,searchable:['name'],prepareCreate:(request:any)=>({name:clean(request.body?.name),order:Number.isFinite(Number(request.body?.order))?Number(request.body.order):undefined,updatedAt:new Date()}),prepareUpdate:(request:any)=>{const body=protectedUpdate(request.body);if(body.name!==undefined)body.name=clean(body.name);if(body.order!==undefined)body.order=Number(body.order);return body}});
 await registerCrud(app,{prefix:'/api/academics/sections',model:Section,entity:'section',readPermission:PERMISSIONS.ACADEMICS_READ,writePermission:PERMISSIONS.ACADEMICS_WRITE,searchable:['name','room'],prepareCreate:async(request:any)=>{await ensureClass(request.body?.classId);return{name:clean(request.body?.name),classId:request.body.classId,capacity:request.body?.capacity?Number(request.body.capacity):undefined,room:clean(request.body?.room,80)||undefined,updatedAt:new Date()}},prepareUpdate:async(request:any)=>{const body=protectedUpdate(request.body);if(body.classId!==undefined)await ensureClass(body.classId);if(body.name!==undefined)body.name=clean(body.name);if(body.capacity!==undefined)body.capacity=Number(body.capacity);if(body.room!==undefined)body.room=clean(body.room,80)||undefined;return body}});
 await registerCrud(app,{prefix:'/api/academics/subjects',model:Subject,entity:'subject',readPermission:PERMISSIONS.ACADEMICS_READ,writePermission:PERMISSIONS.ACADEMICS_WRITE,searchable:['name','code'],prepareCreate:(request:any)=>({name:clean(request.body?.name),code:clean(request.body?.code,40).toUpperCase(),type:request.body?.type||'THEORY',maxMarks:request.body?.maxMarks===undefined?100:Number(request.body.maxMarks),updatedAt:new Date()}),prepareUpdate:(request:any)=>{const body=protectedUpdate(request.body);if(body.name!==undefined)body.name=clean(body.name);if(body.code!==undefined)body.code=clean(body.code,40).toUpperCase();if(body.maxMarks!==undefined)body.maxMarks=Number(body.maxMarks);return body}});
 await registerCrud(app,{prefix:'/api/academics/teacher-maps',model:TeacherSubjectMap,entity:'teacher-subject-map',readPermission:PERMISSIONS.ACADEMICS_READ,writePermission:PERMISSIONS.ACADEMICS_WRITE,readScope:teacherMapReadScope,prepareCreate:async(request:any)=>{const body=request.body??{};await ensureMapRefs(body);return{teacherId:body.teacherId,classId:body.classId,sectionId:body.sectionId,subjectId:body.subjectId,updatedAt:new Date()}},prepareUpdate:async(request:any)=>{const current:any=await TeacherSubjectMap.findById(request.params.id).lean();if(!current)throw new AppError(404,'NOT_FOUND','Teacher assignment not found');const next={...current,...protectedUpdate(request.body)};await ensureMapRefs(next);return{teacherId:next.teacherId,classId:next.classId,sectionId:next.sectionId,subjectId:next.subjectId,updatedAt:new Date()}}});
}
