import { createHmac,randomBytes,timingSafeEqual } from 'node:crypto';
const ALPHABET='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
function base32Encode(input:Buffer){let bits=0,value=0,out='';for(const byte of input){value=(value<<8)|byte;bits+=8;while(bits>=5){out+=ALPHABET[(value>>>(bits-5))&31];bits-=5}value&=(1<<bits)-1}if(bits>0)out+=ALPHABET[(value<<(5-bits))&31];return out}
function base32Decode(input:string){const clean=input.toUpperCase().replace(/[^A-Z2-7]/g,'');let bits=0,value=0;const out:number[]=[];for(const char of clean){const idx=ALPHABET.indexOf(char);if(idx<0)throw new Error('Invalid base32 secret');value=(value<<5)|idx;bits+=5;while(bits>=8){out.push((value>>>(bits-8))&255);bits-=8}value&=(1<<bits)-1}return Buffer.from(out)}
export function generateTotpSecret(bytes=20){return base32Encode(randomBytes(bytes))}
export function generateTotp(secret:string,at=Date.now(),stepSeconds=30,digits=6){const counter=BigInt(Math.floor(at/1000/stepSeconds));const message=Buffer.alloc(8);message.writeBigUInt64BE(counter);const digest=createHmac('sha1',base32Decode(secret)).update(message).digest();const offset=digest[digest.length-1]&0x0f;const binary=((digest[offset]&0x7f)<<24)|((digest[offset+1]&0xff)<<16)|((digest[offset+2]&0xff)<<8)|(digest[offset+3]&0xff);return String(binary%(10**digits)).padStart(digits,'0')}
export function verifyTotp(secret:string,code:string,at=Date.now(),window=1){const normalized=String(code||'').replace(/\s/g,'');if(!/^\d{6}$/.test(normalized))return false;for(let offset=-window;offset<=window;offset++){const expected=generateTotp(secret,at+offset*30_000);if(timingSafeEqual(Buffer.from(expected),Buffer.from(normalized)))return true}return false}
export function buildOtpAuthUri(issuer:string,account:string,secret:string){const label=`${issuer}:${account}`;return `otpauth://totp/${encodeURIComponent(label)}?secret=${encodeURIComponent(secret)}&issuer=${encodeURIComponent(issuer)}&algorithm=SHA1&digits=6&period=30`}
export function generateRecoveryCodes(count=8){return Array.from({length:count},()=>{const raw=randomBytes(8).toString('hex').toUpperCase();return `${raw.slice(0,4)}-${raw.slice(4,8)}-${raw.slice(8,12)}-${raw.slice(12,16)}`})}
export function normalizeRecoveryCode(code:string){return String(code||'').toUpperCase().replace(/[^A-F0-9]/g,'')}
