import { AppError } from '../../core/errors.js';
import { runWithTenant } from '../../core/tenant-context.js';
import { FeePayment,FeeRefund,ProviderWebhookEvent } from './models.js';
import { applyInvoicePayment,completeRefund,failRefund,markRefundProcessing } from './service.js';
import { fetchOrderPayments,fetchPayment,fetchRefund,toPaise,type RazorpayPayment } from './razorpay.js';

async function localPaymentByProvider(providerPayment:RazorpayPayment){const candidates:any[]=await FeePayment.find({provider:'RAZORPAY',providerOrderId:providerPayment.order_id,deletedAt:null}).limit(2);if(candidates.length>1)throw new AppError(500,'PROVIDER_MAPPING_CONFLICT','Provider order maps to multiple local payments');return candidates[0]||null}
export async function reconcileCapturedPayment(providerPaymentId:string){return runWithTenant({isPlatform:true},async()=>{const provider=await fetchPayment(providerPaymentId);if(provider.status!=='captured'||!provider.captured||!provider.order_id)throw new AppError(409,'PAYMENT_NOT_CAPTURED','Provider payment is not captured');const local:any=await localPaymentByProvider(provider);if(!local)return{outcome:'ignored' as const,reason:'No local payment intent'};if(provider.amount!==toPaise(Number(local.amount))||provider.currency!==(local.currency||'INR'))throw new AppError(409,'PROVIDER_AMOUNT_MISMATCH','Provider payment amount or currency does not match local intent');local.providerPaymentId=provider.id;local.providerStatus=provider.status;local.lastProviderSyncAt=new Date();local.failureReason=null;await local.save();const invoice=await applyInvoicePayment(local);return{outcome:'processed' as const,paymentId:String(local._id),invoiceId:String(invoice._id)}})}

export async function reconcileProviderRefund(providerRefundId:string){return runWithTenant({isPlatform:true},async()=>{const provider=await fetchRefund(providerRefundId);const refund:any=await FeeRefund.findOne({providerRefundId:provider.id,deletedAt:null});if(!refund)return{outcome:'ignored' as const,reason:'No local refund'};const payment:any=await FeePayment.findOne({_id:refund.paymentId,schoolId:refund.schoolId,deletedAt:null});if(!payment)throw new AppError(404,'NOT_FOUND','Refund payment not found');if(provider.payment_id!==payment.providerPaymentId||provider.amount!==toPaise(Number(refund.amount)))throw new AppError(409,'PROVIDER_REFUND_MISMATCH','Provider refund does not match local refund');if(provider.status==='processed'){await completeRefund(refund,provider.id,null);return{outcome:'processed' as const}}if(provider.status==='failed'){await failRefund(refund,'Razorpay reported refund failure');return{outcome:'failed' as const}}await markRefundProcessing(refund,provider.id,provider.status);return{outcome:'pending' as const}})}

export async function processProviderWebhookEvent(eventId:string){return runWithTenant({isPlatform:true},async()=>{let event:any=await ProviderWebhookEvent.findOneAndUpdate({provider:'RAZORPAY',eventId,status:{$in:['RECEIVED','FAILED']}},{$set:{status:'PROCESSING',failureReason:null,updatedAt:new Date()},$inc:{attempts:1}},{new:true});if(!event){event=await ProviderWebhookEvent.findOne({provider:'RAZORPAY',eventId});if(!event)throw new AppError(404,'NOT_FOUND','Provider webhook event not found');return{outcome:event.status==='PROCESSED'?'processed':'ignored'}}try{let result:any={outcome:'ignored'};if(['payment.captured','order.paid'].includes(event.eventType)&&event.providerPaymentId)result=await reconcileCapturedPayment(event.providerPaymentId);else if(event.eventType==='payment.failed'&&event.providerPaymentId){const provider=await fetchPayment(event.providerPaymentId);if(provider.status==='captured'&&provider.captured)result=await reconcileCapturedPayment(provider.id);else{const local:any=await localPaymentByProvider(provider);if(local){local.providerPaymentId=provider.id;local.providerStatus=provider.status;local.lastProviderSyncAt=new Date();local.failureReason=provider.error_description||'Provider payment failed; reservation retained for possible retry';await local.save()}result={outcome:'processed'}}}else if(['refund.created','refund.processed','refund.failed'].includes(event.eventType)&&event.providerRefundId)result=await reconcileProviderRefund(event.providerRefundId);event.status=result.outcome==='ignored'?'IGNORED':'PROCESSED';event.processedAt=new Date();event.updatedAt=new Date();await event.save();return result}catch(error){event.status='FAILED';event.failureReason=(error instanceof Error?error.message:'Webhook processing failed').slice(0,500);event.updatedAt=new Date();await event.save();throw error}})}

export async function reconcilePendingProviderState(limit=50){return runWithTenant({isPlatform:true},async()=>{const payments:any[]=await FeePayment.find({provider:'RAZORPAY',status:'PENDING',providerOrderId:{$type:'string'},deletedAt:null}).sort({updatedAt:1}).limit(Math.min(100,Math.max(1,limit)));let paymentCaptured=0,paymentChecked=0;for(const local of payments){try{const collection=await fetchOrderPayments(local.providerOrderId);const captured=collection.items.find(item=>item.status==='captured'&&item.captured&&item.amount===toPaise(Number(local.amount)));if(captured){await reconcileCapturedPayment(captured.id);paymentCaptured++}else{const latest=collection.items[0];local.providerStatus=latest?.status||local.providerStatus||'created';local.lastProviderSyncAt=new Date();if(latest?.error_description)local.failureReason=latest.error_description;await local.save()}paymentChecked++}catch{continue}}
 const refunds:any[]=await FeeRefund.find({status:'PROCESSING',providerRefundId:{$type:'string'},deletedAt:null}).sort({updatedAt:1}).limit(Math.min(100,Math.max(1,limit)));let refundChecked=0;for(const refund of refunds){try{await reconcileProviderRefund(refund.providerRefundId);refundChecked++}catch{continue}}return{payments:{checked:paymentChecked,captured:paymentCaptured},refunds:{checked:refundChecked}}})}
