import type { FastifyInstance } from 'fastify';
import { PERMISSIONS } from '@erp/contracts';
import { registerCrud } from '../../core/crud.js';
import { requirePermission } from '../../core/security.js';
import { AppError } from '../../core/errors.js';
import { FeeStructure,FeeInvoice,FeePayment,FeeRefund } from './models.js';
import { writeAudit } from '../../core/audit.js';
import { assertStudentAccessible,relatedStudentReadScope } from '../people/access.js';
import { applyInvoicePayment,assertPaymentRetryMatches,collectManualPayment,completeRefund,normalizeIdempotencyKey,releaseOnlineReservation,requestRefund,reserveOnlineInvoice,stableReceipt } from './service.js';
import { createOrder,createRefund,fetchPayment,razorpayPublicKey,toPaise,verifyCheckoutSignature } from './razorpay.js';

const keyFrom=(request:any)=>normalizeIdempotencyKey(request.headers['x-idempotency-key']||request.body?.idempotencyKey);
export async function feeRoutes(app:FastifyInstance){
 await registerCrud(app,{prefix:'/api/fees/structures',model:FeeStructure,entity:'fee-structure',readPermission:PERMISSIONS.FEE_READ,writePermission:PERMISSIONS.FEE_COLLECT,searchable:['name']});
 await registerCrud(app,{prefix:'/api/fees/invoices',model:FeeInvoice,entity:'fee-invoice',readPermission:PERMISSIONS.FEE_READ,writePermission:PERMISSIONS.FEE_COLLECT,searchable:['invoiceNo'],readScope:request=>relatedStudentReadScope(request)});
 app.get('/api/fees/payments',{preHandler:requirePermission(PERMISSIONS.FEE_READ)},async(request:any)=>{const scope=await relatedStudentReadScope(request);const filter:any={...scope};if(request.query?.invoiceId)filter.invoiceId=request.query.invoiceId;return{success:true,data:await FeePayment.find(filter).sort({createdAt:-1}).limit(200).lean()}});
 app.post('/api/fees/collect',{preHandler:requirePermission(PERMISSIONS.FEE_COLLECT)},async(request:any)=>{const{invoiceId,amount,mode,reference}=request.body??{};const result=await collectManualPayment({invoiceId,amount:Number(amount),mode:String(mode||''),reference,idempotencyKey:keyFrom(request),collectedBy:request.auth.sub});await writeAudit({action:'fee.collect',entity:'fee-payment',entityId:String(result.payment?._id),after:result.payment,ip:request.ip});return{success:true,data:result}});
 app.post('/api/fees/online/order',{preHandler:requirePermission(PERMISSIONS.FEE_PAY)},async(request:any)=>{const{invoiceId,amount}=request.body??{},value=Number(amount),key=keyFrom(request);const invoice:any=await FeeInvoice.findById(invoiceId).lean();if(!invoice)throw new AppError(404,'NOT_FOUND','Invoice not found');await assertStudentAccessible(request,invoice.studentId);const existing:any=await FeePayment.findOne({idempotencyKey:key});if(existing){assertPaymentRetryMatches(existing,{invoiceId,amount:value,mode:'RAZORPAY'});if(existing.providerOrderId)return{success:true,data:{keyId:razorpayPublicKey(),orderId:existing.providerOrderId,amount:toPaise(existing.amount),currency:existing.currency||'INR',paymentId:existing._id}};throw new AppError(409,'PAYMENT_PENDING','A payment attempt with this key already exists')}
  await reserveOnlineInvoice(invoice._id,value,key);let payment:any;try{payment=await FeePayment.create({receiptNo:stableReceipt('RCPT',key),idempotencyKey:key,invoiceId:invoice._id,studentId:invoice.studentId,amount:value,currency:'INR',mode:'RAZORPAY',provider:'RAZORPAY',status:'PENDING'});const order=await createOrder(toPaise(value),stableReceipt('ORD',key),{schoolInvoice:String(invoice.invoiceNo),invoiceId:String(invoice._id),paymentId:String(payment._id)});payment.providerOrderId=order.id;await payment.save();return{success:true,data:{keyId:razorpayPublicKey(),orderId:order.id,amount:order.amount,currency:order.currency,paymentId:payment._id}}}catch(error){await releaseOnlineReservation(invoice._id,value,key);if(payment?._id)await FeePayment.findByIdAndUpdate(payment._id,{$set:{status:'FAILED',failureReason:error instanceof Error?error.message:'Order creation failed',updatedAt:new Date()}});throw error}});
 app.post('/api/fees/online/verify',{preHandler:requirePermission(PERMISSIONS.FEE_PAY)},async(request:any)=>{const{razorpay_order_id:orderId,razorpay_payment_id:providerPaymentId,razorpay_signature:signature}=request.body??{};const payment:any=await FeePayment.findOne({providerOrderId:String(orderId||'')});if(!payment)throw new AppError(404,'NOT_FOUND','Payment intent not found');await assertStudentAccessible(request,payment.studentId);if(payment.status==='SUCCESS')return{success:true,data:{payment,invoice:await FeeInvoice.findById(payment.invoiceId).lean()}};if(!verifyCheckoutSignature(String(orderId),String(providerPaymentId),String(signature||'')))throw new AppError(400,'INVALID_PAYMENT_SIGNATURE','Payment signature verification failed');const provider=await fetchPayment(String(providerPaymentId));if(provider.order_id!==String(orderId)||provider.status!=='captured'||!provider.captured||provider.amount!==toPaise(Number(payment.amount)))throw new AppError(409,'PAYMENT_NOT_CAPTURED','Provider payment is not captured or does not match this order');payment.providerPaymentId=provider.id;await payment.save();const invoice=await applyInvoicePayment(payment);const finalPayment=await FeePayment.findById(payment._id).lean();await writeAudit({action:'fee.online-captured',entity:'fee-payment',entityId:String(payment._id),after:finalPayment,ip:request.ip});return{success:true,data:{payment:finalPayment,invoice}}});
 app.post('/api/fees/refunds',{preHandler:requirePermission(PERMISSIONS.FEE_REFUND)},async(request:any)=>{const refund=await requestRefund({paymentId:request.body?.paymentId,amount:Number(request.body?.amount),reason:request.body?.reason,idempotencyKey:keyFrom(request),requestedBy:request.auth.sub});return{success:true,data:refund}});
 app.post('/api/fees/refunds/:id/process',{preHandler:requirePermission(PERMISSIONS.FEE_REFUND)},async(request:any)=>{const refund:any=await FeeRefund.findById(request.params.id);if(!refund)throw new AppError(404,'NOT_FOUND','Refund not found');if(refund.status==='PROCESSED')return{success:true,data:refund};if(!['REQUESTED','FAILED'].includes(refund.status))throw new AppError(409,'REFUND_STATE','Refund cannot be processed in its current state');const payment:any=await FeePayment.findById(refund.paymentId);if(!payment)throw new AppError(404,'NOT_FOUND','Payment not found');refund.status='PROCESSING';await refund.save();try{let providerRefundId:string|undefined;if(payment.mode==='RAZORPAY'){if(!payment.providerPaymentId)throw new AppError(409,'PROVIDER_PAYMENT_MISSING','Provider payment id is missing');const providerRefund=await createRefund(payment.providerPaymentId,toPaise(Number(refund.amount)),refund.idempotencyKey,stableReceipt('RFND',refund.idempotencyKey));providerRefundId=providerRefund.id}const processed=await completeRefund(refund,providerRefundId,request.auth.sub);await writeAudit({action:'fee.refund-processed',entity:'fee-refund',entityId:String(refund._id),after:processed?.toObject(),ip:request.ip});return{success:true,data:processed}}catch(error){refund.status='FAILED';refund.failureReason=error instanceof Error?error.message:'Refund failed';refund.updatedAt=new Date();await refund.save();throw error}});
}
