import { createHash } from 'node:crypto';
import { AppError } from '../../core/errors.js';
import { FeeInvoice,FeePayment,FeeRefund } from './models.js';

export function normalizeIdempotencyKey(value:any){const key=String(value||'').trim();if(!/^[A-Za-z0-9_-]{10,100}$/.test(key))throw new AppError(400,'IDEMPOTENCY_KEY_REQUIRED','Provide an idempotency key (10-100 letters, numbers, hyphens or underscores)');return key}
const receiptFor=(prefix:string,key:string)=>`${prefix}-${createHash('sha256').update(key).digest('hex').slice(0,24).toUpperCase()}`;
const sameMoney=(a:any,b:any)=>Math.abs(Number(a)-Number(b))<0.000001;
export function assertPaymentRetryMatches(payment:any,input:{invoiceId:any;amount:number;mode:string}){if(String(payment.invoiceId)!==String(input.invoiceId)||!sameMoney(payment.amount,input.amount)||payment.mode!==input.mode)throw new AppError(409,'IDEMPOTENCY_CONFLICT','This idempotency key was already used for different payment details')}

export async function applyInvoicePayment(payment:any){
 const key=String(payment.idempotencyKey),amount=Number(payment.amount);
 const invoice:any=await FeeInvoice.findOneAndUpdate({_id:payment.invoiceId,appliedPaymentKeys:{$ne:key},status:{$ne:'CANCELLED'},$expr:{$gte:[{$ifNull:['$balance','$total']},amount]}},[
  {$set:{paid:{$add:[{$ifNull:['$paid',0]},amount]},balance:{$subtract:[{$ifNull:['$balance','$total']},amount]},reserved:{$max:[0,{$subtract:[{$ifNull:['$reserved',0]},{$cond:[{$in:[key,{$ifNull:['$reservationKeys',[]]}]},amount,0]}]}]},reservationKeys:{$setDifference:[{$ifNull:['$reservationKeys',[]]},[key]]},appliedPaymentKeys:{$setUnion:[{$ifNull:['$appliedPaymentKeys',[]]},[key]]},updatedAt:'$$NOW'}},
  {$set:{status:{$cond:[{$lte:['$balance',0]},'PAID','PARTIAL']}}}
 ] as any,{new:true});
 if(!invoice){const current:any=await FeeInvoice.findById(payment.invoiceId).lean();if(current?.appliedPaymentKeys?.includes(key)){await FeePayment.findByIdAndUpdate(payment._id,{$set:{status:'SUCCESS',paidAt:payment.paidAt||new Date(),updatedAt:new Date()}});return current}await FeePayment.findByIdAndUpdate(payment._id,{$set:{status:'FAILED',failureReason:'Invoice balance is insufficient or invoice is unavailable',updatedAt:new Date()}});throw new AppError(409,'PAYMENT_NOT_APPLIED','Invoice balance is insufficient or invoice is unavailable')}
 await FeePayment.findByIdAndUpdate(payment._id,{$set:{status:'SUCCESS',paidAt:new Date(),failureReason:null,updatedAt:new Date()}});
 return invoice;
}

export async function collectManualPayment(input:{invoiceId:any;amount:number;mode:string;reference?:string;idempotencyKey:string;collectedBy:any}){
 const key=normalizeIdempotencyKey(input.idempotencyKey),amount=Number(input.amount);if(!Number.isFinite(amount)||amount<=0)throw new AppError(400,'INVALID_AMOUNT','Payment amount is invalid');if(!['CASH','UPI','CARD','BANK'].includes(input.mode))throw new AppError(400,'INVALID_MODE','Use the online payment flow for Razorpay payments');
 let payment:any=await FeePayment.findOne({idempotencyKey:key});if(payment){assertPaymentRetryMatches(payment,{invoiceId:input.invoiceId,amount,mode:input.mode});if(payment.status==='FAILED')throw new AppError(409,'PAYMENT_FAILED','This payment attempt is already failed; use a new idempotency key')}else{const invoice:any=await FeeInvoice.findById(input.invoiceId).lean();if(!invoice)throw new AppError(404,'NOT_FOUND','Invoice not found');try{payment=await FeePayment.create({receiptNo:receiptFor('RCPT',key),idempotencyKey:key,invoiceId:invoice._id,studentId:invoice.studentId,amount,currency:invoice.currency||'INR',mode:input.mode,reference:input.reference,status:'PENDING',collectedBy:input.collectedBy})}catch(error:any){if(error?.code!==11000)throw error;payment=await FeePayment.findOne({idempotencyKey:key});if(!payment)throw error;assertPaymentRetryMatches(payment,{invoiceId:input.invoiceId,amount,mode:input.mode})}}
 const invoice=await applyInvoicePayment(payment);return{payment:await FeePayment.findById(payment._id).lean(),invoice};
}

export async function reserveOnlineInvoice(invoiceId:any,amount:number,key:string){const invoice:any=await FeeInvoice.findOneAndUpdate({_id:invoiceId,reservationKeys:{$ne:key},appliedPaymentKeys:{$ne:key},status:{$nin:['CANCELLED','PAID']},$expr:{$gte:[{$subtract:[{$ifNull:['$balance','$total']},{$ifNull:['$reserved',0]}]},amount]}},[{$set:{reserved:{$add:[{$ifNull:['$reserved',0]},amount]},reservationKeys:{$setUnion:[{$ifNull:['$reservationKeys',[]]},[key]]},updatedAt:'$$NOW'}}] as any,{new:true});if(invoice)return invoice;const current:any=await FeeInvoice.findById(invoiceId).lean();if(current?.reservationKeys?.includes(key))return current;throw new AppError(409,'INSUFFICIENT_BALANCE','The invoice does not have enough unreserved balance')}
export async function releaseOnlineReservation(invoiceId:any,amount:number,key:string){await FeeInvoice.findOneAndUpdate({_id:invoiceId,reservationKeys:key},[{$set:{reserved:{$max:[0,{$subtract:[{$ifNull:['$reserved',0]},amount]}]},reservationKeys:{$setDifference:[{$ifNull:['$reservationKeys',[]]},[key]]},updatedAt:'$$NOW'}}] as any)}

export async function requestRefund(input:{paymentId:any;amount:number;reason?:string;idempotencyKey:string;requestedBy:any}){const key=normalizeIdempotencyKey(input.idempotencyKey),amount=Number(input.amount);if(!Number.isFinite(amount)||amount<=0)throw new AppError(400,'INVALID_AMOUNT','Refund amount is invalid');let refund:any=await FeeRefund.findOne({idempotencyKey:key});if(refund){if(String(refund.paymentId)!==String(input.paymentId)||!sameMoney(refund.amount,amount))throw new AppError(409,'IDEMPOTENCY_CONFLICT','This idempotency key was used for a different refund');return refund}const payment:any=await FeePayment.findOneAndUpdate({_id:input.paymentId,status:{$in:['SUCCESS','PARTIALLY_REFUNDED']},refundReservationKeys:{$ne:key},$expr:{$gte:[{$subtract:[{$subtract:['$amount',{$ifNull:['$refundedAmount',0]}]},{$ifNull:['$refundReserved',0]}]},amount]}},{$inc:{refundReserved:amount},$addToSet:{refundReservationKeys:key},$set:{updatedAt:new Date()}},{new:true});if(!payment)throw new AppError(409,'REFUND_EXCEEDS_PAYMENT','Refund exceeds the refundable payment balance');try{return await FeeRefund.create({paymentId:payment._id,idempotencyKey:key,amount,reason:input.reason,status:'REQUESTED',requestedBy:input.requestedBy})}catch(error){await FeePayment.findByIdAndUpdate(payment._id,{$inc:{refundReserved:-amount},$pull:{refundReservationKeys:key}});throw error}}
export async function completeRefund(refund:any,providerRefundId:string|undefined,processedBy:any){const payment:any=await FeePayment.findById(refund.paymentId);if(!payment)throw new AppError(404,'NOT_FOUND','Payment not found');const amount=Number(refund.amount),newRefunded=Number(payment.refundedAmount||0)+amount,newStatus=newRefunded>=Number(payment.amount)?'REFUNDED':'PARTIALLY_REFUNDED';await FeePayment.findByIdAndUpdate(payment._id,{$inc:{refundReserved:-amount,refundedAmount:amount},$pull:{refundReservationKeys:refund.idempotencyKey},$set:{status:newStatus,updatedAt:new Date()}});return FeeRefund.findByIdAndUpdate(refund._id,{$set:{status:'PROCESSED',providerRefundId,processedBy,processedAt:new Date(),updatedAt:new Date()}},{new:true})}
export const stableReceipt=(prefix:string,key:string)=>receiptFor(prefix,key);
