import{BarChart3,Bell,BookOpen,BookUser,BriefcaseBusiness,Building2,CalendarClock,ClipboardCheck,ClipboardList,FileCheck2,FileSpreadsheet,Fingerprint,GraduationCap,LayoutDashboard,LibraryBig,MessagesSquare,NotebookPen,ReceiptIndianRupee,Settings,ShieldCheck,UserCog,UsersRound,WalletCards}from'lucide-react';
import{PERMISSIONS}from'@erp/contracts';
export const nav=[
 ['Dashboard','/',LayoutDashboard,null],
 ['Students','/students',GraduationCap,PERMISSIONS.STUDENT_READ],
 ['Teachers','/teachers',BookUser,PERMISSIONS.TEACHER_READ],
 ['Staff','/staff',BriefcaseBusiness,PERMISSIONS.STAFF_READ],
 ['Parents','/parents',UsersRound,PERMISSIONS.STUDENT_READ],
 ['Admissions','/admissions',Building2,PERMISSIONS.ADMISSION_READ],
 ['Academics','/academics',BookOpen,PERMISSIONS.ACADEMICS_READ],
 ['Timetable','/timetable',CalendarClock,PERMISSIONS.TIMETABLE_READ],
 ['Attendance','/attendance',ClipboardCheck,PERMISSIONS.ATTENDANCE_READ],
 ['Assignments','/assignments',NotebookPen,PERMISSIONS.ASSIGNMENT_READ],
 ['Examinations','/exams',ClipboardList,PERMISSIONS.EXAM_READ],
 ['Report Cards','/report-cards',FileCheck2,PERMISSIONS.REPORT_CARD_READ],
 ['Fees & Accounts','/fees',ReceiptIndianRupee,PERMISSIONS.FEE_READ],
 ['Library','/library',LibraryBig,PERMISSIONS.LIBRARY_READ],
 ['Payroll','/payroll',WalletCards,PERMISSIONS.PAYROLL_READ],
 ['Leaves','/leaves',CalendarClock,PERMISSIONS.LEAVE_READ],
 ['Communication','/communication',MessagesSquare,PERMISSIONS.COMMUNICATION_READ],
 ['Documents','/documents',FileCheck2,PERMISSIONS.DOCUMENT_READ],
 ['Imports','/imports',FileSpreadsheet,PERMISSIONS.IMPORT_RUN],
 ['Notifications','/notifications',Bell,null],
 ['Analytics','/analytics',BarChart3,PERMISSIONS.ANALYTICS_READ],
 ['Users & Roles','/users',UserCog,PERMISSIONS.USER_MANAGE],
 ['Settings','/settings',Settings,PERMISSIONS.SCHOOL_MANAGE],
 ['Audit','/audit',ShieldCheck,PERMISSIONS.AUDIT_READ],
 ['Biometric','/biometric',Fingerprint,PERMISSIONS.BIOMETRIC_READ],
 ['OASES','/oases',FileSpreadsheet,PERMISSIONS.OASES_READ],
 ['Custom Forms','/custom-forms',FileSpreadsheet,PERMISSIONS.CUSTOM_FORM_READ]
] as const;
