export const SCHOOL_ROLES = [
  'SCHOOL_ADMIN','ADMISSION_MANAGER','ACCOUNTS_MANAGER','HR_MANAGER',
  'EXAM_CONTROLLER','TEACHER','LIBRARIAN','STUDENT','PARENT'
] as const;
export type SchoolRole = (typeof SCHOOL_ROLES)[number];

export const MODULES = [
  'dashboard','students','teachers','staff','parents','admissions','academics','timetable',
  'attendance','assignments','examinations','report-cards','fees','library','payroll',
  'leaves','communication','documents','imports','notifications','analytics','settings','audit','biometric','oases','custom-forms'
] as const;

export const PERMISSIONS = {
  SCHOOL_MANAGE:'school.manage', USER_MANAGE:'user.manage',
  STUDENT_READ:'student.read', STUDENT_WRITE:'student.write',
  TEACHER_READ:'teacher.read', TEACHER_WRITE:'teacher.write',
  STAFF_READ:'staff.read', STAFF_WRITE:'staff.write',
  ADMISSION_READ:'admission.read', ADMISSION_WRITE:'admission.write',
  ACADEMICS_READ:'academics.read', ACADEMICS_WRITE:'academics.write',
  TIMETABLE_READ:'timetable.read', TIMETABLE_WRITE:'timetable.write',
  ATTENDANCE_READ:'attendance.read', ATTENDANCE_MARK:'attendance.mark',
  ASSIGNMENT_READ:'assignment.read', ASSIGNMENT_WRITE:'assignment.write', ASSIGNMENT_SUBMIT:'assignment.submit',
  EXAM_READ:'exam.read', EXAM_WRITE:'exam.write', MARKS_WRITE:'marks.write', RESULT_PUBLISH:'result.publish',
  REPORT_CARD_READ:'reportcard.read', REPORT_CARD_WRITE:'reportcard.write',
  FEE_READ:'fee.read', FEE_PAY:'fee.pay', FEE_COLLECT:'fee.collect', FEE_REFUND:'fee.refund',
  LIBRARY_READ:'library.read', LIBRARY_WRITE:'library.write',
  PAYROLL_READ:'payroll.read', PAYROLL_PROCESS:'payroll.process',
  LEAVE_READ:'leave.read', LEAVE_APPROVE:'leave.approve',
  COMMUNICATION_READ:'communication.read', COMMUNICATION_SEND:'communication.send', COMMUNICATION_WRITE:'communication.write',
  DOCUMENT_READ:'document.read', DOCUMENT_WRITE:'document.write',
  IMPORT_RUN:'import.run', NOTIFICATION_SEND:'notification.send',
  ANALYTICS_READ:'analytics.read', AUDIT_READ:'audit.read', BIOMETRIC_READ:'biometric.read', BIOMETRIC_WRITE:'biometric.write', OASES_READ:'oases.read', OASES_EVALUATE:'oases.evaluate', CUSTOM_FORM_READ:'customform.read', CUSTOM_FORM_WRITE:'customform.write'
} as const;
export type Permission=(typeof PERMISSIONS)[keyof typeof PERMISSIONS];
const ALL=Object.values(PERMISSIONS) as Permission[];
export const DEFAULT_ROLE_PERMISSIONS:Record<SchoolRole,Permission[]>={
  SCHOOL_ADMIN:ALL,
  ADMISSION_MANAGER:[PERMISSIONS.STUDENT_READ,PERMISSIONS.STUDENT_WRITE,PERMISSIONS.ADMISSION_READ,PERMISSIONS.ADMISSION_WRITE,PERMISSIONS.ACADEMICS_READ,PERMISSIONS.DOCUMENT_READ,PERMISSIONS.DOCUMENT_WRITE,PERMISSIONS.IMPORT_RUN,PERMISSIONS.COMMUNICATION_READ,PERMISSIONS.COMMUNICATION_SEND,PERMISSIONS.CUSTOM_FORM_READ,PERMISSIONS.CUSTOM_FORM_WRITE],
  ACCOUNTS_MANAGER:[PERMISSIONS.STUDENT_READ,PERMISSIONS.FEE_READ,PERMISSIONS.FEE_COLLECT,PERMISSIONS.FEE_REFUND,PERMISSIONS.ANALYTICS_READ,PERMISSIONS.DOCUMENT_READ],
  HR_MANAGER:[PERMISSIONS.TEACHER_READ,PERMISSIONS.TEACHER_WRITE,PERMISSIONS.STAFF_READ,PERMISSIONS.STAFF_WRITE,PERMISSIONS.PAYROLL_READ,PERMISSIONS.PAYROLL_PROCESS,PERMISSIONS.LEAVE_READ,PERMISSIONS.LEAVE_APPROVE,PERMISSIONS.ATTENDANCE_READ,PERMISSIONS.BIOMETRIC_READ,PERMISSIONS.BIOMETRIC_WRITE],
  EXAM_CONTROLLER:[PERMISSIONS.STUDENT_READ,PERMISSIONS.ACADEMICS_READ,PERMISSIONS.EXAM_READ,PERMISSIONS.EXAM_WRITE,PERMISSIONS.MARKS_WRITE,PERMISSIONS.RESULT_PUBLISH,PERMISSIONS.REPORT_CARD_READ,PERMISSIONS.REPORT_CARD_WRITE,PERMISSIONS.OASES_READ,PERMISSIONS.OASES_EVALUATE],
  TEACHER:[PERMISSIONS.STUDENT_READ,PERMISSIONS.ACADEMICS_READ,PERMISSIONS.TIMETABLE_READ,PERMISSIONS.ATTENDANCE_READ,PERMISSIONS.ATTENDANCE_MARK,PERMISSIONS.ASSIGNMENT_READ,PERMISSIONS.ASSIGNMENT_WRITE,PERMISSIONS.EXAM_READ,PERMISSIONS.MARKS_WRITE,PERMISSIONS.REPORT_CARD_READ,PERMISSIONS.LEAVE_READ,PERMISSIONS.COMMUNICATION_READ,PERMISSIONS.COMMUNICATION_SEND],
  LIBRARIAN:[PERMISSIONS.STUDENT_READ,PERMISSIONS.TEACHER_READ,PERMISSIONS.LIBRARY_READ,PERMISSIONS.LIBRARY_WRITE],
  STUDENT:[PERMISSIONS.STUDENT_READ,PERMISSIONS.ACADEMICS_READ,PERMISSIONS.TIMETABLE_READ,PERMISSIONS.ATTENDANCE_READ,PERMISSIONS.ASSIGNMENT_READ,PERMISSIONS.ASSIGNMENT_SUBMIT,PERMISSIONS.EXAM_READ,PERMISSIONS.REPORT_CARD_READ,PERMISSIONS.FEE_READ,PERMISSIONS.FEE_PAY,PERMISSIONS.LIBRARY_READ,PERMISSIONS.LEAVE_READ,PERMISSIONS.COMMUNICATION_READ,PERMISSIONS.COMMUNICATION_SEND,PERMISSIONS.DOCUMENT_READ],
  PARENT:[PERMISSIONS.STUDENT_READ,PERMISSIONS.TIMETABLE_READ,PERMISSIONS.ATTENDANCE_READ,PERMISSIONS.ASSIGNMENT_READ,PERMISSIONS.EXAM_READ,PERMISSIONS.REPORT_CARD_READ,PERMISSIONS.FEE_READ,PERMISSIONS.FEE_PAY,PERMISSIONS.COMMUNICATION_READ,PERMISSIONS.COMMUNICATION_SEND,PERMISSIONS.DOCUMENT_READ]
};
