import type { FastifyInstance } from 'fastify';
import { timingSafeEqual } from 'node:crypto';
import { Types } from 'mongoose';
import { env } from '../../config/env.js';
import { AppError,forbidden } from '../../core/errors.js';
import { enqueueFileScan } from '../../core/queue.js';
import { getTenantContext,runWithTenant } from '../../core/tenant-context.js';
import { FileAsset } from './models.js';
import { cleanFileName,getFilePolicy,requirePurposePermission,validateFileRequest } from './policy.js';
import { buildObjectKey,createDownloadUrl,createUploadForm,deleteObject,headObject,storageBucket } from './storage.js';

function isOwner(request:any,asset:any){return String(asset.createdBy)===String(request.auth?.sub)}
function assertAssetAccess(request:any,asset:any,mode:'read'|'write'){if(isOwner(request,asset))return;requirePurposePermission(request,asset.purpose,mode)}
function safeSecret(input:string|undefined){const a=Buffer.from(String(input||'')),b=Buffer.from(env.WORKER_CALLBACK_SECRET);return a.length===b.length&&a.length>0&&timingSafeEqual(a,b)}

export async function fileRoutes(app:FastifyInstance){
 app.post('/api/files/upload-intents',async(request:any)=>{const{purpose,fileName,contentType,size}=request.body??{};requirePurposePermission(request,String(purpose||''),'write');const checked=validateFileRequest(String(purpose),String(fileName||''),String(contentType||''),Number(size));const ctx=getTenantContext();if(!ctx?.schoolId)throw new AppError(403,'TENANT_REQUIRED','School context required');const asset=new FileAsset({purpose,originalName:checked.name,objectKey:'pending',contentType:checked.mime,declaredSize:checked.bytes,createdBy:request.auth.sub,status:'INITIATED',scanStatus:'PENDING'});asset.objectKey=buildObjectKey({schoolId:ctx.schoolId,purpose:String(purpose),assetId:String(asset._id),fileName:checked.name});await asset.save();try{const upload=await createUploadForm({key:asset.objectKey,contentType:checked.mime,maxBytes:checked.policy.maxBytes,assetId:String(asset._id),schoolId:ctx.schoolId,purpose:String(purpose)});return{success:true,data:{asset:{id:asset._id,name:asset.originalName,contentType:asset.contentType,size:asset.declaredSize,status:asset.status},upload:{method:'POST',url:upload.url,fields:upload.fields,expiresIn:300}}}}catch(error){asset.status='REJECTED';asset.scanStatus='ERROR';asset.scanDetail=error instanceof Error?error.message:'Unable to create upload intent';await asset.save();throw error}});
 app.post('/api/files/:id/confirm',async(request:any)=>{const asset:any=await FileAsset.findById(request.params.id);if(!asset)throw new AppError(404,'NOT_FOUND','File asset not found');assertAssetAccess(request,asset,'write');if(asset.status==='READY')return{success:true,data:asset};if(!['INITIATED','UPLOADED'].includes(asset.status))throw new AppError(409,'FILE_STATE','File cannot be confirmed in its current state');const policy=getFilePolicy(asset.purpose);let head;try{head=await headObject(asset.objectKey)}catch{throw new AppError(409,'UPLOAD_NOT_FOUND','Uploaded object is not available yet')};const actual=Number(head.ContentLength||0),metadata=head.Metadata||{},contentType=String(head.ContentType||'').toLowerCase();const validMetadata=metadata['asset-id']===String(asset._id)&&metadata['school-id']===String(getTenantContext()?.schoolId)&&metadata['purpose']===asset.purpose;const valid=actual===Number(asset.declaredSize)&&actual>0&&actual<=policy.maxBytes&&contentType===asset.contentType&&validMetadata;if(!valid){await deleteObject(asset.objectKey).catch(()=>undefined);asset.status='REJECTED';asset.scanStatus='ERROR';asset.scanDetail='Uploaded object metadata, size or content type did not match the signed intent';asset.actualSize=actual;await asset.save();throw new AppError(422,'UPLOAD_MISMATCH','Uploaded file did not match the approved upload intent')};asset.actualSize=actual;asset.etag=head.ETag;asset.confirmedAt=new Date();asset.updatedAt=new Date();if(env.FILE_SCAN_MODE==='disabled'){asset.status='READY';asset.scanStatus='SKIPPED';asset.scanCompletedAt=new Date();await asset.save();return{success:true,data:asset}}asset.status='UPLOADED';asset.scanStatus='PENDING';await asset.save();try{await enqueueFileScan({assetId:String(asset._id),schoolId:String(getTenantContext()?.schoolId),bucket:storageBucket(),key:asset.objectKey,contentType:asset.contentType,size:actual})}catch(error){asset.scanStatus='ERROR';asset.scanDetail='Malware scan could not be queued';await asset.save();throw new AppError(503,'SCAN_QUEUE_UNAVAILABLE','Upload was received but malware scanning could not be queued')};return{success:true,data:asset}});
 app.get('/api/files/:id',async(request:any)=>{const asset:any=await FileAsset.findById(request.params.id).lean();if(!asset)throw new AppError(404,'NOT_FOUND','File asset not found');assertAssetAccess(request,asset,'read');return{success:true,data:{id:asset._id,purpose:asset.purpose,name:asset.originalName,contentType:asset.contentType,size:asset.actualSize??asset.declaredSize,status:asset.status,scanStatus:asset.scanStatus,createdAt:asset.createdAt}}});
 app.get('/api/files/:id/download',async(request:any)=>{const asset:any=await FileAsset.findById(request.params.id).lean();if(!asset)throw new AppError(404,'NOT_FOUND','File asset not found');assertAssetAccess(request,asset,'read');if(asset.status!=='READY'||!['CLEAN','SKIPPED'].includes(asset.scanStatus))throw new AppError(423,'FILE_NOT_READY','File is not cleared for download');return{success:true,data:{url:await createDownloadUrl(asset.objectKey,cleanFileName(asset.originalName)),expiresIn:300}}});
 app.delete('/api/files/:id',async(request:any)=>{const asset:any=await FileAsset.findById(request.params.id);if(!asset)throw new AppError(404,'NOT_FOUND','File asset not found');assertAssetAccess(request,asset,'write');await deleteObject(asset.objectKey).catch(()=>undefined);asset.status='DELETED';asset.deletedAt=new Date();asset.updatedAt=new Date();await asset.save();return{success:true,data:{id:asset._id,deleted:true}}});
}

export async function internalFileRoutes(app:FastifyInstance){
 app.post('/api/internal/files/scan-result',async(request:any)=>{if(!safeSecret(request.headers['x-worker-secret'] as string|undefined))throw forbidden('Invalid worker credentials');const{assetId,schoolId,key,status,detail}=request.body??{};if(!Types.ObjectId.isValid(String(assetId||''))||!Types.ObjectId.isValid(String(schoolId||'')))throw new AppError(400,'INVALID_SCAN_RESULT','Invalid asset or school id');if(!['CLEAN','INFECTED','ERROR'].includes(status))throw new AppError(400,'INVALID_SCAN_RESULT','Invalid scan status');return runWithTenant({isPlatform:true,requestId:request.id},async()=>{const asset:any=await FileAsset.findOne({_id:assetId,schoolId});if(!asset||asset.objectKey!==key)throw new AppError(404,'NOT_FOUND','File asset not found');if(status==='CLEAN'){asset.status='READY';asset.scanStatus='CLEAN'}else if(status==='INFECTED'){asset.status='REJECTED';asset.scanStatus='INFECTED';await deleteObject(asset.objectKey).catch(()=>undefined)}else{asset.status='UPLOADED';asset.scanStatus='ERROR'}asset.scanDetail=String(detail||'').slice(0,500);asset.scanCompletedAt=new Date();asset.updatedAt=new Date();await asset.save();return{success:true,data:{id:asset._id,status:asset.status,scanStatus:asset.scanStatus}}})});
}
