import type { FastifyInstance } from 'fastify';
import { randomBytes } from 'node:crypto';
import { Types } from 'mongoose';
import { PERMISSIONS } from '@erp/contracts';
import { registerCrud } from '../../core/crud.js';
import { requirePermission } from '../../core/security.js';
import { Admission } from './models.js';
import { writeAudit } from '../../core/audit.js';
import { Guardian,Student } from '../people/models.js';
import { AcademicClass,Section } from '../academics/models.js';
import { AppError } from '../../core/errors.js';

const transitions:Record<string,string[]>={ENQUIRY:['APPLIED','REJECTED'],APPLIED:['DOCUMENT_VERIFICATION','UNDER_REVIEW','REJECTED'],DOCUMENT_VERIFICATION:['UNDER_REVIEW','REJECTED'],UNDER_REVIEW:['DOCUMENT_VERIFICATION','ACCEPTED','REJECTED'],ACCEPTED:['UNDER_REVIEW'],REJECTED:['UNDER_REVIEW'],ADMITTED:[]};
const validId=(value:any)=>Types.ObjectId.isValid(String(value||''));
const applicationNo=()=>`APP-${new Date().getUTCFullYear()}-${randomBytes(4).toString('hex').toUpperCase()}`;
const text=(value:any,max=180)=>{const clean=String(value??'').trim();return clean?clean.slice(0,max):undefined};

async function assertClass(classId:any){if(!validId(classId))throw new AppError(400,'INVALID_CLASS','A valid applying class is required');const klass=await AcademicClass.findById(classId).select('_id').lean();if(!klass)throw new AppError(404,'CLASS_NOT_FOUND','Class not found');return klass}
async function prepareCreate(request:any){const body=request.body??{};await assertClass(body.applyingForClassId);const applicant=body.applicant??{};if(!text(applicant.firstName,100))throw new AppError(400,'INVALID_APPLICANT','Applicant first name is required');const initialStatus=['ENQUIRY','APPLIED'].includes(body.status)?body.status:'APPLIED';return{applicationNo:applicationNo(),applicant:{firstName:text(applicant.firstName,100),lastName:text(applicant.lastName,100)||'',dob:applicant.dob||undefined,gender:applicant.gender||undefined,email:text(applicant.email)?.toLowerCase(),phone:text(applicant.phone,40)},guardian:body.guardian?{firstName:text(body.guardian.firstName,100),lastName:text(body.guardian.lastName,100)||'',relation:text(body.guardian.relation,50),phone:text(body.guardian.phone,40),email:text(body.guardian.email)?.toLowerCase(),occupation:text(body.guardian.occupation,120)}:undefined,applyingForClassId:body.applyingForClassId,source:text(body.source,60)||'DIRECT',status:initialStatus,documents:Array.isArray(body.documents)?body.documents.slice(0,25).map((doc:any)=>({name:text(doc.name,120),url:text(doc.url,1000),status:'PENDING'})):[],notes:[]}}
async function prepareUpdate(request:any){const body={...(request.body??{})};for(const field of['applicationNo','status','schoolId','deletedAt','convertedStudentId','acceptedAt','rejectedAt','admittedAt','createdAt'] as const)delete body[field];if(body.applyingForClassId!==undefined)await assertClass(body.applyingForClassId);if(body.applicant){const applicant=body.applicant;body.applicant={firstName:text(applicant.firstName,100),lastName:text(applicant.lastName,100)||'',dob:applicant.dob||undefined,gender:applicant.gender||undefined,email:text(applicant.email)?.toLowerCase(),phone:text(applicant.phone,40)}}if(body.guardian){const guardian=body.guardian;body.guardian={firstName:text(guardian.firstName,100),lastName:text(guardian.lastName,100)||'',relation:text(guardian.relation,50),phone:text(guardian.phone,40),email:text(guardian.email)?.toLowerCase(),occupation:text(guardian.occupation,120)}}body.updatedAt=new Date();return body}

export async function admissionsRoutes(app:FastifyInstance){
 await registerCrud(app,{prefix:'/api/admissions',model:Admission,entity:'admission',readPermission:PERMISSIONS.ADMISSION_READ,writePermission:PERMISSIONS.ADMISSION_WRITE,searchable:['applicationNo','applicant.firstName','applicant.lastName','applicant.phone','applicant.email'],prepareCreate,prepareUpdate});
 app.post('/api/admissions/:id/status',{preHandler:requirePermission(PERMISSIONS.ADMISSION_WRITE)},async(request:any)=>{
  const next=String(request.body?.status||'');const admission:any=await Admission.findById(request.params.id);if(!admission)throw new AppError(404,'NOT_FOUND','Admission not found');if(admission.status===next)return{success:true,data:admission};if(!(transitions[admission.status]||[]).includes(next))throw new AppError(409,'INVALID_STATUS_TRANSITION',`Cannot move admission from ${admission.status} to ${next}`);
  const before={status:admission.status};admission.status=next;admission.updatedAt=new Date();if(next==='ACCEPTED')admission.acceptedAt=new Date();if(next==='REJECTED')admission.rejectedAt=new Date();await admission.save();await writeAudit({action:'admission.status',entity:'admission',entityId:String(admission._id),before,after:{status:next},ip:request.ip});return{success:true,data:admission};
 });
 app.post('/api/admissions/:id/notes',{preHandler:requirePermission(PERMISSIONS.ADMISSION_WRITE)},async(request:any)=>{const note=text(request.body?.text,1000);if(!note)throw new AppError(400,'INVALID_NOTE','Note text is required');const admission=await Admission.findByIdAndUpdate(request.params.id,{$push:{notes:{text:note,by:request.auth.sub,at:new Date()}},$set:{updatedAt:new Date()}},{new:true});if(!admission)throw new AppError(404,'NOT_FOUND','Admission not found');await writeAudit({action:'admission.note',entity:'admission',entityId:request.params.id,after:{noteAdded:true},ip:request.ip});return{success:true,data:admission}});
 app.post('/api/admissions/:id/admit',{preHandler:requirePermission(PERMISSIONS.ADMISSION_WRITE)},async(request:any)=>{
  const admission:any=await Admission.findById(request.params.id);if(!admission)throw new AppError(404,'NOT_FOUND','Admission not found');if(admission.status==='ADMITTED'&&admission.convertedStudentId){const student=await Student.findById(admission.convertedStudentId);if(student)return{success:true,data:{admission,student,idempotent:true}}}if(admission.status!=='ACCEPTED')throw new AppError(409,'ADMISSION_NOT_ACCEPTED','Accept the application before converting it to a student');
  const admissionNumber=text(request.body?.admissionNo,80);if(!admissionNumber)throw new AppError(400,'ADMISSION_NO_REQUIRED','Student admission number is required');const classId=request.body?.classId||admission.applyingForClassId;await assertClass(classId);let sectionId=request.body?.sectionId||undefined;if(sectionId){if(!validId(sectionId))throw new AppError(400,'INVALID_SECTION','Invalid section');const section:any=await Section.findOne({_id:sectionId,classId}).select('_id').lean();if(!section)throw new AppError(404,'SECTION_NOT_FOUND','Section does not belong to the selected class')}
  const a:any=admission.applicant||{};const student:any=await Student.findOneAndUpdate({sourceAdmissionId:admission._id},{$setOnInsert:{firstName:a.firstName,lastName:a.lastName||'',email:a.email,phone:a.phone,dateOfBirth:a.dob,gender:a.gender,admissionNo:admissionNumber,rollNo:text(request.body?.rollNo,80),classId,sectionId,admissionDate:new Date(),lifecycle:'ACTIVE',status:'ACTIVE',sourceAdmissionId:admission._id,createdAt:new Date(),updatedAt:new Date()}},{new:true,upsert:true,runValidators:true,setDefaultsOnInsert:true});
  const g:any=admission.guardian||{};let guardian:any=null;if(text(g.firstName,100)&&text(g.relation,50)){guardian=await Guardian.findOneAndUpdate({sourceAdmissionId:admission._id},{$setOnInsert:{firstName:text(g.firstName,100),lastName:text(g.lastName,100)||'',relation:text(g.relation,50),phone:text(g.phone,40),email:text(g.email)?.toLowerCase(),occupation:text(g.occupation,120),sourceAdmissionId:admission._id,createdAt:new Date(),updatedAt:new Date()},$addToSet:{studentIds:student._id}},{new:true,upsert:true,runValidators:true,setDefaultsOnInsert:true});if(guardian&&!student.guardianIds?.some((id:any)=>String(id)===String(guardian._id))){student.guardianIds=[...(student.guardianIds||[]),guardian._id];await student.save()}}
  admission.status='ADMITTED';admission.convertedStudentId=student._id;admission.admittedAt=new Date();admission.updatedAt=new Date();await admission.save();await writeAudit({action:'admission.convert',entity:'admission',entityId:String(admission._id),after:{studentId:String(student._id),guardianId:guardian?String(guardian._id):undefined},ip:request.ip});return{success:true,data:{admission,student,guardian}};
 });
}
