import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Building2,ChartNoAxesCombined,Layers3,ShieldCheck,LogOut,Plus,Search,X,Save,Power}from'lucide-react';
import{MODULES}from'@erp/contracts';
import'./styles.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:4000/api';
let token=sessionStorage.getItem('platform_token')||'';
async function call(path:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});const b=await r.json();if(!r.ok)throw new Error(b?.error?.message||'Request failed');return b}

function App(){
 const[authed,setAuthed]=useState(!!token),[view,setView]=useState('Overview'),[schools,setSchools]=useState<any[]>([]),[metrics,setMetrics]=useState<any>(null),[error,setError]=useState(''),[creating,setCreating]=useState(false),[selected,setSelected]=useState<any>(null);
 const load=async()=>{setError('');try{const[s,m]=await Promise.all([call('/platform/schools'),call('/platform/metrics')]);setSchools(s.data);setMetrics(m.data)}catch(e:any){setError(e.message)}};
 useEffect(()=>{if(authed)void load()},[authed]);
 if(!authed)return<Login onDone={()=>setAuthed(true)}/>;
 const links=[['Overview',ChartNoAxesCombined],['Schools',Building2],['Modules & plans',Layers3],['Security & audit',ShieldCheck]];
 return<div className="sa-shell"><aside><div className="sa-brand"><span>A</span><div><b>ERP BY ANMOL</b><small>Platform Control</small></div></div><nav>{links.map(([label,Icon]:any)=><button key={label} className={view===label?'active':''} onClick={()=>setView(label)}><Icon size={17}/>{label}</button>)}</nav><button className="logout" onClick={()=>{sessionStorage.clear();location.reload()}}><LogOut size={16}/>Sign out</button></aside><main><header><div><small>PLATFORM ADMINISTRATION</small><h1>{view}</h1></div><button className="new" onClick={()=>setCreating(true)}><Plus size={16}/>Add school</button></header>{error&&<div className="error">{error}</div>}{view==='Overview'?<><div className="metrics"><Metric label="Total schools" value={metrics?.schools?.total??schools.length}/><Metric label="Active" value={metrics?.schools?.active??'—'}/><Metric label="Trial" value={metrics?.schools?.trial??'—'}/><Metric label="Suspended" value={metrics?.schools?.suspended??'—'}/></div><Schools schools={schools} onManage={setSelected}/></>:view==='Schools'?<Schools schools={schools} onManage={setSelected}/>:view==='Modules & plans'?<section className="surface"><div className="surface-head"><div><small>ENTITLEMENTS</small><h2>School module controls</h2></div></div><p className="muted-copy">Open any school from the directory to manage plan, status and module access. Backend entitlement checks enforce the selection on every protected module request.</p></section>:<section className="surface"><h2>Security & audit</h2><p className="muted-copy">Platform authentication is isolated from tenant sessions. Enable MFA/WebAuthn and centralized security monitoring before public production launch.</p></section>}</main>{creating&&<CreateSchool onClose={()=>setCreating(false)} onCreated={async()=>{setCreating(false);await load()}}/>}{selected&&<SchoolManager school={selected} onClose={()=>setSelected(null)} onSaved={async()=>{setSelected(null);await load()}}/>}</div>
}
function Metric({label,value}:any){return<div className="metric"><span>{label}</span><b>{value}</b><small>Platform wide</small></div>}
function Schools({schools,onManage}:{schools:any[];onManage:(s:any)=>void}){const[q,setQ]=useState('');const visible=useMemo(()=>schools.filter(s=>`${s.name} ${s.code}`.toLowerCase().includes(q.toLowerCase())),[schools,q]);return<section className="surface"><div className="surface-head"><div><small>TENANT DIRECTORY</small><h2>Schools</h2></div><label><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search schools"/></label></div><div className="school-list">{visible.length?visible.map((s:any)=><div className="school-row" key={s._id}><div className="school-logo">{s.name?.[0]}</div><div><b>{s.name}</b><small>{s.code} · {s.plan} · {(s.enabledModules||[]).length} modules</small></div><span className={`status ${s.status?.toLowerCase()}`}>{s.status}</span><button onClick={()=>onManage(s)}>Manage</button></div>):<div className="empty">No matching schools.</div>}</div></section>}
function CreateSchool({onClose,onCreated}:{onClose:()=>void;onCreated:()=>void}){const[form,setForm]=useState({name:'',code:'',email:'',phone:'',plan:'STARTER',adminEmail:'',adminPassword:'',adminFirstName:'School',adminLastName:'Admin'}),[busy,setBusy]=useState(false),[error,setError]=useState('');const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));const submit=async(e:any)=>{e.preventDefault();setBusy(true);setError('');try{await call('/platform/schools',{method:'POST',body:JSON.stringify({name:form.name,code:form.code,email:form.email,phone:form.phone,plan:form.plan,admin:{email:form.adminEmail,password:form.adminPassword,firstName:form.adminFirstName,lastName:form.adminLastName}})});onCreated()}catch(e:any){setError(e.message)}finally{setBusy(false)}};return<div className="modal-backdrop"><form className="modal-card" onSubmit={submit}><div className="modal-head"><div><small>NEW TENANT</small><h2>Onboard school</h2></div><button type="button" className="plain" onClick={onClose}><X/></button></div><div className="form-grid"><Field label="School name" value={form.name} onChange={v=>set('name',v)}/><Field label="School code" value={form.code} onChange={v=>set('code',v.toUpperCase())}/><Field label="School email" value={form.email} onChange={v=>set('email',v)}/><Field label="Phone" value={form.phone} onChange={v=>set('phone',v)}/><label>Plan<select value={form.plan} onChange={e=>set('plan',e.target.value)}><option>STARTER</option><option>GROWTH</option><option>PRO</option></select></label><span/><Field label="First admin email" value={form.adminEmail} onChange={v=>set('adminEmail',v)}/><Field label="Temporary password" type="password" value={form.adminPassword} onChange={v=>set('adminPassword',v)}/><Field label="Admin first name" value={form.adminFirstName} onChange={v=>set('adminFirstName',v)}/><Field label="Admin last name" value={form.adminLastName} onChange={v=>set('adminLastName',v)}/></div>{error&&<div className="error">{error}</div>}<div className="modal-actions"><button type="button" className="cancel" onClick={onClose}>Cancel</button><button className="new" disabled={busy}><Plus size={15}/>{busy?'Creating…':'Create school'}</button></div></form></div>}
function SchoolManager({school,onClose,onSaved}:{school:any;onClose:()=>void;onSaved:()=>void}){const[status,setStatus]=useState(school.status),[plan,setPlan]=useState(school.plan),[enabled,setEnabled]=useState<string[]>(school.enabledModules||[]),[busy,setBusy]=useState(false),[error,setError]=useState('');const toggle=(m:string)=>setEnabled(x=>x.includes(m)?x.filter(v=>v!==m):[...x,m]);const save=async()=>{setBusy(true);setError('');try{await call(`/platform/schools/${school._id}`,{method:'PATCH',body:JSON.stringify({status,plan,enabledModules:enabled})});onSaved()}catch(e:any){setError(e.message)}finally{setBusy(false)}};return<div className="modal-backdrop"><section className="modal-card wide"><div className="modal-head"><div><small>TENANT CONTROL</small><h2>{school.name}</h2><p>{school.code}</p></div><button className="plain" onClick={onClose}><X/></button></div><div className="tenant-controls"><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option>ACTIVE</option><option>TRIAL</option><option>SUSPENDED</option></select></label><label>Plan<select value={plan} onChange={e=>setPlan(e.target.value)}><option>STARTER</option><option>GROWTH</option><option>PRO</option></select></label></div><div className="module-grid">{MODULES.filter(m=>m!=='dashboard').map(m=><label className="module-toggle" key={m}><input type="checkbox" checked={enabled.includes(m)} onChange={()=>toggle(m)}/><span><b>{m.replaceAll('-',' ')}</b><small>{enabled.includes(m)?'Enabled':'Disabled'}</small></span></label>)}</div>{error&&<div className="error">{error}</div>}<div className="modal-actions"><button className="cancel" onClick={()=>setStatus(status==='SUSPENDED'?'ACTIVE':'SUSPENDED')}><Power size={14}/>{status==='SUSPENDED'?'Reactivate':'Suspend'}</button><button className="new" onClick={save} disabled={busy}><Save size={15}/>{busy?'Saving…':'Save controls'}</button></div></section></div>}
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return<label>{label}<input required={label.includes('name')||label.includes('code')||label.includes('admin')||label.includes('password')} type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Login({onDone}:{onDone:()=>void}){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');const submit=async(e:any)=>{e.preventDefault();try{const r=await call('/platform/auth/login',{method:'POST',body:JSON.stringify({email,password})});token=r.data.accessToken;sessionStorage.setItem('platform_token',token);onDone()}catch(e:any){setError(e.message)}};return<div className="sa-login"><form onSubmit={submit}><div className="sa-lock">A</div><small>ERP BY ANMOL · PLATFORM</small><h1>Platform administration</h1><p>Separate privileged access for managing schools, plans and platform controls.</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button>Sign in securely</button></form></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
