import type { FastifyInstance } from 'fastify';
import { timingSafeEqual } from 'node:crypto';
import { Types } from 'mongoose';
import { PERMISSIONS } from '@erp/contracts';
import { AppError,forbidden } from '../../core/errors.js';
import { enqueueImport } from '../../core/queue.js';
import { requirePermission } from '../../core/security.js';
import { getTenantContext,runWithTenant } from '../../core/tenant-context.js';
import { env } from '../../config/env.js';
import { AcademicClass,Section } from '../academics/models.js';
import { FileAsset } from '../files/models.js';
import { storageBucket } from '../files/storage.js';
import { Student,Teacher } from '../people/models.js';
import { ImportJob } from './models.js';

type ImportType='students'|'teachers';
type RowEnvelope={row:number;data:Record<string,unknown>};
const allowed=new Set<ImportType>(['students','teachers']);
const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const genders=new Set(['MALE','FEMALE','OTHER']);
const studentLifecycle=new Set(['ACTIVE','SUSPENDED','DROPPED','PASSED','ALUMNI']);
function validId(value:any){return Types.ObjectId.isValid(String(value||''))}
function workerSecret(input:string|undefined){const a=Buffer.from(String(input||'')),b=Buffer.from(env.WORKER_CALLBACK_SECRET);return a.length===b.length&&a.length>0&&timingSafeEqual(a,b)}
function cleanString(value:any,max=200){const text=String(value??'').trim();return text?text.slice(0,max):undefined}
function parseDate(value:any){if(value===undefined||value===null||String(value).trim()==='')return undefined;const date=new Date(value);return Number.isNaN(date.getTime())?null:date}
function rowError(row:number,field:string,message:string){return{row,field,message}}

async function prepareStudents(rows:RowEnvelope[]){
 const errors:Array<{row:number;field:string;message:string}>=[],prepared:any[]=[];
 const admissionNos=rows.map(item=>cleanString(item.data.admissionNo,80)).filter(Boolean) as string[];
 const existing=new Set((await Student.find({admissionNo:{$in:admissionNos}}).select('admissionNo').lean()).map((item:any)=>String(item.admissionNo).toLowerCase()));
 const seen=new Set<string>();
 const classNames=[...new Set(rows.map(item=>cleanString(item.data.className,80)).filter(Boolean) as string[])];
 const classes=classNames.length?await AcademicClass.find({name:{$in:classNames}}).select('_id name').lean():[];const classMap=new Map(classes.map((item:any)=>[String(item.name).toLowerCase(),item._id]));
 const sectionNames=[...new Set(rows.map(item=>cleanString(item.data.sectionName,80)).filter(Boolean) as string[])];
 const sections=sectionNames.length?await Section.find({name:{$in:sectionNames}}).select('_id name classId').lean():[];
 for(const item of rows){const data=item.data,row=item.row;const firstName=cleanString(data.firstName,100),admissionNo=cleanString(data.admissionNo,80);if(!firstName){errors.push(rowError(row,'firstName','Required'));continue}if(!admissionNo){errors.push(rowError(row,'admissionNo','Required'));continue}const key=admissionNo.toLowerCase();if(seen.has(key)||existing.has(key)){errors.push(rowError(row,'admissionNo','Duplicate admission number'));continue}seen.add(key);const email=cleanString(data.email,180)?.toLowerCase();if(email&&!emailPattern.test(email)){errors.push(rowError(row,'email','Invalid email'));continue}const gender=cleanString(data.gender,20)?.toUpperCase();if(gender&&!genders.has(gender)){errors.push(rowError(row,'gender','Use MALE, FEMALE or OTHER'));continue}const dob=parseDate(data.dateOfBirth),admissionDate=parseDate(data.admissionDate);if(dob===null){errors.push(rowError(row,'dateOfBirth','Invalid date'));continue}if(admissionDate===null){errors.push(rowError(row,'admissionDate','Invalid date'));continue}const className=cleanString(data.className,80),sectionName=cleanString(data.sectionName,80);let classId:any=undefined,sectionId:any=undefined;if(className){classId=classMap.get(className.toLowerCase());if(!classId){errors.push(rowError(row,'className','Class not found'));continue}}if(sectionName){const match=sections.find((section:any)=>String(section.name).toLowerCase()===sectionName.toLowerCase()&&(!classId||String(section.classId)===String(classId)));if(!match){errors.push(rowError(row,'sectionName','Section not found for the selected class'));continue}sectionId=match._id;if(!classId)classId=match.classId}const lifecycle=cleanString(data.lifecycle,30)?.toUpperCase();if(lifecycle&&!studentLifecycle.has(lifecycle)){errors.push(rowError(row,'lifecycle','Invalid lifecycle value'));continue}prepared.push({firstName,lastName:cleanString(data.lastName,100)||'',email,phone:cleanString(data.phone,40),dateOfBirth:dob||undefined,gender,admissionNo,rollNo:cleanString(data.rollNo,80),classId,sectionId,admissionDate:admissionDate||undefined,status:cleanString(data.status,30)||'ACTIVE',lifecycle:lifecycle||'ACTIVE'})}
 return{prepared,errors};
}

async function prepareTeachers(rows:RowEnvelope[]){
 const errors:Array<{row:number;field:string;message:string}>=[],prepared:any[]=[];
 const employeeNos=rows.map(item=>cleanString(item.data.employeeNo,80)).filter(Boolean) as string[];
 const existing=new Set((await Teacher.find({employeeNo:{$in:employeeNos}}).select('employeeNo').lean()).map((item:any)=>String(item.employeeNo).toLowerCase()));const seen=new Set<string>();
 for(const item of rows){const data=item.data,row=item.row;const firstName=cleanString(data.firstName,100),employeeNo=cleanString(data.employeeNo,80);if(!firstName){errors.push(rowError(row,'firstName','Required'));continue}if(!employeeNo){errors.push(rowError(row,'employeeNo','Required'));continue}const key=employeeNo.toLowerCase();if(seen.has(key)||existing.has(key)){errors.push(rowError(row,'employeeNo','Duplicate employee number'));continue}seen.add(key);const email=cleanString(data.email,180)?.toLowerCase();if(email&&!emailPattern.test(email)){errors.push(rowError(row,'email','Invalid email'));continue}const gender=cleanString(data.gender,20)?.toUpperCase();if(gender&&!genders.has(gender)){errors.push(rowError(row,'gender','Use MALE, FEMALE or OTHER'));continue}const dob=parseDate(data.dateOfBirth),joiningDate=parseDate(data.joiningDate);if(dob===null){errors.push(rowError(row,'dateOfBirth','Invalid date'));continue}if(joiningDate===null){errors.push(rowError(row,'joiningDate','Invalid date'));continue}prepared.push({firstName,lastName:cleanString(data.lastName,100)||'',email,phone:cleanString(data.phone,40),dateOfBirth:dob||undefined,gender,employeeNo,department:cleanString(data.department,120),qualification:cleanString(data.qualification,180),joiningDate:joiningDate||undefined,status:cleanString(data.status,30)||'ACTIVE'})}
 return{prepared,errors};
}

export async function importRoutes(app:FastifyInstance){
 app.get('/api/imports/jobs',{preHandler:requirePermission(PERMISSIONS.IMPORT_RUN)},async(request:any)=>{const limit=Math.min(Math.max(Number(request.query?.limit)||50,1),100);return{success:true,data:await ImportJob.find().sort({createdAt:-1}).limit(limit).lean()}});
 app.get('/api/imports/jobs/:id',{preHandler:requirePermission(PERMISSIONS.IMPORT_RUN)},async(request:any)=>{if(!validId(request.params.id))throw new AppError(404,'NOT_FOUND','Import job not found');const job=await ImportJob.findById(request.params.id).lean();if(!job)throw new AppError(404,'NOT_FOUND','Import job not found');return{success:true,data:job}});
 app.post('/api/imports/jobs',{preHandler:requirePermission(PERMISSIONS.IMPORT_RUN)},async(request:any)=>{const{type,sourceAssetId}=request.body??{};if(!allowed.has(type as ImportType)||!validId(sourceAssetId))throw new AppError(400,'INVALID_INPUT','type and a valid sourceAssetId are required');const asset:any=await FileAsset.findById(sourceAssetId).lean();if(!asset||asset.purpose!=='import-source')throw new AppError(404,'NOT_FOUND','Import source file not found');if(asset.status!=='READY'||!['CLEAN','SKIPPED'].includes(asset.scanStatus))throw new AppError(423,'FILE_NOT_READY','Import source must pass file verification first');const schoolId=getTenantContext()?.schoolId;if(!schoolId)throw new AppError(403,'TENANT_REQUIRED','School context required');const job:any=await ImportJob.create({type,sourceAssetId:asset._id,sourceName:asset.originalName,status:'QUEUED',createdBy:request.auth.sub});try{await enqueueImport({jobId:String(job._id),schoolId,bucket:storageBucket(),key:asset.objectKey,contentType:asset.contentType,type,sourceName:asset.originalName})}catch(error){job.status='FAILED';job.failureReason='Import job could not be queued';job.completedAt=new Date();job.updatedAt=new Date();await job.save();throw new AppError(503,'IMPORT_QUEUE_UNAVAILABLE','Import job could not be queued')}return{success:true,data:job}});

 app.post('/api/internal/imports/state',async(request:any)=>{if(!workerSecret(request.headers['x-worker-secret'] as string|undefined))throw forbidden('Invalid worker credentials');const{jobId,schoolId,status,totalRows,failureReason}=request.body??{};if(!validId(jobId)||!validId(schoolId)||!['PARSING','IMPORTING','FAILED'].includes(status))throw new AppError(400,'INVALID_IMPORT_STATE','Invalid import state callback');return runWithTenant({isPlatform:true,requestId:request.id},async()=>{const job:any=await ImportJob.findOne({_id:jobId,schoolId});if(!job)throw new AppError(404,'NOT_FOUND','Import job not found');job.status=status;if(status==='PARSING'&&!job.startedAt)job.startedAt=new Date();if(Number.isInteger(totalRows)&&totalRows>=0)job.totalRows=totalRows;if(status==='FAILED'){job.failureReason=String(failureReason||'Import failed').slice(0,500);job.completedAt=new Date()}job.updatedAt=new Date();await job.save();return{success:true,data:{id:job._id,status:job.status}}})});

 app.post('/api/internal/imports/batch',async(request:any)=>{if(!workerSecret(request.headers['x-worker-secret'] as string|undefined))throw forbidden('Invalid worker credentials');const{jobId,schoolId,type,rows}=request.body??{};if(!validId(jobId)||!validId(schoolId)||!allowed.has(type)||!Array.isArray(rows)||rows.length>250)throw new AppError(400,'INVALID_IMPORT_BATCH','Invalid import batch');return runWithTenant({isPlatform:true,requestId:request.id},async()=>{const job:any=await ImportJob.findOne({_id:jobId,schoolId});if(!job||job.type!==type)throw new AppError(404,'NOT_FOUND','Import job not found');if(['COMPLETED','COMPLETED_WITH_ERRORS','FAILED'].includes(job.status))throw new AppError(409,'IMPORT_STATE','Import job is already finished');const scopedRows:RowEnvelope[]=rows.map((item:any,index:number)=>({row:Number(item?.row)||job.processedRows+index+2,data:item?.data&&typeof item.data==='object'?item.data:{}}));const result=type==='students'?await prepareStudents(scopedRows):await prepareTeachers(scopedRows);const docs=result.prepared.map(doc=>({...doc,schoolId,deletedAt:null}));let inserted=0;if(docs.length){const created=type==='students'?await Student.insertMany(docs,{ordered:true}):await Teacher.insertMany(docs,{ordered:true});inserted=created.length}job.status='IMPORTING';job.processedRows+=scopedRows.length;job.insertedRows+=inserted;job.rejectedRows+=result.errors.length;job.errorCount+=result.errors.length;if(result.errors.length)job.errors=[...(job.errors||[]),...result.errors].slice(0,500);job.updatedAt=new Date();await job.save();return{success:true,data:{processed:scopedRows.length,inserted,rejected:result.errors.length}}})});

 app.post('/api/internal/imports/complete',async(request:any)=>{if(!workerSecret(request.headers['x-worker-secret'] as string|undefined))throw forbidden('Invalid worker credentials');const{jobId,schoolId,totalRows}=request.body??{};if(!validId(jobId)||!validId(schoolId))throw new AppError(400,'INVALID_IMPORT_COMPLETE','Invalid import completion callback');return runWithTenant({isPlatform:true,requestId:request.id},async()=>{const job:any=await ImportJob.findOne({_id:jobId,schoolId});if(!job)throw new AppError(404,'NOT_FOUND','Import job not found');if(job.status==='FAILED')return{success:true,data:job};if(Number.isInteger(totalRows)&&totalRows>=0)job.totalRows=totalRows;job.status=job.errorCount>0?'COMPLETED_WITH_ERRORS':'COMPLETED';job.completedAt=new Date();job.updatedAt=new Date();await job.save();return{success:true,data:job}})});
}
