import type { FastifyInstance } from 'fastify';
import { Student,Teacher,Staff,Guardian } from '../people/models.js';
import { Admission } from '../admissions/models.js';
import { Attendance } from '../attendance/models.js';
import { Assignment,AssignmentSubmission } from '../assignments/models.js';
import { TimetableSlot } from '../timetable/models.js';
import { Exam } from '../examinations/models.js';
import { ReportCard } from '../report-cards/models.js';
import { FeeInvoice,FeePayment } from '../fees/models.js';
import { LibraryBook,BookIssue } from '../library/models.js';
import { Payroll } from '../payroll/models.js';
import { LeaveRequest } from '../leaves/models.js';
import { Notice } from '../communication/models.js';

const money=(value:number)=>Math.round(value*100)/100;
const card=(label:string,value:string|number,note:string)=>({label,value:String(value),note});
function noticeFilter(role:string){const now=new Date();return{status:'PUBLISHED',$and:[{$or:[{publishAt:{$exists:false}},{publishAt:null},{publishAt:{$lte:now}}]},{$or:[{expiresAt:{$exists:false}},{expiresAt:null},{expiresAt:{$gt:now}}]},{$or:[{audience:{$size:0}},{audience:'ALL'},{audience:role}]}]}}

export async function dashboardRoutes(app:FastifyInstance){
 app.get('/api/dashboard/overview',async(request:any)=>{
   const role=String(request.auth?.role||''),profileId=request.auth?.profileId,notices=await Notice.countDocuments(noticeFilter(role));
   if(role==='STUDENT'&&profileId){const student=await Student.findById(profileId).lean();if(!student)return{success:true,data:{role,cards:[card('Profile','Unavailable','Link student profile to this login')]}};const[attendance,assignments,reports,feeAgg]=await Promise.all([Attendance.aggregate([{$match:{studentId:student._id}},{$group:{_id:'$status',count:{$sum:1}}}]),Assignment.countDocuments({classId:student.classId,sectionId:student.sectionId,published:true}),ReportCard.countDocuments({studentId:student._id,publishedAt:{$ne:null}}),FeeInvoice.aggregate([{$match:{studentId:student._id,status:{$nin:['CANCELLED','PAID']}}},{$group:{_id:null,balance:{$sum:'$balance'}}}])]);const total=attendance.reduce((n:any,x:any)=>n+x.count,0),present=attendance.filter((x:any)=>['PRESENT','LATE'].includes(x._id)).reduce((n:any,x:any)=>n+x.count,0);return{success:true,data:{role,name:`${student.firstName} ${student.lastName||''}`.trim(),cards:[card('Attendance',total?`${Math.round(present/total*100)}%`:'—','Recorded attendance'),card('Assignments',assignments,'Published for your class'),card('Report cards',reports,'Published results'),card('Fee balance',`₹${money(feeAgg[0]?.balance||0).toLocaleString('en-IN')}`,'Outstanding dues')],notices}}}
   if(role==='PARENT'&&profileId){const guardian=await Guardian.findById(profileId).lean(),ids=(guardian?.studentIds||[]) as any[];const[students,feeAgg,reports]=await Promise.all([Student.countDocuments({_id:{$in:ids},lifecycle:'ACTIVE'}),FeeInvoice.aggregate([{$match:{studentId:{$in:ids},status:{$nin:['CANCELLED','PAID']}}},{$group:{_id:null,balance:{$sum:'$balance'}}}]),ReportCard.countDocuments({studentId:{$in:ids},publishedAt:{$ne:null}})]);return{success:true,data:{role,cards:[card('Linked students',students,'Active children in this school'),card('Fee balance',`₹${money(feeAgg[0]?.balance||0).toLocaleString('en-IN')}`,'Across linked students'),card('Published reports',reports,'Available report cards'),card('Notices',notices,'Visible school notices')]}}}
   if(role==='TEACHER'&&profileId){const now=new Date(),day=((now.getDay()+6)%7)+1,assignmentIds=await Assignment.distinct('_id',{teacherId:profileId});const[classes,assignments,submissions,leaves]=await Promise.all([TimetableSlot.countDocuments({teacherId:profileId,day,published:true}),Assignment.countDocuments({teacherId:profileId}),AssignmentSubmission.countDocuments({assignmentId:{$in:assignmentIds},status:{$in:['SUBMITTED','LATE']}}),LeaveRequest.countDocuments({applicantType:'TEACHER',applicantId:profileId,status:'PENDING'})]);return{success:true,data:{role,cards:[card('Today’s periods',classes,'Published timetable'),card('Assignments',assignments,'Created by you'),card('Submissions',submissions,'Awaiting grading on your assignments'),card('Leave requests',leaves,'Your pending requests')],notices}}}
   if(role==='ACCOUNTS_MANAGER'){const[feeAgg,payments]=await Promise.all([FeeInvoice.aggregate([{$match:{status:{$ne:'CANCELLED'}}},{$group:{_id:null,total:{$sum:'$total'},paid:{$sum:'$paid'},balance:{$sum:'$balance'}}}]),FeePayment.countDocuments({status:'SUCCESS'})]);const f=feeAgg[0]||{};return{success:true,data:{role,cards:[card('Billed',`₹${money(f.total||0).toLocaleString('en-IN')}`,'Active invoices'),card('Collected',`₹${money(f.paid||0).toLocaleString('en-IN')}`,'Recorded payments'),card('Outstanding',`₹${money(f.balance||0).toLocaleString('en-IN')}`,'Open balance'),card('Receipts',payments,'Successful payments')]}}}
   if(role==='HR_MANAGER'){const[teachers,staff,payroll,leaves]=await Promise.all([Teacher.countDocuments({status:'ACTIVE'}),Staff.countDocuments({status:'ACTIVE'}),Payroll.countDocuments({status:{$in:['DRAFT','APPROVED']}}),LeaveRequest.countDocuments({applicantType:{$in:['TEACHER','STAFF']},status:'PENDING'})]);return{success:true,data:{role,cards:[card('Teachers',teachers,'Active faculty records'),card('Staff',staff,'Active non-teaching records'),card('Payroll runs',payroll,'Draft or approved'),card('Pending leaves',leaves,'Needs HR decision')]}}}
   if(role==='EXAM_CONTROLLER'){const[draft,entry,published,reports]=await Promise.all([Exam.countDocuments({status:'DRAFT'}),Exam.countDocuments({status:'MARKS_ENTRY'}),Exam.countDocuments({status:'PUBLISHED'}),ReportCard.countDocuments({publishedAt:{$ne:null}})]);return{success:true,data:{role,cards:[card('Draft exams',draft,'Configuration stage'),card('Marks entry',entry,'Open for marks'),card('Published exams',published,'Visible results'),card('Report cards',reports,'Published records')]}}}
   if(role==='LIBRARIAN'){const now=new Date(),[books,available,issued,overdue]=await Promise.all([LibraryBook.countDocuments(),LibraryBook.countDocuments({status:'AVAILABLE'}),BookIssue.countDocuments({status:{$in:['ISSUED','OVERDUE']}}),BookIssue.countDocuments({status:{$in:['ISSUED','OVERDUE']},dueAt:{$lt:now}})]);return{success:true,data:{role,cards:[card('Books',books,'Catalogue copies'),card('Available',available,'Ready to issue'),card('Issued',issued,'Currently borrowed'),card('Overdue',overdue,'Needs follow-up')]}}}
   if(role==='ADMISSION_MANAGER'){const[applied,review,accepted,admitted]=await Promise.all([Admission.countDocuments({status:'APPLIED'}),Admission.countDocuments({status:{$in:['DOCUMENT_VERIFICATION','UNDER_REVIEW']}}),Admission.countDocuments({status:'ACCEPTED'}),Admission.countDocuments({status:'ADMITTED'})]);return{success:true,data:{role,cards:[card('Applications',applied,'New applications'),card('In review',review,'Verification pipeline'),card('Accepted',accepted,'Ready to admit'),card('Admitted',admitted,'Converted to student')]}}}
   const[students,teachers,staff,admissions,pendingLeaves,feeAgg]=await Promise.all([Student.countDocuments({lifecycle:'ACTIVE'}),Teacher.countDocuments({status:'ACTIVE'}),Staff.countDocuments({status:'ACTIVE'}),Admission.countDocuments({status:{$in:['APPLIED','UNDER_REVIEW','DOCUMENT_VERIFICATION']}}),LeaveRequest.countDocuments({status:'PENDING'}),FeeInvoice.aggregate([{$match:{status:{$ne:'CANCELLED'}}},{$group:{_id:null,total:{$sum:'$total'},paid:{$sum:'$paid'},balance:{$sum:'$balance'}}}])]);const fees=feeAgg[0]||{total:0,paid:0,balance:0};return{success:true,data:{role,cards:[card('Active students',students,'Current tenant'),card('Teachers',teachers,'Active faculty records'),card('Pending admissions',admissions,'Needs review'),card('Outstanding fees',`₹${money(fees.balance||0).toLocaleString('en-IN')}`,'Student invoices')],secondary:{staff,pendingLeaves,fees,notices}}};
 });
}
