import type { FastifyInstance } from 'fastify';
import { Types } from 'mongoose';
import { PERMISSIONS } from '@erp/contracts';
import { requirePermission } from '../../core/security.js';
import { AppError } from '../../core/errors.js';
import { writeAudit } from '../../core/audit.js';
import { SalaryStructure,Payroll } from './models.js';
import { Teacher,Staff } from '../people/models.js';

const validId=(value:any)=>Types.ObjectId.isValid(String(value||''));
const clean=(value:any,max=180)=>String(value??'').trim().slice(0,max);
const money=(value:any,label:string)=>{const n=Number(value);if(!Number.isFinite(n)||n<0)throw new AppError(400,'INVALID_AMOUNT',`${label} must be a non-negative number`);return Math.round(n*100)/100};
function dateValue(value:any,label:string){const date=new Date(value);if(Number.isNaN(date.getTime()))throw new AppError(400,'INVALID_DATE',`${label} is invalid`);return date}
function components(value:any,label:string){if(value===undefined)return[];if(!Array.isArray(value)||value.length>50)throw new AppError(400,'INVALID_COMPONENTS',`${label} must contain at most 50 components`);return value.map((raw:any,index:number)=>{const name=clean(raw?.name,120);if(!name)throw new AppError(400,'INVALID_COMPONENT',`${label} component ${index+1} needs a name`);const kind=raw?.kind==='PERCENTAGE'?'PERCENTAGE':'FIXED';return kind==='PERCENTAGE'?{name,kind,amount:0,percentage:Math.min(100,money(raw?.percentage,`${name} percentage`))}:{name,kind,amount:money(raw?.amount,`${name} amount`),percentage:0}})}
async function validateEmployee(type:any,id:any){const employeeType=String(type||'');if(!['TEACHER','STAFF'].includes(employeeType)||!validId(id))throw new AppError(400,'INVALID_EMPLOYEE','Valid teacher or staff employee is required');const Model=employeeType==='TEACHER'?Teacher:Staff;const employee:any=await Model.findById(id).select('_id firstName lastName employeeNo status').lean();if(!employee||employee.status!=='ACTIVE')throw new AppError(404,'EMPLOYEE_NOT_FOUND','Active employee not found in this school');return{employeeType,employeeId:new Types.ObjectId(String(id)),employee}}
async function structureData(body:any,current:any={}){const target=await validateEmployee(body?.employeeType??current.employeeType,body?.employeeId??current.employeeId),baseAmount=money(body?.baseAmount??current.baseAmount,'Base amount'),effectiveFrom=body?.effectiveFrom===undefined?current.effectiveFrom:dateValue(body.effectiveFrom,'effectiveFrom'),effectiveTo=body?.effectiveTo===undefined?current.effectiveTo:(body.effectiveTo?dateValue(body.effectiveTo,'effectiveTo'):undefined);if(effectiveTo&&effectiveTo<effectiveFrom)throw new AppError(400,'INVALID_DATE_RANGE','effectiveTo must be on or after effectiveFrom');return{employeeType:target.employeeType,employeeId:target.employeeId,baseAmount,earnings:body?.earnings===undefined?(current.earnings||[]):components(body.earnings,'Earnings'),deductions:body?.deductions===undefined?(current.deductions||[]):components(body.deductions,'Deductions'),effectiveFrom,effectiveTo,isActive:body?.isActive===undefined?(current.isActive??true):Boolean(body.isActive),updatedAt:new Date()}}
function period(month:number,year:number){if(!Number.isInteger(month)||month<1||month>12||!Number.isInteger(year)||year<2000||year>2100)throw new AppError(400,'INVALID_PERIOD','Payroll month/year are invalid');return{start:new Date(Date.UTC(year,month-1,1)),end:new Date(Date.UTC(year,month,0,23,59,59,999))}}
function calculate(structure:any){const base=money(structure.baseAmount,'Base amount'),earnings=(structure.earnings||[]).map((c:any)=>({...c,calculated:c.kind==='PERCENTAGE'?Math.round(base*Number(c.percentage||0))/100:money(c.amount||0,c.name)})),earningTotal=Math.round(earnings.reduce((n:number,c:any)=>n+c.calculated,0)*100)/100,gross=Math.round((base+earningTotal)*100)/100,deductionRows=(structure.deductions||[]).map((c:any)=>({...c,calculated:c.kind==='PERCENTAGE'?Math.round(gross*Number(c.percentage||0))/100:money(c.amount||0,c.name)})),rawDeductions=Math.round(deductionRows.reduce((n:number,c:any)=>n+c.calculated,0)*100)/100,deductions=Math.min(gross,rawDeductions),net=Math.round((gross-deductions)*100)/100;return{gross,deductions,net,breakdown:{baseAmount:base,earnings,deductions:deductionRows,rawDeductions}}}

export async function payrollRoutes(app:FastifyInstance){
 app.get('/api/payroll/structures',{preHandler:requirePermission(PERMISSIONS.PAYROLL_READ)},async()=>({success:true,data:await SalaryStructure.find().sort({employeeType:1,employeeId:1,effectiveFrom:-1}).limit(1000).lean()}));
 app.post('/api/payroll/structures',{preHandler:requirePermission(PERMISSIONS.PAYROLL_PROCESS)},async(request:any)=>{const data=await structureData(request.body),item=await SalaryStructure.create(data);await writeAudit({action:'payroll.structure-create',entity:'salary-structure',entityId:String(item._id),after:{employeeType:item.employeeType,employeeId:String(item.employeeId),baseAmount:item.baseAmount,effectiveFrom:item.effectiveFrom},ip:request.ip});return{success:true,data:item}});
 app.patch('/api/payroll/structures/:id',{preHandler:requirePermission(PERMISSIONS.PAYROLL_PROCESS)},async(request:any)=>{const item:any=await SalaryStructure.findById(request.params.id);if(!item)throw new AppError(404,'NOT_FOUND','Salary structure not found');const before=item.toObject(),data=await structureData(request.body,item);Object.assign(item,data);await item.save();await writeAudit({action:'payroll.structure-update',entity:'salary-structure',entityId:String(item._id),before,after:item.toObject(),ip:request.ip});return{success:true,data:item}});
 app.delete('/api/payroll/structures/:id',{preHandler:requirePermission(PERMISSIONS.PAYROLL_PROCESS)},async(request:any)=>{const item:any=await SalaryStructure.findById(request.params.id);if(!item)throw new AppError(404,'NOT_FOUND','Salary structure not found');item.isActive=false;item.deletedAt=new Date();item.updatedAt=new Date();await item.save();await writeAudit({action:'payroll.structure-delete',entity:'salary-structure',entityId:String(item._id),before:{isActive:true},after:{deleted:true},ip:request.ip});return{success:true,data:{id:item._id,deleted:true}}});
 app.get('/api/payroll/runs',{preHandler:requirePermission(PERMISSIONS.PAYROLL_READ)},async(request:any)=>{const filter:any={};if(request.query?.month)filter.month=Number(request.query.month);if(request.query?.year)filter.year=Number(request.query.year);if(request.query?.status){const status=String(request.query.status);if(!['DRAFT','APPROVED','PAID','CANCELLED'].includes(status))throw new AppError(400,'INVALID_STATUS','Invalid payroll status');filter.status=status}return{success:true,data:await Payroll.find(filter).sort({year:-1,month:-1,employeeType:1}).limit(1000).lean()}});
 app.get('/api/payroll/runs/:id',{preHandler:requirePermission(PERMISSIONS.PAYROLL_READ)},async(request:any)=>{const item=await Payroll.findById(request.params.id).lean();if(!item)throw new AppError(404,'NOT_FOUND','Payroll record not found');return{success:true,data:item}});
 app.post('/api/payroll/run',{preHandler:requirePermission(PERMISSIONS.PAYROLL_PROCESS)},async(request:any)=>{const month=Number(request.body?.month),year=Number(request.body?.year),range=period(month,year),structures:any[]=await SalaryStructure.find({isActive:true,effectiveFrom:{$lte:range.end},$or:[{effectiveTo:{$exists:false}},{effectiveTo:null},{effectiveTo:{$gte:range.start}}]}).sort({effectiveFrom:-1}).lean(),selected=new Map<string,any>();for(const structure of structures){const key=`${structure.employeeType}:${structure.employeeId}`;if(!selected.has(key))selected.set(key,structure)}const results:any[]=[];let locked=0,cancelled=0;for(const structure of selected.values()){const existing:any=await Payroll.findOne({month,year,employeeType:structure.employeeType,employeeId:structure.employeeId});if(existing&&['APPROVED','PAID'].includes(existing.status)){locked++;continue}if(existing?.status==='CANCELLED'){cancelled++;continue}const calculated=calculate(structure),payload={month,year,employeeType:structure.employeeType,employeeId:structure.employeeId,salaryStructureId:structure._id,...calculated,status:'DRAFT',generatedAt:new Date(),updatedAt:new Date()};const item=await Payroll.findOneAndUpdate({month,year,employeeType:structure.employeeType,employeeId:structure.employeeId},{$set:payload,$setOnInsert:{createdAt:new Date()}},{new:true,upsert:true,setDefaultsOnInsert:true});results.push(item)}await writeAudit({action:'payroll.run',entity:'payroll',after:{month,year,generated:results.length,locked,cancelled},ip:request.ip});return{success:true,data:{count:results.length,locked,cancelled,items:results}}});
 app.post('/api/payroll/runs/:id/approve',{preHandler:requirePermission(PERMISSIONS.PAYROLL_PROCESS)},async(request:any)=>{const item:any=await Payroll.findById(request.params.id);if(!item)throw new AppError(404,'NOT_FOUND','Payroll record not found');if(item.status==='APPROVED')return{success:true,data:item};if(item.status!=='DRAFT')throw new AppError(409,'PAYROLL_STATE','Only draft payroll can be approved');item.status='APPROVED';item.approvedBy=request.auth.sub;item.approvedAt=new Date();item.updatedAt=new Date();await item.save();await writeAudit({action:'payroll.approve',entity:'payroll',entityId:String(item._id),before:{status:'DRAFT'},after:{status:'APPROVED',net:item.net},ip:request.ip});return{success:true,data:item}});
 app.post('/api/payroll/runs/:id/pay',{preHandler:requirePermission(PERMISSIONS.PAYROLL_PROCESS)},async(request:any)=>{const item:any=await Payroll.findById(request.params.id);if(!item)throw new AppError(404,'NOT_FOUND','Payroll record not found');if(item.status==='PAID')return{success:true,data:item};if(item.status!=='APPROVED')throw new AppError(409,'PAYROLL_STATE','Approve payroll before marking it paid');const reference=clean(request.body?.reference,180);if(!reference)throw new AppError(400,'PAYMENT_REFERENCE_REQUIRED','Payment reference is required');item.status='PAID';item.paidBy=request.auth.sub;item.paidAt=new Date();item.paymentReference=reference;item.updatedAt=new Date();await item.save();await writeAudit({action:'payroll.pay',entity:'payroll',entityId:String(item._id),before:{status:'APPROVED'},after:{status:'PAID',net:item.net,paymentReference:reference},ip:request.ip});return{success:true,data:item}});
 app.post('/api/payroll/runs/:id/cancel',{preHandler:requirePermission(PERMISSIONS.PAYROLL_PROCESS)},async(request:any)=>{const item:any=await Payroll.findById(request.params.id);if(!item)throw new AppError(404,'NOT_FOUND','Payroll record not found');if(item.status==='CANCELLED')return{success:true,data:item};if(item.status!=='DRAFT')throw new AppError(409,'PAYROLL_STATE','Only draft payroll can be cancelled');item.status='CANCELLED';item.updatedAt=new Date();await item.save();await writeAudit({action:'payroll.cancel',entity:'payroll',entityId:String(item._id),before:{status:'DRAFT'},after:{status:'CANCELLED'},ip:request.ip});return{success:true,data:item}});
 app.get('/api/payroll/runs/:id/payslip',{preHandler:requirePermission(PERMISSIONS.PAYROLL_READ)},async(request:any)=>{const item:any=await Payroll.findById(request.params.id).lean();if(!item)throw new AppError(404,'NOT_FOUND','Payroll record not found');const Model=item.employeeType==='TEACHER'?Teacher:Staff,employee:any=await Model.findById(item.employeeId).select('firstName lastName employeeNo department designation').lean();if(!employee)throw new AppError(404,'EMPLOYEE_NOT_FOUND','Employee not found');return{success:true,data:{payroll:item,employee:{id:employee._id,name:`${employee.firstName} ${employee.lastName||''}`.trim(),employeeNo:employee.employeeNo,department:employee.department,designation:employee.designation}}}});
}
