import type { FastifyInstance } from 'fastify';
import { Types } from 'mongoose';
import { PERMISSIONS } from '@erp/contracts';
import { requirePermission } from '../../core/security.js';
import { AppError } from '../../core/errors.js';
import { Attendance,FacultyAttendance } from './models.js';
import { writeAudit } from '../../core/audit.js';
import { getTenantContext } from '../../core/tenant-context.js';
import { accessibleStudentIds,assertStudentAccessible } from '../people/access.js';
import { Student,Teacher,Staff } from '../people/models.js';
import { AcademicSession,Subject } from '../academics/models.js';
import { assertAttendanceMarkerScope,attendanceDate,boundedRemark,validateAttendanceBatch,validateSectionContext,validObjectId } from './service.js';

const facultyStatuses=new Set(['PRESENT','ABSENT','LATE','LEAVE','HALF_DAY']);
const timePattern=/^(?:[01]\d|2[0-3]):[0-5]\d$/;
function optionalDate(value:any,label:string){if(value===undefined||value===null||value==='')return undefined;try{return attendanceDate(value)}catch{throw new AppError(400,'INVALID_DATE',`${label} must use YYYY-MM-DD`)}}

export async function attendanceRoutes(app:FastifyInstance){
 app.get('/api/attendance',{preHandler:requirePermission(PERMISSIONS.ATTENDANCE_READ)},async(request:any)=>{
  const{studentId,sectionId,sessionId,subjectId,period,from,to}=request.query??{},filter:any={};const accessible=await accessibleStudentIds(request);if(accessible!==null)filter.studentId={$in:accessible};if(studentId){if(!validObjectId(studentId))throw new AppError(400,'INVALID_STUDENT','Invalid studentId');await assertStudentAccessible(request,studentId);filter.studentId=new Types.ObjectId(String(studentId))}if(sectionId){if(!validObjectId(sectionId))throw new AppError(400,'INVALID_SECTION','Invalid sectionId');filter.sectionId=new Types.ObjectId(String(sectionId))}if(sessionId){if(!validObjectId(sessionId))throw new AppError(400,'INVALID_SESSION','Invalid sessionId');filter.sessionId=new Types.ObjectId(String(sessionId))}if(subjectId){if(!validObjectId(subjectId))throw new AppError(400,'INVALID_SUBJECT','Invalid subjectId');filter.subjectId=new Types.ObjectId(String(subjectId))}if(period!==undefined){const parsed=Number(period);if(!Number.isInteger(parsed)||parsed<1)throw new AppError(400,'INVALID_PERIOD','Invalid period');filter.period=parsed}const start=optionalDate(from,'from'),end=optionalDate(to,'to');if(start||end){if(start&&end&&start>end)throw new AppError(400,'INVALID_RANGE','from must be before to');filter.date={...(start?{$gte:start}:{}),...(end?{$lte:end}:{})}}return{success:true,data:await Attendance.find(filter).sort({date:-1,period:1}).limit(1000).populate('studentId','firstName lastName admissionNo rollNo').populate('subjectId','name code').lean()};
 });

 app.get('/api/attendance/roster',{preHandler:requirePermission(PERMISSIONS.ATTENDANCE_MARK)},async(request:any)=>{
  const{sectionId,subjectId,date,sessionId,period}=request.query??{};const{section,klass}=await validateSectionContext(sectionId);await assertAttendanceMarkerScope(request,sectionId,subjectId||undefined);if(subjectId){if(!validObjectId(subjectId)||!await Subject.findById(subjectId).select('_id').lean())throw new AppError(404,'SUBJECT_NOT_FOUND','Subject not found')}const students=await Student.find({sectionId:section._id,classId:klass._id,lifecycle:'ACTIVE'}).select('firstName lastName admissionNo rollNo photoUrl').sort({rollNo:1,firstName:1}).lean();let existing:any[]=[];if(date){const attendanceFilter:any={date:attendanceDate(date),sectionId:section._id,studentId:{$in:students.map((student:any)=>student._id)}};if(sessionId){if(!validObjectId(sessionId)||!await AcademicSession.findById(sessionId).select('_id').lean())throw new AppError(404,'SESSION_NOT_FOUND','Academic session not found');attendanceFilter.sessionId=new Types.ObjectId(String(sessionId))}if(subjectId)attendanceFilter.subjectId=new Types.ObjectId(String(subjectId));else attendanceFilter.subjectId={$in:[null,undefined]};if(subjectId){const parsed=Number(period);if(!Number.isInteger(parsed)||parsed<1)throw new AppError(400,'INVALID_PERIOD','Period is required for subject attendance');attendanceFilter.period=parsed}existing=await Attendance.find(attendanceFilter).select('studentId status remark').lean()}const byStudent=new Map(existing.map((row:any)=>[String(row.studentId),row]));return{success:true,data:{class:{id:klass._id,name:klass.name},section:{id:section._id,name:section.name},students:students.map((student:any)=>({...student,status:byStudent.get(String(student._id))?.status||'PRESENT',remark:byStudent.get(String(student._id))?.remark||''}))}};
 });

 app.post('/api/attendance/mark',{preHandler:requirePermission(PERMISSIONS.ATTENDANCE_MARK)},async(request:any)=>{
  const validated=await validateAttendanceBatch(request,request.body);const schoolId=getTenantContext()?.schoolId;if(!schoolId)throw new AppError(403,'TENANT_REQUIRED','School context required');const ops=validated.records.map(row=>({updateOne:{filter:{schoolId,date:validated.date,studentId:row.studentId,subjectId:validated.subjectId||null,period:validated.period||null},update:{$set:{date:validated.date,sessionId:validated.sessionId,classId:validated.classId,sectionId:validated.sectionId,studentId:row.studentId,subjectId:validated.subjectId,period:validated.period,status:row.status,remark:row.remark,markedBy:request.auth.sub,updatedAt:new Date()},$setOnInsert:{schoolId,createdAt:new Date(),deletedAt:null}},upsert:true}}));const result=await Attendance.bulkWrite(ops,{ordered:true});await writeAudit({action:'attendance.mark',entity:'attendance',after:{date:validated.date,sectionId:String(validated.sectionId),subjectId:validated.subjectId?String(validated.subjectId):undefined,period:validated.period,count:validated.records.length},ip:request.ip});return{success:true,data:{upserted:result.upsertedCount,modified:result.modifiedCount,matched:result.matchedCount}};
 });

 app.get('/api/attendance/summary/:studentId',{preHandler:requirePermission(PERMISSIONS.ATTENDANCE_READ)},async(request:any)=>{
  if(!validObjectId(request.params.studentId))throw new AppError(404,'NOT_FOUND','Student not found');await assertStudentAccessible(request,request.params.studentId);const match:any={studentId:new Types.ObjectId(request.params.studentId)};if(request.query?.sessionId){if(!validObjectId(request.query.sessionId))throw new AppError(400,'INVALID_SESSION','Invalid sessionId');match.sessionId=new Types.ObjectId(String(request.query.sessionId))}const start=optionalDate(request.query?.from,'from'),end=optionalDate(request.query?.to,'to');if(start||end)match.date={...(start?{$gte:start}:{}),...(end?{$lte:end}:{})};const rows=await Attendance.aggregate([{$match:match},{$group:{_id:'$status',count:{$sum:1}}}]);const total=rows.reduce((n:number,r:any)=>n+r.count,0),present=rows.find((r:any)=>r._id==='PRESENT')?.count||0,late=rows.find((r:any)=>r._id==='LATE')?.count||0;return{success:true,data:{total,present,percentage:total?Math.round(((present+late)*100/total)*100)/100:0,breakdown:rows}};
 });

 app.get('/api/faculty-attendance',{preHandler:requirePermission(PERMISSIONS.ATTENDANCE_READ)},async(request:any)=>{
  const role=request.auth?.role,filter:any={};if(role==='TEACHER'){if(!request.auth?.profileId)throw new AppError(403,'PROFILE_REQUIRED','Teacher profile is required');filter.personType='TEACHER';filter.personId=request.auth.profileId}else if(!['SCHOOL_ADMIN','HR_MANAGER'].includes(role))throw new AppError(403,'FORBIDDEN','Faculty attendance is not available for this role');if(request.query?.date)filter.date=attendanceDate(request.query.date);if(request.query?.personType&&role!=='TEACHER'){if(!['TEACHER','STAFF'].includes(request.query.personType))throw new AppError(400,'INVALID_PERSON_TYPE','personType must be TEACHER or STAFF');filter.personType=request.query.personType}return{success:true,data:await FacultyAttendance.find(filter).sort({date:-1}).limit(1000).lean()};
 });

 app.post('/api/faculty-attendance/mark',{preHandler:requirePermission(PERMISSIONS.STAFF_WRITE)},async(request:any)=>{
  const{date,records}=request.body??{};if(!Array.isArray(records)||!records.length||records.length>300)throw new AppError(400,'INVALID_INPUT','1 to 300 faculty attendance records are required');const normalizedDate=attendanceDate(date),keys=new Set<string>();for(const row of records){if(!['TEACHER','STAFF'].includes(row?.personType)||!validObjectId(row?.personId))throw new AppError(400,'INVALID_PERSON','Each record needs a valid TEACHER/STAFF person');if(!facultyStatuses.has(String(row?.status||'')))throw new AppError(400,'INVALID_STATUS','Invalid faculty attendance status');if(row.checkIn&&!timePattern.test(String(row.checkIn)))throw new AppError(400,'INVALID_TIME','checkIn must use HH:mm');if(row.checkOut&&!timePattern.test(String(row.checkOut)))throw new AppError(400,'INVALID_TIME','checkOut must use HH:mm');const key=`${row.personType}:${row.personId}`;if(keys.has(key))throw new AppError(400,'DUPLICATE_PERSON','Faculty payload contains duplicate people');keys.add(key)}const teacherIds=records.filter((row:any)=>row.personType==='TEACHER').map((row:any)=>row.personId),staffIds=records.filter((row:any)=>row.personType==='STAFF').map((row:any)=>row.personId);const[teacherCount,staffCount]=await Promise.all([teacherIds.length?Teacher.countDocuments({_id:{$in:teacherIds}}):0,staffIds.length?Staff.countDocuments({_id:{$in:staffIds}}):0]);if(teacherCount!==teacherIds.length||staffCount!==staffIds.length)throw new AppError(409,'FACULTY_SCOPE_MISMATCH','One or more people do not exist in this school');const schoolId=getTenantContext()?.schoolId;if(!schoolId)throw new AppError(403,'TENANT_REQUIRED','School context required');const ops=records.map((row:any)=>({updateOne:{filter:{schoolId,date:normalizedDate,personType:row.personType,personId:new Types.ObjectId(String(row.personId))},update:{$set:{date:normalizedDate,personType:row.personType,personId:new Types.ObjectId(String(row.personId)),status:row.status,checkIn:row.checkIn||undefined,checkOut:row.checkOut||undefined,source:'MANUAL',markedBy:request.auth.sub,updatedAt:new Date()},$setOnInsert:{schoolId,createdAt:new Date(),deletedAt:null}},upsert:true}}));const result=await FacultyAttendance.bulkWrite(ops,{ordered:true});await writeAudit({action:'faculty-attendance.mark',entity:'faculty-attendance',after:{date:normalizedDate,count:records.length},ip:request.ip});return{success:true,data:{upserted:result.upsertedCount,modified:result.modifiedCount,matched:result.matchedCount}};
 });
}
