import type { FastifyInstance } from 'fastify';
import { Types } from 'mongoose';
import { PERMISSIONS } from '@erp/contracts';
import { requirePermission } from '../../core/security.js';
import { Attendance,FacultyAttendance } from './models.js';
import { writeAudit } from '../../core/audit.js';
import { getTenantContext } from '../../core/tenant-context.js';
export async function attendanceRoutes(app:FastifyInstance){
 app.get('/api/attendance',{preHandler:requirePermission(PERMISSIONS.ATTENDANCE_READ)},async(request:any)=>{const{studentId,sectionId,from,to}=request.query??{};const filter:any={};if(studentId)filter.studentId=studentId;if(sectionId)filter.sectionId=sectionId;if(from||to)filter.date={...(from?{$gte:new Date(from)}:{}),...(to?{$lte:new Date(to)}:{})};return{success:true,data:await Attendance.find(filter).sort({date:-1}).limit(500).lean()}});
 app.post('/api/attendance/mark',{preHandler:requirePermission(PERMISSIONS.ATTENDANCE_MARK)},async(request:any)=>{const{date,sessionId,classId,sectionId,subjectId,period,records}=request.body??{};if(!Array.isArray(records)||!records.length)return{success:false,error:{code:'INVALID_INPUT',message:'records required'}};const schoolId=getTenantContext()?.schoolId;if(!schoolId)throw new Error('Tenant context missing');const ops=records.map((r:any)=>({updateOne:{filter:{schoolId,date:new Date(date),studentId:r.studentId,subjectId:subjectId||null,period:period||null},update:{$set:{date:new Date(date),sessionId,classId,sectionId,studentId:r.studentId,subjectId,period,status:r.status,remark:r.remark,markedBy:request.auth.sub,updatedAt:new Date()},$setOnInsert:{schoolId,createdAt:new Date(),deletedAt:null}},upsert:true}}));const result=await Attendance.bulkWrite(ops);await writeAudit({action:'attendance.mark',entity:'attendance',after:{date,sectionId,count:records.length},ip:request.ip});return{success:true,data:{upserted:result.upsertedCount,modified:result.modifiedCount}}});
 app.get('/api/attendance/summary/:studentId',{preHandler:requirePermission(PERMISSIONS.ATTENDANCE_READ)},async(request:any)=>{const rows=await Attendance.aggregate([{$match:{studentId:new Types.ObjectId(request.params.studentId)}},{$group:{_id:'$status',count:{$sum:1}}}]);const total=rows.reduce((n:any,r:any)=>n+r.count,0),present=rows.find((r:any)=>r._id==='PRESENT')?.count||0;return{success:true,data:{total,present,percentage:total?Math.round((present/total)*10000)/100:0,breakdown:rows}}});
 app.get('/api/faculty-attendance',{preHandler:requirePermission(PERMISSIONS.ATTENDANCE_READ)},async(request:any)=>{const filter:any={};if(request.query?.date)filter.date=new Date(request.query.date);if(request.query?.personType)filter.personType=request.query.personType;return{success:true,data:await FacultyAttendance.find(filter).sort({date:-1}).limit(500).lean()}});
 app.post('/api/faculty-attendance/mark',{preHandler:requirePermission(PERMISSIONS.ATTENDANCE_MARK)},async(request:any)=>{const{date,records}=request.body??{};const schoolId=getTenantContext()?.schoolId;if(!schoolId)throw new Error('Tenant context missing');const ops=(records||[]).map((r:any)=>({updateOne:{filter:{schoolId,date:new Date(date),personType:r.personType,personId:r.personId},update:{$set:{...r,date:new Date(date),markedBy:request.auth.sub,updatedAt:new Date()},$setOnInsert:{schoolId,createdAt:new Date(),deletedAt:null}},upsert:true}}));const result=await FacultyAttendance.bulkWrite(ops);return{success:true,data:{upserted:result.upsertedCount,modified:result.modifiedCount}}});
}
