import { Types } from 'mongoose';
import { AppError,forbidden } from '../../core/errors.js';
import { AcademicClass,AcademicSession,Section,Subject,TeacherSubjectMap } from '../academics/models.js';
import { Student,Teacher } from '../people/models.js';

const studentStatuses=new Set(['PRESENT','ABSENT','LATE','LEAVE']);
export const validObjectId=(value:any)=>Types.ObjectId.isValid(String(value||''));
export function attendanceDate(value:any){const raw=String(value||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(raw))throw new AppError(400,'INVALID_DATE','Attendance date must use YYYY-MM-DD');const date=new Date(`${raw}T00:00:00.000Z`);if(Number.isNaN(date.getTime()))throw new AppError(400,'INVALID_DATE','Attendance date is invalid');return date}
export function boundedRemark(value:any){const text=String(value??'').trim();return text?text.slice(0,300):undefined}

export async function validateSectionContext(sectionId:any){
 if(!validObjectId(sectionId))throw new AppError(400,'INVALID_SECTION','Valid sectionId is required');const section:any=await Section.findById(sectionId).select('_id classId name').lean();if(!section)throw new AppError(404,'SECTION_NOT_FOUND','Section not found');const klass=await AcademicClass.findById(section.classId).select('_id name').lean();if(!klass)throw new AppError(404,'CLASS_NOT_FOUND','Class not found');return{section,klass};
}
export async function assertAttendanceMarkerScope(request:any,sectionId:any,subjectId?:any){
 if(request.auth?.role!=='TEACHER')return;const teacherId=request.auth?.profileId;if(!teacherId)throw forbidden('Teacher profile is not linked');if(subjectId){if(!validObjectId(subjectId))throw new AppError(400,'INVALID_SUBJECT','Valid subjectId is required');const assigned=await TeacherSubjectMap.findOne({teacherId,sectionId,subjectId}).select('_id classId').lean();if(!assigned)throw forbidden('You are not assigned to this subject and section');return}
 const teacher:any=await Teacher.findById(teacherId).select('classTeacherOf').lean();if(!teacher||String(teacher.classTeacherOf||'')!==String(sectionId))throw forbidden('Daily attendance without a subject is limited to the class teacher');
}
export async function validateAttendanceBatch(request:any,body:any){
 const{date,sessionId,sectionId,subjectId,period,records}=body??{};if(!validObjectId(sessionId))throw new AppError(400,'INVALID_SESSION','Valid sessionId is required');const session=await AcademicSession.findById(sessionId).select('_id name').lean();if(!session)throw new AppError(404,'SESSION_NOT_FOUND','Academic session not found');const{section,klass}=await validateSectionContext(sectionId);let subject:any=null;if(subjectId){if(!validObjectId(subjectId))throw new AppError(400,'INVALID_SUBJECT','Valid subjectId is required');subject=await Subject.findById(subjectId).select('_id name').lean();if(!subject)throw new AppError(404,'SUBJECT_NOT_FOUND','Subject not found');if(!Number.isInteger(Number(period))||Number(period)<1||Number(period)>30)throw new AppError(400,'INVALID_PERIOD','Period is required for subject attendance')}else if(period!==undefined&&period!==null&&period!=='')throw new AppError(400,'INVALID_PERIOD','Period is only valid with a subject');await assertAttendanceMarkerScope(request,sectionId,subjectId);if(!Array.isArray(records)||!records.length||records.length>250)throw new AppError(400,'INVALID_INPUT','1 to 250 attendance records are required');const ids=records.map((row:any)=>String(row?.studentId||''));if(ids.some(id=>!validObjectId(id)))throw new AppError(400,'INVALID_STUDENT','One or more student IDs are invalid');if(new Set(ids).size!==ids.length)throw new AppError(400,'DUPLICATE_STUDENT','Attendance payload contains duplicate students');for(const row of records)if(!studentStatuses.has(String(row?.status||'')))throw new AppError(400,'INVALID_STATUS','Attendance status must be PRESENT, ABSENT, LATE or LEAVE');const students=await Student.find({_id:{$in:ids},classId:klass._id,sectionId:section._id,lifecycle:'ACTIVE'}).select('_id').lean();if(students.length!==ids.length)throw new AppError(409,'ROSTER_MISMATCH','One or more students are not active members of the selected section');return{date:attendanceDate(date),sessionId:session._id,classId:klass._id,sectionId:section._id,subjectId:subject?subject._id:undefined,period:subject?Number(period):undefined,records:records.map((row:any)=>({studentId:new Types.ObjectId(String(row.studentId)),status:String(row.status),remark:boundedRemark(row.remark)}))};
}
