import Fastify from 'fastify';
import { randomUUID } from 'node:crypto';
import cookie from '@fastify/cookie';import cors from '@fastify/cors';import helmet from '@fastify/helmet';import rateLimit from '@fastify/rate-limit';
import { corsOrigins,env } from './config/env.js';import { AppError } from './core/errors.js';import { authenticate } from './core/security.js';import { enterTenantContext } from './core/tenant-context.js';import { enforceSchoolAccess } from './modules/tenancy/module-access.js';
import { identityRoutes } from './modules/identity/routes.js';import { tenancyRoutes } from './modules/tenancy/routes.js';import { peopleRoutes } from './modules/people/routes.js';import { academicsRoutes } from './modules/academics/routes.js';import { admissionsRoutes } from './modules/admissions/routes.js';import { timetableRoutes } from './modules/timetable/routes.js';import { attendanceRoutes } from './modules/attendance/routes.js';import { assignmentRoutes } from './modules/assignments/routes.js';import { examinationRoutes } from './modules/examinations/routes.js';import { reportCardRoutes } from './modules/report-cards/routes.js';import { feeRoutes } from './modules/fees/routes.js';import { libraryRoutes } from './modules/library/routes.js';import { payrollRoutes } from './modules/payroll/routes.js';import { leaveRoutes } from './modules/leaves/routes.js';import { communicationRoutes } from './modules/communication/routes.js';import { documentRoutes } from './modules/documents/routes.js';import { importRoutes } from './modules/imports/routes.js';import { notificationRoutes } from './modules/notifications/routes.js';import { analyticsRoutes } from './modules/analytics/routes.js';import { auditRoutes } from './modules/audit/routes.js';import { biometricRoutes } from './modules/biometric/routes.js';import { oasesRoutes } from './modules/oases/routes.js';import { customFormRoutes } from './modules/custom-forms/routes.js';import { settingsRoutes } from './modules/settings/routes.js';import { dashboardRoutes } from './modules/dashboard/routes.js';import { fileRoutes,internalFileRoutes } from './modules/files/routes.js';

const safeMethods=new Set(['GET','HEAD','OPTIONS']);
const publicPrefixes=['/api/health','/api/auth/','/api/platform/','/api/internal/','/api/webhooks/','/api/documents/verify/','/api/public/forms/','/api/device/biometric/'];
function enforceCookieOrigin(request:any){if(safeMethods.has(request.method))return;const bearer=String(request.headers.authorization||'').startsWith('Bearer '),cookieAuth=Boolean(request.cookies?.access_token||request.cookies?.refresh_token);if(!cookieAuth||bearer)return;const origin=String(request.headers.origin||'');if(!origin||!corsOrigins.includes(origin))throw new AppError(403,'ORIGIN_DENIED','Cookie-authenticated mutations require an allowed browser origin')}
function isPublicRoute(url:string){return publicPrefixes.some(prefix=>url.startsWith(prefix))}

export async function buildApp(){const app=Fastify({logger:{level:env.NODE_ENV==='production'?'info':'debug'},trustProxy:true,bodyLimit:2*1024*1024,genReqId:()=>randomUUID()});await app.register(cookie);await app.register(helmet,{contentSecurityPolicy:false});await app.register(rateLimit,{max:200,timeWindow:'1 minute'});await app.register(cors,{origin:(origin,cb)=>{if(!origin||corsOrigins.includes(origin))cb(null,true);else cb(new Error('Origin not allowed'),false)},credentials:true});app.get('/api/health',async()=>({success:true,data:{status:'ok',service:'erp-api',time:new Date().toISOString()}}));app.addHook('preHandler',async(request)=>{enforceCookieOrigin(request);if(isPublicRoute(request.url))return;await authenticate(request);if(request.auth?.type!=='school'||!request.auth.schoolId)throw new AppError(403,'TENANT_REQUIRED','School session required');enterTenantContext({schoolId:request.auth.schoolId,userId:request.auth.sub,requestId:request.id});if(request.auth.mustChangePassword&&!request.url.startsWith('/api/account/change-password'))throw new AppError(428,'PASSWORD_CHANGE_REQUIRED','Password must be changed before continuing');await enforceSchoolAccess(request)});await identityRoutes(app);await tenancyRoutes(app);await internalFileRoutes(app);await fileRoutes(app);await peopleRoutes(app);await academicsRoutes(app);await admissionsRoutes(app);await timetableRoutes(app);await attendanceRoutes(app);await assignmentRoutes(app);await examinationRoutes(app);await reportCardRoutes(app);await feeRoutes(app);await libraryRoutes(app);await payrollRoutes(app);await leaveRoutes(app);await communicationRoutes(app);await documentRoutes(app);await importRoutes(app);await notificationRoutes(app);await analyticsRoutes(app);await auditRoutes(app);await biometricRoutes(app);await oasesRoutes(app);await customFormRoutes(app);await settingsRoutes(app);await dashboardRoutes(app);app.setNotFoundHandler((_request,reply)=>reply.code(404).send({success:false,error:{code:'ROUTE_NOT_FOUND',message:'Route not found'}}));app.setErrorHandler((error:any,request,reply)=>{request.log.error({err:error,requestId:request.id},'request failed');if(error instanceof AppError)return reply.code(error.statusCode).send({success:false,error:{code:error.code,message:error.message,details:error.details}});if(error?.code===11000)return reply.code(409).send({success:false,error:{code:'DUPLICATE',message:'A unique value already exists',details:error.keyValue}});return reply.code(500).send({success:false,error:{code:'INTERNAL_ERROR',message:env.NODE_ENV==='production'?'Unexpected server error':error.message}})});return app;}
