import type { FastifyInstance } from 'fastify';
import { Types } from 'mongoose';
import { PERMISSIONS,SCHOOL_ROLES } from '@erp/contracts';
import { requirePermission } from '../../core/security.js';
import { AppError } from '../../core/errors.js';
import { getTenantContext } from '../../core/tenant-context.js';
import { enqueueEmail } from '../../core/queue.js';
import { writeAudit } from '../../core/audit.js';
import { Notification,NotificationPreference } from './models.js';
import { User } from '../identity/models.js';

const validId=(value:any)=>Types.ObjectId.isValid(String(value||''));
const clean=(value:any,max=5000)=>String(value??'').trim().slice(0,max);
function safeLink(value:any){const link=clean(value,1000);if(!link)return undefined;if(link.startsWith('/')||/^https:\/\//i.test(link))return link;throw new AppError(400,'INVALID_LINK','Notification link must be an internal path or https URL')}

export async function notificationRoutes(app:FastifyInstance){
 app.get('/api/notifications',async(request:any)=>{const limit=Math.min(200,Math.max(1,Number(request.query?.limit||100))),filter:any={userId:request.auth.sub};if(String(request.query?.unreadOnly||'')==='true')filter.readAt=null;return{success:true,data:await Notification.find(filter).sort({createdAt:-1}).limit(limit).lean()}});
 app.get('/api/notifications/unread-count',async(request:any)=>({success:true,data:{count:await Notification.countDocuments({userId:request.auth.sub,readAt:null})}}));
 app.get('/api/notifications/preferences',async(request:any)=>{const item=await NotificationPreference.findOne({userId:request.auth.sub}).lean();return{success:true,data:item||{userId:request.auth.sub,inApp:true,email:true,mutedTypes:[]}}});
 app.patch('/api/notifications/preferences',async(request:any)=>{const muted=request.body?.mutedTypes;if(muted!==undefined&&(!Array.isArray(muted)||muted.length>50))throw new AppError(400,'INVALID_MUTED_TYPES','mutedTypes must contain at most 50 values');const update:any={updatedAt:new Date()};if(typeof request.body?.inApp==='boolean')update.inApp=request.body.inApp;if(typeof request.body?.email==='boolean')update.email=request.body.email;if(muted!==undefined)update.mutedTypes=[...new Set(muted.map((value:any)=>clean(value,80)).filter(Boolean))];const item=await NotificationPreference.findOneAndUpdate({userId:request.auth.sub},{$set:update,$setOnInsert:{userId:request.auth.sub}},{new:true,upsert:true,setDefaultsOnInsert:true});return{success:true,data:item}});
 app.post('/api/notifications/send',{preHandler:requirePermission(PERMISSIONS.NOTIFICATION_SEND)},async(request:any)=>{const title=clean(request.body?.title,180),body=clean(request.body?.body,5000),type=clean(request.body?.type,80)||'INFO',link=safeLink(request.body?.link);if(!title||!body)throw new AppError(400,'INVALID_NOTIFICATION','Notification title and body are required');const rawIds=Array.isArray(request.body?.userIds)?request.body.userIds:[],rawRoles=Array.isArray(request.body?.roles)?request.body.roles:[];if(rawIds.length>1000||rawRoles.length>SCHOOL_ROLES.length)throw new AppError(400,'TOO_MANY_RECIPIENTS','Recipient selection is too large');if(rawIds.some((id:any)=>!validId(id)))throw new AppError(400,'INVALID_RECIPIENT','One or more user IDs are invalid');const roles=[...new Set(rawRoles.map(String))];if(roles.some(role=>!(SCHOOL_ROLES as readonly string[]).includes(role)))throw new AppError(400,'INVALID_ROLE','One or more recipient roles are invalid');if(!rawIds.length&&!roles.length)throw new AppError(400,'RECIPIENT_REQUIRED','Choose userIds or roles');const filter:any={isActive:true,$or:[]};if(rawIds.length)filter.$or.push({_id:{$in:rawIds}});if(roles.length)filter.$or.push({role:{$in:roles}});const users:any[]=await User.find(filter).select('_id email firstName').limit(1000).lean();if(!users.length)throw new AppError(404,'RECIPIENT_NOT_FOUND','No active recipients matched');const ids=users.map(user=>user._id),prefs:any[]=await NotificationPreference.find({userId:{$in:ids}}).lean(),prefMap=new Map(prefs.map(pref=>[String(pref.userId),pref])),schoolId=getTenantContext()?.schoolId;if(!schoolId)throw new AppError(403,'TENANT_REQUIRED','School context required');const inAppDocs:any[]=[],emailJobs:Promise<unknown>[]=[];for(const user of users){const pref=prefMap.get(String(user._id)),muted=new Set<string>(pref?.mutedTypes||[]);if(muted.has(type))continue;if(pref?.inApp!==false)inAppDocs.push({schoolId,deletedAt:null,userId:user._id,title,body,type,link});if(pref?.email!==false&&user.email)emailJobs.push(enqueueEmail({to:user.email,subject:title,text:`${body}${link?`\n\nOpen: ${link}`:''}`,tags:{kind:'erp-notification',type,schoolId:String(schoolId)}}))}const inserted=inAppDocs.length?await Notification.insertMany(inAppDocs):[];const emailResults=await Promise.allSettled(emailJobs);const emailQueued=emailResults.filter(result=>result.status==='fulfilled').length,emailFailed=emailResults.length-emailQueued;await writeAudit({action:'notification.send',entity:'notification',after:{requestedUsers:users.length,inApp:inserted.length,emailQueued,emailFailed,type},ip:request.ip});return{success:true,data:{recipients:users.length,inApp:inserted.length,emailQueued,emailFailed}}});
 app.post('/api/notifications/read-all',async(request:any)=>{const result=await Notification.updateMany({userId:request.auth.sub,readAt:null},{$set:{readAt:new Date()}});return{success:true,data:{marked:result.modifiedCount}}});
 app.post('/api/notifications/:id/read',async(request:any)=>{const item=await Notification.findOneAndUpdate({_id:request.params.id,userId:request.auth.sub},{$set:{readAt:new Date()}},{new:true});if(!item)throw new AppError(404,'NOT_FOUND','Notification not found');return{success:true,data:item}});
}
