import type { FastifyInstance } from 'fastify';
import { Types } from 'mongoose';
import { PERMISSIONS } from '@erp/contracts';
import { requirePermission } from '../../core/security.js';
import { AppError,forbidden } from '../../core/errors.js';
import { writeAudit } from '../../core/audit.js';
import { LeaveRequest } from './models.js';
import { Student,Teacher,Staff } from '../people/models.js';

const validId=(value:any)=>Types.ObjectId.isValid(String(value||''));
function parseDate(value:any,label:string){const raw=String(value||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(raw))throw new AppError(400,'INVALID_DATE',`${label} must use YYYY-MM-DD`);const date=new Date(`${raw}T00:00:00.000Z`);if(Number.isNaN(date.getTime()))throw new AppError(400,'INVALID_DATE',`${label} is invalid`);return date}
function validateRange(fromDate:Date,toDate:Date){if(fromDate>toDate)throw new AppError(400,'INVALID_RANGE','Leave end date must be on or after the start date');if(toDate.getTime()-fromDate.getTime()>366*86400000)throw new AppError(400,'LEAVE_TOO_LONG','A single leave request cannot exceed 366 days')}
const clean=(value:any,max=1000)=>String(value??'').trim().slice(0,max);
function actorScope(request:any){const role=request.auth?.role,profileId=request.auth?.profileId;if(role==='STUDENT')return profileId&&validId(profileId)?{applicantType:'STUDENT',applicantId:new Types.ObjectId(String(profileId))}:{_id:{$in:[]}};if(role==='TEACHER')return profileId&&validId(profileId)?{applicantType:'TEACHER',applicantId:new Types.ObjectId(String(profileId))}:{_id:{$in:[]}};if(['SCHOOL_ADMIN','HR_MANAGER'].includes(role))return{};return{_id:{$in:[]}}}
async function resolveApplicant(request:any,body:any){const role=request.auth?.role,profileId=request.auth?.profileId;if(role==='STUDENT'||role==='TEACHER'){if(!profileId||!validId(profileId))throw forbidden('Your profile is not linked');return{applicantType:role,applicantId:new Types.ObjectId(String(profileId))}}if(!['SCHOOL_ADMIN','HR_MANAGER'].includes(role))throw forbidden('This role cannot create leave requests');const type=String(body?.applicantType||'');const id=body?.applicantId;if(!['STUDENT','TEACHER','STAFF'].includes(type)||!validId(id))throw new AppError(400,'INVALID_APPLICANT','A valid student, teacher or staff applicant is required');const Model:any=type==='STUDENT'?Student:type==='TEACHER'?Teacher:Staff;if(!await Model.findById(id).select('_id').lean())throw new AppError(404,'APPLICANT_NOT_FOUND','Applicant does not exist in this school');return{applicantType:type,applicantId:new Types.ObjectId(String(id))}}
async function ensureNoOverlap(applicantType:string,applicantId:any,fromDate:Date,toDate:Date,excludeId?:string){const filter:any={applicantType,applicantId,status:{$in:['PENDING','APPROVED']},fromDate:{$lte:toDate},toDate:{$gte:fromDate}};if(excludeId)filter._id={$ne:excludeId};if(await LeaveRequest.exists(filter))throw new AppError(409,'LEAVE_OVERLAP','An overlapping pending or approved leave request already exists')}

export async function leaveRoutes(app:FastifyInstance){
 app.get('/api/leaves',{preHandler:requirePermission(PERMISSIONS.LEAVE_READ)},async(request:any)=>{const filter:any={...actorScope(request)};if(request.query?.status){const status=String(request.query.status);if(!['PENDING','APPROVED','REJECTED','CANCELLED'].includes(status))throw new AppError(400,'INVALID_STATUS','Invalid leave status');filter.status=status}const page=Math.max(1,Number(request.query?.page||1)),limit=Math.min(100,Math.max(1,Number(request.query?.limit||50)));const[data,total]=await Promise.all([LeaveRequest.find(filter).sort({fromDate:-1,createdAt:-1}).skip((page-1)*limit).limit(limit).lean(),LeaveRequest.countDocuments(filter)]);return{success:true,data,meta:{page,limit,total}}});
 app.get('/api/leaves/:id',{preHandler:requirePermission(PERMISSIONS.LEAVE_READ)},async(request:any)=>{const item=await LeaveRequest.findOne({...actorScope(request),_id:request.params.id}).lean();if(!item)throw new AppError(404,'NOT_FOUND','Leave request not found');return{success:true,data:item}});
 app.post('/api/leaves',{preHandler:requirePermission(PERMISSIONS.LEAVE_READ)},async(request:any)=>{const reason=clean(request.body?.reason);if(reason.length<3)throw new AppError(400,'INVALID_REASON','Leave reason must contain at least 3 characters');const fromDate=parseDate(request.body?.fromDate,'fromDate'),toDate=parseDate(request.body?.toDate,'toDate');validateRange(fromDate,toDate);const applicant=await resolveApplicant(request,request.body);await ensureNoOverlap(applicant.applicantType,applicant.applicantId,fromDate,toDate);const item=await LeaveRequest.create({...applicant,fromDate,toDate,reason,status:'PENDING'});await writeAudit({action:'leave.create',entity:'leave',entityId:String(item._id),after:{applicantType:item.applicantType,applicantId:String(item.applicantId),fromDate,toDate,status:item.status},ip:request.ip});return{success:true,data:item}});
 app.patch('/api/leaves/:id',{preHandler:requirePermission(PERMISSIONS.LEAVE_READ)},async(request:any)=>{const scope=actorScope(request),item:any=await LeaveRequest.findOne({...scope,_id:request.params.id});if(!item)throw new AppError(404,'NOT_FOUND','Leave request not found');if(item.status!=='PENDING')throw new AppError(409,'LEAVE_LOCKED','Only pending leave requests can be edited');const fromDate=request.body?.fromDate?parseDate(request.body.fromDate,'fromDate'):item.fromDate,toDate=request.body?.toDate?parseDate(request.body.toDate,'toDate'):item.toDate;validateRange(fromDate,toDate);const reason=request.body?.reason!==undefined?clean(request.body.reason):item.reason;if(String(reason).length<3)throw new AppError(400,'INVALID_REASON','Leave reason must contain at least 3 characters');await ensureNoOverlap(item.applicantType,item.applicantId,fromDate,toDate,String(item._id));const before={fromDate:item.fromDate,toDate:item.toDate,reason:item.reason};item.fromDate=fromDate;item.toDate=toDate;item.reason=reason;item.updatedAt=new Date();await item.save();await writeAudit({action:'leave.update',entity:'leave',entityId:String(item._id),before,after:{fromDate,toDate,reason},ip:request.ip});return{success:true,data:item}});
 app.post('/api/leaves/:id/cancel',{preHandler:requirePermission(PERMISSIONS.LEAVE_READ)},async(request:any)=>{const item:any=await LeaveRequest.findOne({...actorScope(request),_id:request.params.id});if(!item)throw new AppError(404,'NOT_FOUND','Leave request not found');if(item.status!=='PENDING')throw new AppError(409,'LEAVE_LOCKED','Only pending leave requests can be cancelled');item.status='CANCELLED';item.updatedAt=new Date();await item.save();await writeAudit({action:'leave.cancel',entity:'leave',entityId:String(item._id),before:{status:'PENDING'},after:{status:'CANCELLED'},ip:request.ip});return{success:true,data:item}});
 app.post('/api/leaves/:id/decision',{preHandler:requirePermission(PERMISSIONS.LEAVE_APPROVE)},async(request:any)=>{const status=String(request.body?.status||'');if(!['APPROVED','REJECTED'].includes(status))throw new AppError(400,'INVALID_STATUS','Use APPROVED or REJECTED');const item:any=await LeaveRequest.findById(request.params.id);if(!item)throw new AppError(404,'NOT_FOUND','Leave request not found');if(item.status!=='PENDING')throw new AppError(409,'LEAVE_LOCKED','Only pending leave requests can be decided');const before={status:item.status};item.status=status;item.approverId=request.auth.sub;item.decisionNote=clean(request.body?.note);item.decidedAt=new Date();item.updatedAt=new Date();await item.save();await writeAudit({action:'leave.decision',entity:'leave',entityId:String(item._id),before,after:{status,decisionNote:item.decisionNote},ip:request.ip});return{success:true,data:item}});
}
