import type { FastifyInstance } from 'fastify';
import { Types } from 'mongoose';
import { PERMISSIONS } from '@erp/contracts';
import { registerCrud } from '../../core/crud.js';
import { requirePermission } from '../../core/security.js';
import { AppError,forbidden } from '../../core/errors.js';
import { writeAudit } from '../../core/audit.js';
import { Notice,Grievance,ChatMessage,KnowledgeResource } from './models.js';
import { User } from '../identity/models.js';

const validId=(value:any)=>Types.ObjectId.isValid(String(value||''));
const clean=(value:any,max=10000)=>String(value??'').trim().slice(0,max);
const has=(request:any,permission:string)=>request.auth?.type==='platform'||new Set(request.auth?.permissions||[]).has(permission);
function sendGuard(request:any){if(has(request,PERMISSIONS.COMMUNICATION_SEND)||has(request,PERMISSIONS.COMMUNICATION_READ))return;throw forbidden('Communication send permission required')}
function audienceScope(request:any){if(has(request,PERMISSIONS.COMMUNICATION_WRITE))return{};const role=String(request.auth?.role||''),now=new Date();return{$and:[{status:'PUBLISHED'},{$or:[{publishAt:{$exists:false}},{publishAt:null},{publishAt:{$lte:now}}]},{$or:[{expiresAt:{$exists:false}},{expiresAt:null},{expiresAt:{$gt:now}}]},{$or:[{audience:{$size:0}},{audience:'ALL'},{audience:role}]}]}}
function knowledgeScope(request:any){if(has(request,PERMISSIONS.COMMUNICATION_WRITE))return{};const role=String(request.auth?.role||'');return{$or:[{audience:{$size:0}},{audience:'ALL'},{audience:role}]}}
function sanitizeAudience(value:any){if(value===undefined)return[];if(!Array.isArray(value)||value.length>20)throw new AppError(400,'INVALID_AUDIENCE','Audience must be a bounded list');return[...new Set(value.map((x:any)=>clean(x,50)).filter(Boolean))]}
function sanitizeAttachments(value:any){if(value===undefined)return[];if(!Array.isArray(value)||value.length>10)throw new AppError(400,'INVALID_ATTACHMENTS','At most 10 attachments are allowed');return value.map((x:any)=>clean(x,200)).filter(Boolean)}
function noticeData(request:any,current:any={}){const body=request.body??{},title=body.title===undefined?current.title:clean(body.title,180),text=body.body===undefined?current.body:clean(body.body,10000);if(!title||!text)throw new AppError(400,'INVALID_NOTICE','Notice title and body are required');const status=body.status===undefined?(current.status||'DRAFT'):String(body.status);if(!['DRAFT','PUBLISHED','ARCHIVED'].includes(status))throw new AppError(400,'INVALID_STATUS','Invalid notice status');let publishAt=body.publishAt===undefined?current.publishAt:(body.publishAt?new Date(body.publishAt):undefined),expiresAt=body.expiresAt===undefined?current.expiresAt:(body.expiresAt?new Date(body.expiresAt):undefined);if(publishAt&&Number.isNaN(publishAt.getTime()))throw new AppError(400,'INVALID_DATE','publishAt is invalid');if(expiresAt&&Number.isNaN(expiresAt.getTime()))throw new AppError(400,'INVALID_DATE','expiresAt is invalid');if(status==='PUBLISHED'&&!publishAt)publishAt=new Date();if(publishAt&&expiresAt&&expiresAt<=publishAt)throw new AppError(400,'INVALID_DATE_RANGE','Notice expiry must be after publish time');return{title,body:text,audience:body.audience===undefined?(current.audience||[]):sanitizeAudience(body.audience),attachments:body.attachments===undefined?(current.attachments||[]):sanitizeAttachments(body.attachments),publishAt,expiresAt,status,createdBy:current.createdBy||request.auth.sub,updatedAt:new Date()}}
function knowledgeData(request:any,current:any={}){const body=request.body??{},title=body.title===undefined?current.title:clean(body.title,180);if(!title)throw new AppError(400,'INVALID_RESOURCE','Resource title is required');const url=body.url===undefined?current.url:clean(body.url,1500);if(url&&!/^https?:\/\//i.test(url))throw new AppError(400,'INVALID_URL','Knowledge URL must use http or https');return{title,description:body.description===undefined?current.description:clean(body.description,10000),url:url||undefined,attachments:body.attachments===undefined?(current.attachments||[]):sanitizeAttachments(body.attachments),audience:body.audience===undefined?(current.audience||[]):sanitizeAudience(body.audience),subjectId:body.subjectId===undefined?current.subjectId:body.subjectId||undefined,createdBy:current.createdBy||request.auth.sub,updatedAt:new Date()}}

export async function communicationRoutes(app:FastifyInstance){
 await registerCrud(app,{prefix:'/api/notices',model:Notice,entity:'notice',readPermission:PERMISSIONS.COMMUNICATION_READ,writePermission:PERMISSIONS.COMMUNICATION_WRITE,searchable:['title','body'],readScope:audienceScope,prepareCreate:(request:any)=>noticeData(request),prepareUpdate:async(request:any)=>{const current=await Notice.findById(request.params.id).lean();if(!current)throw new AppError(404,'NOT_FOUND','Notice not found');return noticeData(request,current)}});
 await registerCrud(app,{prefix:'/api/knowledge',model:KnowledgeResource,entity:'knowledge-resource',readPermission:PERMISSIONS.COMMUNICATION_READ,writePermission:PERMISSIONS.COMMUNICATION_WRITE,searchable:['title','description'],readScope:knowledgeScope,prepareCreate:(request:any)=>knowledgeData(request),prepareUpdate:async(request:any)=>{const current=await KnowledgeResource.findById(request.params.id).lean();if(!current)throw new AppError(404,'NOT_FOUND','Knowledge resource not found');return knowledgeData(request,current)}});
 app.get('/api/grievances',{preHandler:requirePermission(PERMISSIONS.COMMUNICATION_READ)},async(request:any)=>{const filter:any=has(request,PERMISSIONS.COMMUNICATION_WRITE)?{}:{createdBy:request.auth.sub};if(request.query?.status){const status=String(request.query.status);if(!['OPEN','IN_PROGRESS','RESOLVED','CLOSED'].includes(status))throw new AppError(400,'INVALID_STATUS','Invalid grievance status');filter.status=status}return{success:true,data:await Grievance.find(filter).sort({createdAt:-1}).limit(300).lean()}});
 app.post('/api/grievances',{preHandler:async(request:any)=>sendGuard(request)},async(request:any)=>{const subject=clean(request.body?.subject,180),description=clean(request.body?.description,10000);if(!subject||!description)throw new AppError(400,'INVALID_GRIEVANCE','Subject and description are required');const priority=['LOW','MEDIUM','HIGH'].includes(request.body?.priority)?request.body.priority:'MEDIUM';const item=await Grievance.create({category:clean(request.body?.category,80),subject,description,priority,createdBy:request.auth.sub,status:'OPEN'});await writeAudit({action:'grievance.create',entity:'grievance',entityId:String(item._id),after:{subject:item.subject,priority:item.priority,status:item.status},ip:request.ip});return{success:true,data:item}});
 app.patch('/api/grievances/:id',{preHandler:async(request:any)=>sendGuard(request)},async(request:any)=>{const item:any=await Grievance.findOne({_id:request.params.id,createdBy:request.auth.sub});if(!item)throw new AppError(404,'NOT_FOUND','Grievance not found');if(item.status!=='OPEN')throw new AppError(409,'GRIEVANCE_LOCKED','Only open grievances can be edited by their creator');const before={subject:item.subject,description:item.description,category:item.category};if(request.body?.subject!==undefined)item.subject=clean(request.body.subject,180);if(request.body?.description!==undefined)item.description=clean(request.body.description,10000);if(request.body?.category!==undefined)item.category=clean(request.body.category,80);if(!item.subject||!item.description)throw new AppError(400,'INVALID_GRIEVANCE','Subject and description are required');item.updatedAt=new Date();await item.save();await writeAudit({action:'grievance.update',entity:'grievance',entityId:String(item._id),before,after:{subject:item.subject,description:item.description,category:item.category},ip:request.ip});return{success:true,data:item}});
 app.post('/api/grievances/:id/manage',{preHandler:requirePermission(PERMISSIONS.COMMUNICATION_WRITE)},async(request:any)=>{const item:any=await Grievance.findById(request.params.id);if(!item)throw new AppError(404,'NOT_FOUND','Grievance not found');const status=request.body?.status===undefined?item.status:String(request.body.status);if(!['OPEN','IN_PROGRESS','RESOLVED','CLOSED'].includes(status))throw new AppError(400,'INVALID_STATUS','Invalid grievance status');if(item.status==='CLOSED'&&status!=='CLOSED')throw new AppError(409,'GRIEVANCE_CLOSED','Closed grievances cannot be reopened');let assignedTo=item.assignedTo;if(request.body?.assignedTo!==undefined){if(request.body.assignedTo){if(!validId(request.body.assignedTo)||!await User.findById(request.body.assignedTo).select('_id').lean())throw new AppError(404,'ASSIGNEE_NOT_FOUND','Assigned user not found');assignedTo=request.body.assignedTo}else assignedTo=undefined}const before={status:item.status,assignedTo:item.assignedTo,resolution:item.resolution};item.status=status;item.assignedTo=assignedTo;item.resolution=request.body?.resolution===undefined?item.resolution:clean(request.body.resolution,10000);item.updatedAt=new Date();await item.save();await writeAudit({action:'grievance.manage',entity:'grievance',entityId:String(item._id),before,after:{status:item.status,assignedTo:item.assignedTo,resolution:item.resolution},ip:request.ip});return{success:true,data:item}});
 app.get('/api/chat/contacts',{preHandler:async(request:any)=>sendGuard(request)},async(request:any)=>({success:true,data:await User.find({_id:{$ne:request.auth.sub},isActive:true}).select('firstName lastName role profileType').sort({firstName:1,lastName:1}).limit(500).lean()}));
 app.get('/api/chat-messages',{preHandler:requirePermission(PERMISSIONS.COMMUNICATION_READ)},async(request:any)=>{const me=new Types.ObjectId(String(request.auth.sub)),filter:any={$or:[{senderId:me},{recipientId:me}]};if(request.query?.recipientId){if(!validId(request.query.recipientId))throw new AppError(400,'INVALID_RECIPIENT','Invalid recipient');const other=new Types.ObjectId(String(request.query.recipientId));filter.$and=[{$or:[{senderId:me,recipientId:other},{senderId:other,recipientId:me}]}];delete filter.$or}const before=request.query?.before?new Date(String(request.query.before)):undefined;if(before&&!Number.isNaN(before.getTime()))filter.createdAt={$lt:before};return{success:true,data:await ChatMessage.find(filter).sort({createdAt:-1}).limit(100).lean()}});
 app.post('/api/chat-messages',{preHandler:async(request:any)=>sendGuard(request)},async(request:any)=>{const recipientId=request.body?.recipientId;if(!validId(recipientId)||String(recipientId)===String(request.auth.sub))throw new AppError(400,'INVALID_RECIPIENT','Choose another valid school user');const recipient=await User.findOne({_id:recipientId,isActive:true}).select('_id').lean();if(!recipient)throw new AppError(404,'RECIPIENT_NOT_FOUND','Recipient not found');const body=clean(request.body?.body,4000);if(!body)throw new AppError(400,'EMPTY_MESSAGE','Message body is required');const ids=[String(request.auth.sub),String(recipient._id)].sort(),item=await ChatMessage.create({threadKey:`dm:${ids[0]}:${ids[1]}`,senderId:request.auth.sub,recipientId:recipient._id,body,attachments:sanitizeAttachments(request.body?.attachments)});return{success:true,data:item}});
 app.post('/api/chat-messages/read',{preHandler:requirePermission(PERMISSIONS.COMMUNICATION_READ)},async(request:any)=>{const senderId=request.body?.senderId;if(!validId(senderId))throw new AppError(400,'INVALID_SENDER','Valid senderId is required');const result=await ChatMessage.updateMany({senderId,recipientId:request.auth.sub,readAt:null},{$set:{readAt:new Date()}});return{success:true,data:{marked:result.modifiedCount}}});
}
