import { AppError } from '../../core/errors.js';
import { TeacherSubjectMap } from '../academics/models.js';
import { Student } from '../people/models.js';
import { accessibleStudentIds } from '../people/access.js';

export async function examReadScope(request:any){const role=request.auth?.role;if(role==='TEACHER'){const teacherId=request.auth?.profileId;if(!teacherId)return{_id:{$in:[]}};const maps:any[]=await TeacherSubjectMap.find({teacherId}).select('classId sectionId subjectId').lean();const conditions=maps.map(map=>({classId:map.classId,sectionIds:map.sectionId,'subjectConfigs.subjectId':map.subjectId,status:{$in:['MARKS_ENTRY','LOCKED','PUBLISHED']}}));return conditions.length?{$or:conditions}:{_id:{$in:[]}}}if(['STUDENT','PARENT'].includes(role)){const ids=await accessibleStudentIds(request);if(!ids?.length)return{_id:{$in:[]}};const students:any[]=await Student.find({_id:{$in:ids}}).select('classId sectionId').lean();const conditions=students.filter(student=>student.classId&&student.sectionId).map(student=>({classId:student.classId,sectionIds:student.sectionId,status:'PUBLISHED'}));return conditions.length?{$or:conditions}:{_id:{$in:[]}}}return{}}
export async function markReadScope(request:any){const role=request.auth?.role;if(role==='TEACHER'){const teacherId=request.auth?.profileId;if(!teacherId)return{_id:{$in:[]}};const maps:any[]=await TeacherSubjectMap.find({teacherId}).select('classId sectionId subjectId').lean();const conditions:any[]=[];for(const map of maps){const studentIds=await Student.distinct('_id',{classId:map.classId,sectionId:map.sectionId});if(studentIds.length)conditions.push({studentId:{$in:studentIds},subjectId:map.subjectId})}return conditions.length?{$or:conditions}:{_id:{$in:[]}}}const studentIds=await accessibleStudentIds(request);return studentIds===null?{}:{studentId:{$in:studentIds}}}
export async function assertTeacherCanEnterMarks(request:any,records:any[]){if(request.auth?.role!=='TEACHER')return;const teacherId=request.auth?.profileId;if(!teacherId)throw new AppError(403,'TEACHER_PROFILE_REQUIRED','Teacher profile is required');const studentIds=[...new Set(records.map(record=>String(record.studentId)))];const students:any[]=await Student.find({_id:{$in:studentIds}}).select('_id classId sectionId').lean();if(students.length!==studentIds.length)throw new AppError(403,'MARK_SCOPE_DENIED','One or more students are outside your assigned scope');const maps:any[]=await TeacherSubjectMap.find({teacherId}).select('classId sectionId subjectId').lean();const allowed=new Set(maps.map(map=>`${String(map.classId)}:${String(map.sectionId)}:${String(map.subjectId)}`));const byId=new Map(students.map(student=>[String(student._id),student]));for(const record of records){const student=byId.get(String(record.studentId));if(!student||!allowed.has(`${String(student.classId)}:${String(student.sectionId)}:${String(record.subjectId)}`))throw new AppError(403,'MARK_SCOPE_DENIED','Teacher is not assigned to this student section and subject')}}
export async function assertRecordsInExamScope(exam:any,records:any[]){const studentIds=[...new Set(records.map(record=>String(record.studentId)))],students:any[]=await Student.find({_id:{$in:studentIds}}).select('_id classId sectionId lifecycle').lean(),allowedSections=new Set((exam.sectionIds||[]).map(String));if(students.length!==studentIds.length)throw new AppError(404,'STUDENT_NOT_FOUND','One or more students are unavailable');for(const student of students)if(student.lifecycle!=='ACTIVE'||String(student.classId)!==String(exam.classId)||!allowedSections.has(String(student.sectionId)))throw new AppError(403,'EXAM_STUDENT_SCOPE','One or more students are outside this exam class/section scope')}
export function validateSubjectConfigs(configs:any){if(!Array.isArray(configs)||!configs.length||configs.length>100)throw new AppError(400,'SUBJECT_CONFIG_REQUIRED','Exam needs 1 to 100 subject configurations');const seen=new Set<string>();return configs.map(config=>{const subjectId=String(config?.subjectId||'');const maxMarks=Number(config?.maxMarks),passMarks=Number(config?.passMarks??0),weightage=Number(config?.weightage??100);if(!subjectId||seen.has(subjectId))throw new AppError(400,'INVALID_SUBJECT_CONFIG','Exam subjects must be unique and valid');if(!Number.isFinite(maxMarks)||maxMarks<=0||maxMarks>1000||!Number.isFinite(passMarks)||passMarks<0||passMarks>maxMarks)throw new AppError(400,'INVALID_SUBJECT_CONFIG','Invalid maximum or pass marks');if(!Number.isFinite(weightage)||weightage<0||weightage>100)throw new AppError(400,'INVALID_SUBJECT_CONFIG','Weightage must be between 0 and 100');seen.add(subjectId);return{subjectId,maxMarks:Math.round(maxMarks*100)/100,passMarks:Math.round(passMarks*100)/100,weightage:Math.round(weightage*100)/100}})}
export function validateMarkRecord(record:any,config:any){const component=(key:string)=>{const value=record?.[key];if(value===undefined||value===null||value==='')return 0;const number=Number(value);if(!Number.isFinite(number)||number<0)throw new AppError(400,'INVALID_MARKS',`${key} marks must be a non-negative number`);return Math.round(number*100)/100};const theory=component('theory'),practical=component('practical'),internal=component('internal'),total=Math.round((theory+practical+internal)*100)/100;if(total>Number(config.maxMarks))throw new AppError(400,'INVALID_MARKS',`Total marks exceed configured maximum of ${config.maxMarks}`);const percentage=Number(config.maxMarks)?(total/Number(config.maxMarks))*100:0;const grade=total<Number(config.passMarks||0)?'F':percentage>=90?'A+':percentage>=80?'A':percentage>=70?'B+':percentage>=60?'B':percentage>=50?'C':percentage>=40?'D':'E';return{theory,practical,internal,total,grade,remark:String(record?.remark||'').slice(0,1000)}}
