import { AppError } from '../../core/errors.js';
import { TeacherSubjectMap } from '../academics/models.js';
import { Student } from '../people/models.js';
import { accessibleStudentIds } from '../people/access.js';

export function examReadScope(request:any){const role=request.auth?.role;if(['STUDENT','PARENT'].includes(role))return{status:'PUBLISHED'};if(role==='TEACHER')return{status:{$in:['MARKS_ENTRY','LOCKED','PUBLISHED']}};return{}}

export async function markReadScope(request:any){const role=request.auth?.role;if(role==='TEACHER'){const teacherId=request.auth?.profileId;if(!teacherId)return{_id:{$in:[]}};const maps:any[]=await TeacherSubjectMap.find({teacherId}).select('classId sectionId subjectId').lean();const conditions:any[]=[];for(const map of maps){const studentIds=await Student.distinct('_id',{classId:map.classId,sectionId:map.sectionId});if(studentIds.length)conditions.push({studentId:{$in:studentIds},subjectId:map.subjectId})}return conditions.length?{$or:conditions}:{_id:{$in:[]}}}const studentIds=await accessibleStudentIds(request);return studentIds===null?{}:{studentId:{$in:studentIds}}}

export async function assertTeacherCanEnterMarks(request:any,records:any[]){if(request.auth?.role!=='TEACHER')return;const teacherId=request.auth?.profileId;if(!teacherId)throw new AppError(403,'TEACHER_PROFILE_REQUIRED','Teacher profile is required');const studentIds=[...new Set(records.map(record=>String(record.studentId)))];const students:any[]=await Student.find({_id:{$in:studentIds}}).select('_id classId sectionId').lean();if(students.length!==studentIds.length)throw new AppError(403,'MARK_SCOPE_DENIED','One or more students are outside your assigned scope');const maps:any[]=await TeacherSubjectMap.find({teacherId}).select('classId sectionId subjectId').lean();const allowed=new Set(maps.map(map=>`${String(map.classId)}:${String(map.sectionId)}:${String(map.subjectId)}`));const byId=new Map(students.map(student=>[String(student._id),student]));for(const record of records){const student=byId.get(String(record.studentId));if(!student||!allowed.has(`${String(student.classId)}:${String(student.sectionId)}:${String(record.subjectId)}`))throw new AppError(403,'MARK_SCOPE_DENIED','Teacher is not assigned to this student section and subject')}}

export function validateSubjectConfigs(configs:any){if(!Array.isArray(configs)||!configs.length)throw new AppError(400,'SUBJECT_CONFIG_REQUIRED','At least one exam subject configuration is required');const seen=new Set<string>();return configs.map(config=>{const subjectId=String(config?.subjectId||'');const maxMarks=Number(config?.maxMarks),passMarks=Number(config?.passMarks??0),weightage=Number(config?.weightage??100);if(!subjectId||seen.has(subjectId))throw new AppError(400,'INVALID_SUBJECT_CONFIG','Exam subjects must be unique and valid');if(!Number.isFinite(maxMarks)||maxMarks<=0||!Number.isFinite(passMarks)||passMarks<0||passMarks>maxMarks)throw new AppError(400,'INVALID_SUBJECT_CONFIG','Invalid maximum or pass marks');if(!Number.isFinite(weightage)||weightage<0||weightage>100)throw new AppError(400,'INVALID_SUBJECT_CONFIG','Weightage must be between 0 and 100');seen.add(subjectId);return{subjectId,maxMarks,passMarks,weightage}})}

export function validateMarkRecord(record:any,config:any){const component=(key:string)=>{const value=record?.[key];if(value===undefined||value===null||value==='')return 0;const number=Number(value);if(!Number.isFinite(number)||number<0)throw new AppError(400,'INVALID_MARKS',`${key} marks must be a non-negative number`);return number};const theory=component('theory'),practical=component('practical'),internal=component('internal'),total=theory+practical+internal;if(total>Number(config.maxMarks))throw new AppError(400,'INVALID_MARKS',`Total marks exceed configured maximum of ${config.maxMarks}`);const percentage=Number(config.maxMarks)?(total/Number(config.maxMarks))*100:0;const grade=total<Number(config.passMarks||0)?'F':percentage>=90?'A+':percentage>=80?'A':percentage>=70?'B+':percentage>=60?'B':percentage>=50?'C':percentage>=40?'D':'E';return{theory,practical,internal,total,grade,remark:String(record?.remark||'').slice(0,1000)}}
