import type { FastifyInstance } from 'fastify';
import { Types } from 'mongoose';
import { PERMISSIONS } from '@erp/contracts';
import { registerCrud } from '../../core/crud.js';
import { requirePermission } from '../../core/security.js';
import { AppError } from '../../core/errors.js';
import { writeAudit } from '../../core/audit.js';
import { getTenantContext } from '../../core/tenant-context.js';
import { Exam,Mark } from './models.js';
import { assertTeacherCanEnterMarks,examReadScope,markReadScope,validateMarkRecord,validateSubjectConfigs } from './access.js';

function prepareExamCreate(request:any){const body={...(request.body??{})};body.subjectConfigs=validateSubjectConfigs(body.subjectConfigs);body.status='DRAFT';delete body.schoolId;delete body.deletedAt;return body}
function prepareExamUpdate(request:any){const body={...(request.body??{})};if(body.subjectConfigs!==undefined)body.subjectConfigs=validateSubjectConfigs(body.subjectConfigs);delete body.status;delete body.schoolId;delete body.deletedAt;return body}
const and=(...filters:any[])=>({$and:filters.filter(filter=>filter&&Object.keys(filter).length)});

export async function examinationRoutes(app:FastifyInstance){
 await registerCrud(app,{prefix:'/api/exams',model:Exam,entity:'exam',readPermission:PERMISSIONS.EXAM_READ,writePermission:PERMISSIONS.EXAM_WRITE,searchable:['name','term'],readScope:examReadScope,prepareCreate:prepareExamCreate,prepareUpdate:prepareExamUpdate});
 app.post('/api/exams/:id/status',{preHandler:requirePermission(PERMISSIONS.EXAM_WRITE)},async(request:any)=>{const next=String(request.body?.status||''),allowed=['DRAFT','MARKS_ENTRY','LOCKED'];if(!allowed.includes(next))throw new AppError(400,'INVALID_STATUS','Invalid exam status transition target');const exam:any=await Exam.findById(request.params.id);if(!exam)throw new AppError(404,'NOT_FOUND','Exam not found');const transitions:Record<string,string[]>= {DRAFT:['MARKS_ENTRY'],MARKS_ENTRY:['DRAFT','LOCKED'],LOCKED:['MARKS_ENTRY'],PUBLISHED:[]};if(!(transitions[exam.status]||[]).includes(next))throw new AppError(409,'INVALID_STATUS_TRANSITION',`Cannot move exam from ${exam.status} to ${next}`);const before=exam.status;exam.status=next;exam.updatedAt=new Date();await exam.save();await writeAudit({action:'exam.status',entity:'exam',entityId:String(exam._id),before:{status:before},after:{status:next},ip:request.ip});return{success:true,data:exam}});
 app.post('/api/exams/:id/marks',{preHandler:requirePermission(PERMISSIONS.MARKS_WRITE)},async(request:any)=>{const exam:any=await Exam.findById(request.params.id);if(!exam||exam.status!=='MARKS_ENTRY')throw new AppError(409,'MARKS_CLOSED','Exam is not open for marks entry');const records=Array.isArray(request.body?.records)?request.body.records:[];if(!records.length||records.length>500)throw new AppError(400,'INVALID_INPUT','Provide between 1 and 500 marks records');const duplicate=new Set<string>();for(const record of records){const key=`${String(record.studentId)}:${String(record.subjectId)}`;if(duplicate.has(key))throw new AppError(400,'DUPLICATE_MARK_RECORD','Duplicate student and subject in the same upload');duplicate.add(key)}await assertTeacherCanEnterMarks(request,records);const configs=new Map((exam.subjectConfigs||[]).map((config:any)=>[String(config.subjectId),config]));const schoolId=getTenantContext()?.schoolId;if(!schoolId)throw new Error('Tenant context missing');const ops=records.map((record:any)=>{const config=configs.get(String(record.subjectId));if(!config)throw new AppError(400,'SUBJECT_NOT_IN_EXAM','Subject is not configured for this exam');const normalized=validateMarkRecord(record,config);return{updateOne:{filter:{schoolId,examId:exam._id,studentId:record.studentId,subjectId:record.subjectId},update:{$set:{...normalized,enteredBy:request.auth.sub,updatedAt:new Date()},$setOnInsert:{schoolId,examId:exam._id,studentId:record.studentId,subjectId:record.subjectId,createdAt:new Date(),deletedAt:null}},upsert:true}}});const result=await Mark.bulkWrite(ops);await writeAudit({action:'marks.upload',entity:'exam',entityId:String(exam._id),after:{records:records.length,upserted:result.upsertedCount,modified:result.modifiedCount},ip:request.ip});return{success:true,data:{upserted:result.upsertedCount,modified:result.modifiedCount}}});
 app.get('/api/exams/:id/marks',{preHandler:requirePermission(PERMISSIONS.EXAM_READ)},async(request:any)=>{const exam:any=await Exam.findById(request.params.id).lean();if(!exam)throw new AppError(404,'NOT_FOUND','Exam not found');if(['STUDENT','PARENT'].includes(request.auth?.role)&&exam.status!=='PUBLISHED')throw new AppError(404,'NOT_FOUND','Published result not found');const scope=await markReadScope(request),extra:any={examId:new Types.ObjectId(request.params.id)};if(request.query?.studentId)extra.studentId=new Types.ObjectId(String(request.query.studentId));if(request.query?.subjectId)extra.subjectId=new Types.ObjectId(String(request.query.subjectId));const rows=await Mark.find(and(scope,extra)).sort({studentId:1,subjectId:1}).limit(1000).lean();return{success:true,data:rows}});
 app.post('/api/exams/:id/publish',{preHandler:requirePermission(PERMISSIONS.RESULT_PUBLISH)},async(request:any)=>{const exam:any=await Exam.findById(request.params.id);if(!exam)throw new AppError(404,'NOT_FOUND','Exam not found');if(exam.status!=='LOCKED')throw new AppError(409,'EXAM_NOT_LOCKED','Lock exam before publishing');exam.status='PUBLISHED';exam.updatedAt=new Date();await exam.save();await writeAudit({action:'exam.publish',entity:'exam',entityId:String(exam._id),after:{status:'PUBLISHED'},ip:request.ip});return{success:true,data:exam}});
}
