import type { FastifyInstance } from 'fastify';
import { Types } from 'mongoose';
import { PERMISSIONS } from '@erp/contracts';
import { registerCrud } from '../../core/crud.js';
import { requirePermission } from '../../core/security.js';
import { AppError } from '../../core/errors.js';
import { writeAudit } from '../../core/audit.js';
import { getTenantContext } from '../../core/tenant-context.js';
import { Exam,Mark } from './models.js';
import { assertRecordsInExamScope,assertTeacherCanEnterMarks,examReadScope,markReadScope,validateMarkRecord,validateSubjectConfigs } from './access.js';
import { AcademicClass,AcademicSession,Section,Subject } from '../academics/models.js';
import { Student } from '../people/models.js';

const validId=(value:any)=>Types.ObjectId.isValid(String(value||''));
const clean=(value:any,max=180)=>String(value??'').trim().slice(0,max);
async function examData(request:any,current:any={}){const body=request.body??{},name=body.name===undefined?current.name:clean(body.name,180),sessionId=body.sessionId??current.sessionId,classId=body.classId??current.classId,sectionIds:any[]=body.sectionIds===undefined?(current.sectionIds||[]):body.sectionIds,subjectConfigs:any[]=body.subjectConfigs===undefined?(current.subjectConfigs||[]):validateSubjectConfigs(body.subjectConfigs);if(!name)throw new AppError(400,'INVALID_EXAM','Exam name is required');if(!validId(sessionId)||!await AcademicSession.findById(sessionId).select('_id').lean())throw new AppError(404,'SESSION_NOT_FOUND','Academic session not found');if(!validId(classId)||!await AcademicClass.findById(classId).select('_id').lean())throw new AppError(404,'CLASS_NOT_FOUND','Academic class not found');if(!Array.isArray(sectionIds)||!sectionIds.length||sectionIds.length>100||sectionIds.some((id:any)=>!validId(id)))throw new AppError(400,'INVALID_SECTIONS','Choose at least one valid section');const uniqueSections:string[]=[...new Set<string>(sectionIds.map((id:any)=>String(id)))],sections:any[]=await Section.find({_id:{$in:uniqueSections},classId}).select('_id').lean();if(sections.length!==uniqueSections.length)throw new AppError(422,'SECTION_SCOPE','Every selected section must belong to the exam class');const subjectIds:string[]=subjectConfigs.map((config:any)=>String(config.subjectId));if(subjectIds.some((id:string)=>!validId(id))||await Subject.countDocuments({_id:{$in:subjectIds}})!==new Set<string>(subjectIds).size)throw new AppError(422,'SUBJECT_SCOPE','One or more exam subjects are invalid');const startDate=body.startDate===undefined?new Date(current.startDate):new Date(body.startDate),endDate=body.endDate===undefined?new Date(current.endDate):new Date(body.endDate);if(Number.isNaN(startDate.getTime())||Number.isNaN(endDate.getTime())||endDate<startDate)throw new AppError(400,'INVALID_EXAM_DATES','Exam dates are invalid');return{name,sessionId,classId,sectionIds:uniqueSections,term:body.term===undefined?current.term:clean(body.term,80)||undefined,startDate,endDate,subjectConfigs,status:'DRAFT',updatedAt:new Date()}}
async function prepareExamCreate(request:any){return{...await examData(request),createdAt:new Date()}}
async function prepareExamUpdate(request:any){const current:any=await Exam.findOne({_id:request.params.id,status:'DRAFT'}).lean();if(!current)throw new AppError(409,'EXAM_LOCKED','Only DRAFT exams can be edited');return examData(request,current)}
const and=(...filters:any[])=>({$and:filters.filter(filter=>filter&&Object.keys(filter).length)});
async function readiness(exam:any){const students=await Student.distinct('_id',{classId:exam.classId,sectionId:{$in:exam.sectionIds},lifecycle:'ACTIVE'}),subjects=(exam.subjectConfigs||[]).map((config:any)=>config.subjectId),expected=students.length*subjects.length,count=students.length&&subjects.length?await Mark.countDocuments({examId:exam._id,studentId:{$in:students},subjectId:{$in:subjects}}):0;return{students:students.length,subjects:subjects.length,expected,entered:count,complete:expected>0&&count===expected}}

export async function examinationRoutes(app:FastifyInstance){
 await registerCrud(app,{prefix:'/api/exams',model:Exam,entity:'exam',readPermission:PERMISSIONS.EXAM_READ,writePermission:PERMISSIONS.EXAM_WRITE,searchable:['name','term'],readScope:examReadScope,writeScope:async()=>({status:'DRAFT'}),prepareCreate:prepareExamCreate,prepareUpdate:prepareExamUpdate});
 app.get('/api/exams/:id/readiness',{preHandler:requirePermission(PERMISSIONS.EXAM_READ)},async(request:any)=>{const scope=await examReadScope(request),exam:any=await Exam.findOne(and(scope,{_id:request.params.id})).lean();if(!exam)throw new AppError(404,'NOT_FOUND','Exam not found');return{success:true,data:await readiness(exam)}});
 app.post('/api/exams/:id/status',{preHandler:requirePermission(PERMISSIONS.EXAM_WRITE)},async(request:any)=>{const next=String(request.body?.status||''),allowed=['DRAFT','MARKS_ENTRY','LOCKED'];if(!allowed.includes(next))throw new AppError(400,'INVALID_STATUS','Invalid exam status transition target');const exam:any=await Exam.findById(request.params.id);if(!exam)throw new AppError(404,'NOT_FOUND','Exam not found');const transitions:Record<string,string[]>= {DRAFT:['MARKS_ENTRY'],MARKS_ENTRY:['DRAFT','LOCKED'],LOCKED:['MARKS_ENTRY'],PUBLISHED:[]};if(!(transitions[exam.status]||[]).includes(next))throw new AppError(409,'INVALID_STATUS_TRANSITION',`Cannot move exam from ${exam.status} to ${next}`);if(next==='MARKS_ENTRY'&&exam.status==='DRAFT'){const targetStudents=await Student.countDocuments({classId:exam.classId,sectionId:{$in:exam.sectionIds},lifecycle:'ACTIVE'});if(!targetStudents)throw new AppError(409,'NO_STUDENTS','Exam target has no active students')}if(next==='LOCKED'){const ready=await readiness(exam);if(!ready.complete)throw new AppError(409,'MARKS_INCOMPLETE',`Marks coverage is ${ready.entered}/${ready.expected}`,ready)}const before=exam.status;exam.status=next;exam.updatedAt=new Date();await exam.save();await writeAudit({action:'exam.status',entity:'exam',entityId:String(exam._id),before:{status:before},after:{status:next},ip:request.ip});return{success:true,data:exam}});
 app.post('/api/exams/:id/marks',{preHandler:requirePermission(PERMISSIONS.MARKS_WRITE)},async(request:any)=>{const exam:any=await Exam.findById(request.params.id);if(!exam||exam.status!=='MARKS_ENTRY')throw new AppError(409,'MARKS_CLOSED','Exam is not open for marks entry');const records:any[]=Array.isArray(request.body?.records)?request.body.records:[];if(!records.length||records.length>500)throw new AppError(400,'INVALID_INPUT','Provide between 1 and 500 marks records');const duplicate=new Set<string>();for(const record of records){if(!validId(record?.studentId)||!validId(record?.subjectId))throw new AppError(400,'INVALID_MARK_RECORD','Student and subject IDs must be valid');const key=`${String(record.studentId)}:${String(record.subjectId)}`;if(duplicate.has(key))throw new AppError(400,'DUPLICATE_MARK_RECORD','Duplicate student and subject in the same upload');duplicate.add(key)}await assertRecordsInExamScope(exam,records);await assertTeacherCanEnterMarks(request,records);const configs=new Map<string,any>((exam.subjectConfigs||[]).map((config:any)=>[String(config.subjectId),config]));const schoolId=getTenantContext()?.schoolId;if(!schoolId)throw new Error('Tenant context missing');const ops:any[]=records.map((record:any)=>{const config=configs.get(String(record.subjectId));if(!config)throw new AppError(400,'SUBJECT_NOT_IN_EXAM','Subject is not configured for this exam');const normalized=validateMarkRecord(record,config);return{updateOne:{filter:{schoolId,examId:exam._id,studentId:record.studentId,subjectId:record.subjectId},update:{$set:{...normalized,enteredBy:request.auth.sub,updatedAt:new Date()},$setOnInsert:{schoolId,examId:exam._id,studentId:record.studentId,subjectId:record.subjectId,createdAt:new Date(),deletedAt:null}},upsert:true}}});const result=await Mark.bulkWrite(ops);await writeAudit({action:'marks.upload',entity:'exam',entityId:String(exam._id),after:{records:records.length,upserted:result.upsertedCount,modified:result.modifiedCount},ip:request.ip});return{success:true,data:{upserted:result.upsertedCount,modified:result.modifiedCount}}});
 app.get('/api/exams/:id/marks',{preHandler:requirePermission(PERMISSIONS.EXAM_READ)},async(request:any)=>{const scope=await examReadScope(request),exam:any=await Exam.findOne(and(scope,{_id:request.params.id})).lean();if(!exam)throw new AppError(404,'NOT_FOUND','Exam not found');if(['STUDENT','PARENT'].includes(request.auth?.role)&&exam.status!=='PUBLISHED')throw new AppError(404,'NOT_FOUND','Published result not found');const markScope=await markReadScope(request),extra:any={examId:new Types.ObjectId(request.params.id)};if(request.query?.studentId){if(!validId(request.query.studentId))throw new AppError(400,'INVALID_STUDENT','Invalid student filter');extra.studentId=new Types.ObjectId(String(request.query.studentId))}if(request.query?.subjectId){if(!validId(request.query.subjectId))throw new AppError(400,'INVALID_SUBJECT','Invalid subject filter');extra.subjectId=new Types.ObjectId(String(request.query.subjectId))}const rows=await Mark.find(and(markScope,extra)).sort({studentId:1,subjectId:1}).limit(5000).lean();return{success:true,data:rows}});
 app.post('/api/exams/:id/publish',{preHandler:requirePermission(PERMISSIONS.RESULT_PUBLISH)},async(request:any)=>{const exam:any=await Exam.findById(request.params.id);if(!exam)throw new AppError(404,'NOT_FOUND','Exam not found');if(exam.status!=='LOCKED')throw new AppError(409,'EXAM_NOT_LOCKED','Lock exam before publishing');const ready=await readiness(exam);if(!ready.complete)throw new AppError(409,'MARKS_INCOMPLETE','Exam is no longer ready to publish',ready);exam.status='PUBLISHED';exam.updatedAt=new Date();await exam.save();await writeAudit({action:'exam.publish',entity:'exam',entityId:String(exam._id),after:{status:'PUBLISHED',readiness:ready},ip:request.ip});return{success:true,data:exam}});
}
