import type{FastifyInstance}from'fastify';
import{randomBytes,timingSafeEqual}from'node:crypto';
import{Types}from'mongoose';
import{PERMISSIONS}from'@erp/contracts';
import{requirePermission,hashToken}from'../../core/security.js';
import{AppError,forbidden}from'../../core/errors.js';
import{runWithTenant}from'../../core/tenant-context.js';
import{writeAudit}from'../../core/audit.js';
import{School}from'../tenancy/models.js';
import{BiometricDevice,BiometricMapping,BiometricPunch}from'./models.js';
import{Student,Teacher,Staff}from'../people/models.js';
import{Attendance,FacultyAttendance}from'../attendance/models.js';
import{AcademicSession}from'../academics/models.js';
import{SchoolSettings}from'../settings/models.js';

const clean=(value:any,max=500)=>String(value??'').trim().slice(0,max);
const validId=(value:any)=>Types.ObjectId.isValid(String(value||''));
const eventPattern=/^[A-Za-z0-9._:-]{8,160}$/;
function secretMatches(raw:string,hash:string){const a=Buffer.from(hashToken(raw)),b=Buffer.from(hash);return a.length===b.length&&timingSafeEqual(a,b)}
function newDeviceSecret(){return randomBytes(32).toString('base64url')}
function localStamp(date:Date,timeZone:string){const parts=new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date),map=Object.fromEntries(parts.map(part=>[part.type,part.value]));return{dateKey:`${map.year}-${map.month}-${map.day}`,clock:`${map.hour}:${map.minute}`}}
function lateStatus(clock:string,lateAfter:any){const threshold=/^([01]\d|2[0-3]):[0-5]\d$/.test(String(lateAfter||''))?String(lateAfter):'';return threshold&&clock>threshold?'LATE':'PRESENT'}
async function validatePerson(type:any,id:any){const personType=String(type||'');if(!['STUDENT','TEACHER','STAFF'].includes(personType)||!validId(id))throw new AppError(400,'INVALID_PERSON','Valid student, teacher or staff is required');const Model:any=personType==='STUDENT'?Student:personType==='TEACHER'?Teacher:Staff;const person:any=await Model.findById(id).select('_id status lifecycle classId sectionId').lean();if(!person||(person.status&&person.status!=='ACTIVE')||(personType==='STUDENT'&&person.lifecycle!=='ACTIVE'))throw new AppError(404,'PERSON_NOT_FOUND','Active person not found in this school');return{personType,personId:new Types.ObjectId(String(id)),person}}
async function processMappedPunch(punch:any,mapping:any,school:any){const settings:any=await SchoolSettings.findOne().select('attendance').lean(),stamp=localStamp(new Date(punch.punchedAt),school.timezone||'Asia/Kolkata'),date=new Date(`${stamp.dateKey}T00:00:00.000Z`),direction=punch.direction as 'IN'|'OUT'|'UNKNOWN';if(mapping.personType==='STUDENT'){if(direction==='OUT'){punch.processingStatus='PROCESSED';punch.processingDetail='Student OUT punch recorded; daily attendance unchanged';punch.processedAt=new Date();await punch.save();return}const student:any=await Student.findById(mapping.personId).select('classId sectionId lifecycle status').lean(),session:any=await AcademicSession.findOne({isCurrent:true}).sort({startDate:-1}).lean();if(!student||student.lifecycle!=='ACTIVE'||!student.classId||!student.sectionId||!session){punch.processingStatus='ERROR';punch.processingDetail='Student academic profile or current session is incomplete';punch.processedAt=new Date();await punch.save();return}const existing:any=await Attendance.findOne({date,studentId:student._id,subjectId:null,period:null});if(existing&&existing.source!=='BIOMETRIC'){punch.processingStatus='PROCESSED';punch.processingDetail='Existing non-biometric attendance preserved';punch.processedAt=new Date();await punch.save();return}const status=lateStatus(stamp.clock,settings?.attendance?.lateAfter);await Attendance.findOneAndUpdate({date,studentId:student._id,subjectId:null,period:null},{$set:{date,sessionId:session._id,classId:student.classId,sectionId:student.sectionId,studentId:student._id,status,source:'BIOMETRIC',remark:`Biometric ${stamp.clock}`,updatedAt:new Date()},$setOnInsert:{createdAt:new Date()}},{new:true,upsert:true,setDefaultsOnInsert:true});punch.processingStatus='PROCESSED';punch.processingDetail=`Daily student attendance marked ${status}`;punch.processedAt=new Date();await punch.save();return}
 const existing:any=await FacultyAttendance.findOne({date,personType:mapping.personType,personId:mapping.personId});if(existing&&existing.source!=='BIOMETRIC'){punch.processingStatus='PROCESSED';punch.processingDetail='Existing manual/import faculty attendance preserved';punch.processedAt=new Date();await punch.save();return}let checkIn=existing?.checkIn||'',checkOut=existing?.checkOut||'';if(direction==='IN')checkIn=!checkIn||stamp.clock<checkIn?stamp.clock:checkIn;else if(direction==='OUT')checkOut=!checkOut||stamp.clock>checkOut?stamp.clock:checkOut;else if(!checkIn)checkIn=stamp.clock;else checkOut=!checkOut||stamp.clock>checkOut?stamp.clock:checkOut;const status=lateStatus(checkIn||stamp.clock,settings?.attendance?.lateAfter);await FacultyAttendance.findOneAndUpdate({date,personType:mapping.personType,personId:mapping.personId},{$set:{date,personType:mapping.personType,personId:mapping.personId,status,checkIn:checkIn||undefined,checkOut:checkOut||undefined,source:'BIOMETRIC',updatedAt:new Date()},$setOnInsert:{createdAt:new Date()}},{new:true,upsert:true,setDefaultsOnInsert:true});punch.processingStatus='PROCESSED';punch.processingDetail='Faculty attendance synchronized';punch.processedAt=new Date();await punch.save()}

export async function biometricRoutes(app:FastifyInstance){
 app.get('/api/biometric/devices',{preHandler:requirePermission(PERMISSIONS.BIOMETRIC_READ)},async()=>({success:true,data:await BiometricDevice.find().sort({name:1}).lean()}));
 app.post('/api/biometric/devices',{preHandler:requirePermission(PERMISSIONS.BIOMETRIC_WRITE)},async(request:any)=>{const name=clean(request.body?.name,180),deviceCode=clean(request.body?.deviceCode,80).toUpperCase();if(!name||!deviceCode||!eventPattern.test(deviceCode.padEnd(8,'0')))throw new AppError(400,'INVALID_DEVICE','Name and a safe deviceCode are required');const secret=newDeviceSecret(),item=await BiometricDevice.create({name,deviceCode,location:clean(request.body?.location,180)||undefined,mode:request.body?.mode==='HTTP_DEVICE'?'HTTP_DEVICE':'LOCAL_AGENT',secretHash:hashToken(secret),status:'OFFLINE',createdAt:new Date(),updatedAt:new Date()});await writeAudit({action:'biometric.device-create',entity:'biometric-device',entityId:String(item._id),after:{name:item.name,deviceCode:item.deviceCode,mode:item.mode},ip:request.ip});return{success:true,data:{device:item.toObject(),deviceSecret:secret},meta:{secretShownOnce:true}}});
 app.patch('/api/biometric/devices/:id',{preHandler:requirePermission(PERMISSIONS.BIOMETRIC_WRITE)},async(request:any)=>{const item:any=await BiometricDevice.findById(request.params.id);if(!item)throw new AppError(404,'NOT_FOUND','Biometric device not found');if(item.status==='DISABLED')throw new AppError(409,'DEVICE_DISABLED','Disabled device must be explicitly re-enabled');const before={name:item.name,location:item.location,mode:item.mode};if(request.body?.name!==undefined){const name=clean(request.body.name,180);if(!name)throw new AppError(400,'INVALID_DEVICE','Device name cannot be empty');item.name=name}if(request.body?.location!==undefined)item.location=clean(request.body.location,180)||undefined;if(request.body?.mode!==undefined){if(!['LOCAL_AGENT','HTTP_DEVICE'].includes(request.body.mode))throw new AppError(400,'INVALID_MODE','Invalid device mode');item.mode=request.body.mode}item.updatedAt=new Date();await item.save();await writeAudit({action:'biometric.device-update',entity:'biometric-device',entityId:String(item._id),before,after:{name:item.name,location:item.location,mode:item.mode},ip:request.ip});return{success:true,data:item}});
 app.post('/api/biometric/devices/:id/rotate-secret',{preHandler:requirePermission(PERMISSIONS.BIOMETRIC_WRITE)},async(request:any)=>{const item:any=await BiometricDevice.findById(request.params.id).select('+secretHash');if(!item)throw new AppError(404,'NOT_FOUND','Biometric device not found');const secret=newDeviceSecret();item.secretHash=hashToken(secret);item.status='OFFLINE';item.updatedAt=new Date();await item.save();await writeAudit({action:'biometric.secret-rotate',entity:'biometric-device',entityId:String(item._id),after:{rotated:true},ip:request.ip});return{success:true,data:{deviceId:item._id,deviceSecret:secret},meta:{secretShownOnce:true}}});
 app.post('/api/biometric/devices/:id/status',{preHandler:requirePermission(PERMISSIONS.BIOMETRIC_WRITE)},async(request:any)=>{const status=String(request.body?.status||'');if(!['OFFLINE','DISABLED'].includes(status))throw new AppError(400,'INVALID_STATUS','Admin may set OFFLINE or DISABLED');const item:any=await BiometricDevice.findByIdAndUpdate(request.params.id,{$set:{status,updatedAt:new Date()}},{new:true});if(!item)throw new AppError(404,'NOT_FOUND','Biometric device not found');await writeAudit({action:'biometric.device-status',entity:'biometric-device',entityId:String(item._id),after:{status},ip:request.ip});return{success:true,data:item}});
 app.get('/api/biometric/mappings',{preHandler:requirePermission(PERMISSIONS.BIOMETRIC_READ)},async(request:any)=>{const filter:any={};if(request.query?.deviceId)filter.deviceId=request.query.deviceId;return{success:true,data:await BiometricMapping.find(filter).sort({personType:1,biometricId:1}).limit(1000).lean()}});
 app.post('/api/biometric/mappings',{preHandler:requirePermission(PERMISSIONS.BIOMETRIC_WRITE)},async(request:any)=>{const biometricId=clean(request.body?.biometricId,100);if(!biometricId)throw new AppError(400,'INVALID_BIOMETRIC_ID','biometricId is required');if(!validId(request.body?.deviceId)||!await BiometricDevice.findById(request.body.deviceId).select('_id').lean())throw new AppError(404,'DEVICE_NOT_FOUND','Device not found');const person=await validatePerson(request.body?.personType,request.body?.personId),item=await BiometricMapping.create({...person,biometricId,deviceId:request.body.deviceId,createdAt:new Date(),updatedAt:new Date()});await writeAudit({action:'biometric.mapping-create',entity:'biometric-mapping',entityId:String(item._id),after:{personType:item.personType,personId:String(item.personId),biometricId:item.biometricId,deviceId:String(item.deviceId)},ip:request.ip});return{success:true,data:item}});
 app.delete('/api/biometric/mappings/:id',{preHandler:requirePermission(PERMISSIONS.BIOMETRIC_WRITE)},async(request:any)=>{const item:any=await BiometricMapping.findById(request.params.id);if(!item)throw new AppError(404,'NOT_FOUND','Biometric mapping not found');item.deletedAt=new Date();item.updatedAt=new Date();await item.save();await writeAudit({action:'biometric.mapping-delete',entity:'biometric-mapping',entityId:String(item._id),after:{deleted:true},ip:request.ip});return{success:true,data:{id:item._id,deleted:true}}});
 app.get('/api/biometric/punches',{preHandler:requirePermission(PERMISSIONS.BIOMETRIC_READ)},async(request:any)=>{const filter:any={};if(request.query?.deviceId)filter.deviceId=request.query.deviceId;if(request.query?.processingStatus)filter.processingStatus=request.query.processingStatus;return{success:true,data:await BiometricPunch.find(filter).sort({punchedAt:-1}).limit(500).lean()}});
 app.post('/api/device/biometric/punches',{config:{rateLimit:{max:240,timeWindow:'1 minute'}}},async(request:any)=>{const schoolCode=clean(request.headers['x-school-code'],20).toUpperCase(),deviceCode=clean(request.headers['x-device-code'],80).toUpperCase(),secret=clean(request.headers['x-device-secret'],200),timestampRaw=clean(request.headers['x-device-timestamp'],80),timestampNumber=Number(timestampRaw),requestTime=Number.isFinite(timestampNumber)?new Date(timestampNumber<1e12?timestampNumber*1000:timestampNumber):new Date(timestampRaw);if(!schoolCode||!deviceCode||!secret||Number.isNaN(requestTime.getTime())||Math.abs(Date.now()-requestTime.getTime())>5*60_000)throw forbidden('Invalid or stale device credentials');const school:any=await School.findOne({code:schoolCode,status:{$in:['ACTIVE','TRIAL']}}).lean();if(!school||!(school.enabledModules||[]).includes('biometric'))throw forbidden('Biometric integration unavailable');return runWithTenant({schoolId:String(school._id),requestId:request.id},async()=>{const device:any=await BiometricDevice.findOne({deviceCode}).select('+secretHash');if(!device||device.status==='DISABLED'||!secretMatches(secret,device.secretHash))throw forbidden('Invalid device credentials');const eventId=clean(request.body?.eventId,160),biometricId=clean(request.body?.biometricId,100),direction=String(request.body?.direction||'UNKNOWN').toUpperCase(),punchedAt=new Date(request.body?.punchedAt);if(!eventPattern.test(eventId)||!biometricId||!['IN','OUT','UNKNOWN'].includes(direction)||Number.isNaN(punchedAt.getTime()))throw new AppError(400,'INVALID_PUNCH','eventId, biometricId, punchedAt and direction are invalid');if(punchedAt.getTime()>Date.now()+10*60_000||punchedAt.getTime()<Date.now()-30*86400000)throw new AppError(422,'PUNCH_TIME_RANGE','Punch time must be within the last 30 days and not in the future');const duplicate:any=await BiometricPunch.findOne({deviceId:device._id,eventId}).lean();if(duplicate){device.lastSeenAt=new Date();device.status='ONLINE';device.updatedAt=new Date();await device.save();return{success:true,data:{id:duplicate._id,accepted:true,duplicate:true,processingStatus:duplicate.processingStatus}}}const mapping:any=await BiometricMapping.findOne({deviceId:device._id,biometricId}).lean(),punch:any=await BiometricPunch.create({eventId,deviceId:device._id,biometricId,personType:mapping?.personType,personId:mapping?.personId,punchedAt,direction,processingStatus:mapping?'UNMAPPED':'UNMAPPED',processingDetail:mapping?'Queued for attendance synchronization':'No biometric mapping found',receivedAt:new Date()});device.lastSeenAt=new Date();device.status='ONLINE';device.updatedAt=new Date();await device.save();if(mapping)await processMappedPunch(punch,mapping,school);else{punch.processedAt=new Date();await punch.save()}return{success:true,data:{id:punch._id,accepted:true,duplicate:false,processingStatus:punch.processingStatus}}})});
}
