import type { FastifyInstance } from 'fastify';
import bcrypt from 'bcryptjs';
import { PlatformAdmin } from './models.js';
import { authenticate,hashToken,signAccessToken,signMfaChallenge,verifyMfaChallenge,requirePlatform } from '../../core/security.js';
import { buildOtpAuthUri,generateRecoveryCodes,generateTotpSecret,normalizeRecoveryCode,verifyTotp } from '../../core/mfa.js';
import { decryptSecret,encryptSecret } from '../../core/secrets.js';
import { AppError,unauthorized } from '../../core/errors.js';
export async function platformMfaRoutes(app:FastifyInstance){
 app.post('/api/platform/auth/mfa/verify',{config:{rateLimit:{max:8,timeWindow:'5 minutes'}}},async(request:any)=>{const{challengeToken,code}=request.body??{};const claims=await verifyMfaChallenge(String(challengeToken||'')).catch(()=>null);if(!claims)throw unauthorized('MFA challenge expired');const admin=await PlatformAdmin.findById(claims.sub).select('+mfaSecretEncrypted +mfaRecoveryCodeHashes');if(!admin?.isActive||!admin.mfaEnabled||!admin.mfaSecretEncrypted)throw unauthorized('MFA is not available');const normalized=String(code||'').trim();let valid=verifyTotp(decryptSecret(admin.mfaSecretEncrypted),normalized);if(!valid){const recovery=normalizeRecoveryCode(normalized);const recoveryHash=recovery?hashToken(recovery):'';const index=admin.mfaRecoveryCodeHashes?.indexOf(recoveryHash)??-1;if(index>=0){admin.mfaRecoveryCodeHashes.splice(index,1);valid=true}}if(!valid)throw unauthorized('Invalid verification code');admin.lastLoginAt=new Date();await admin.save();const accessToken=await signAccessToken({sub:String(admin._id),type:'platform'});return{success:true,data:{accessToken,admin:{id:admin._id,name:admin.name,email:admin.email}}}});
 const guard=[authenticate,async(request:any)=>requirePlatform(request)];
 app.post('/api/platform/auth/mfa/setup',{preHandler:guard},async(request:any)=>{const admin=await PlatformAdmin.findById(request.auth.sub).select('+mfaPendingSecretEncrypted');if(!admin)throw unauthorized();if(admin.mfaEnabled)throw new AppError(409,'MFA_ALREADY_ENABLED','Disable MFA before rotating the authenticator secret');const secret=generateTotpSecret();admin.mfaPendingSecretEncrypted=encryptSecret(secret);await admin.save();return{success:true,data:{manualKey:secret,otpAuthUri:buildOtpAuthUri('ERP BY ANMOL',admin.email,secret)}}});
 app.post('/api/platform/auth/mfa/enable',{preHandler:guard},async(request:any)=>{const admin=await PlatformAdmin.findById(request.auth.sub).select('+mfaPendingSecretEncrypted');if(!admin?.mfaPendingSecretEncrypted)throw new AppError(400,'MFA_SETUP_REQUIRED','Start MFA setup first');const secret=decryptSecret(admin.mfaPendingSecretEncrypted);if(!verifyTotp(secret,String(request.body?.code||'')))throw new AppError(400,'INVALID_MFA_CODE','Authenticator code is invalid');const recoveryCodes=generateRecoveryCodes();admin.mfaSecretEncrypted=encryptSecret(secret);admin.mfaPendingSecretEncrypted=undefined;admin.mfaRecoveryCodeHashes=recoveryCodes.map(code=>hashToken(normalizeRecoveryCode(code)));admin.mfaEnabled=true;admin.mfaEnabledAt=new Date();await admin.save();return{success:true,data:{enabled:true,recoveryCodes}}});
 app.post('/api/platform/auth/mfa/disable',{preHandler:guard},async(request:any)=>{const admin=await PlatformAdmin.findById(request.auth.sub).select('+passwordHash +mfaSecretEncrypted');if(!admin?.mfaEnabled||!admin.mfaSecretEncrypted)throw new AppError(400,'MFA_NOT_ENABLED','MFA is not enabled');if(!(await bcrypt.compare(String(request.body?.password||''),admin.passwordHash)))throw unauthorized('Password confirmation failed');if(!verifyTotp(decryptSecret(admin.mfaSecretEncrypted),String(request.body?.code||'')))throw unauthorized('Authenticator code is invalid');admin.mfaEnabled=false;admin.mfaSecretEncrypted=undefined;admin.mfaPendingSecretEncrypted=undefined;admin.mfaRecoveryCodeHashes=[];admin.mfaEnabledAt=undefined;await admin.save();return{success:true,data:{enabled:false}}});
}
export async function platformPasswordLogin(admin:any){if(admin.mfaEnabled)return{mfaRequired:true,challengeToken:await signMfaChallenge(String(admin._id))};admin.lastLoginAt=new Date();await admin.save();return{mfaRequired:false,accessToken:await signAccessToken({sub:String(admin._id),type:'platform'}),admin:{id:admin._id,name:admin.name,email:admin.email}}}
