import type { FastifyInstance } from 'fastify';import bcrypt from 'bcryptjs';import { DEFAULT_ROLE_PERMISSIONS,MODULES } from '@erp/contracts';
import { PlatformAdmin,School } from './models.js';import { User } from '../identity/models.js';import { AppError,unauthorized } from '../../core/errors.js';import { authenticate,requirePlatform } from '../../core/security.js';import { runWithTenant } from '../../core/tenant-context.js';import { invalidateSchoolAccess } from './module-access.js';import { platformMfaRoutes,platformPasswordLogin } from './platform-mfa.js';
export async function tenancyRoutes(app:FastifyInstance){
 await platformMfaRoutes(app);
 app.post('/api/platform/auth/login',{config:{rateLimit:{max:5,timeWindow:'1 minute'}}},async(request:any)=>{const{email,password}=request.body??{};const admin=await PlatformAdmin.findOne({email:String(email||'').toLowerCase()}).select('+passwordHash');if(!admin?.isActive||!(await bcrypt.compare(String(password||''),admin.passwordHash)))throw unauthorized('Invalid platform credentials');return{success:true,data:await platformPasswordLogin(admin)}});
 const guard=[authenticate,async(request:any)=>requirePlatform(request)];
 app.get('/api/platform/schools',{preHandler:guard},async()=>({success:true,data:await School.find().sort({createdAt:-1}).lean()}));
 app.post('/api/platform/schools',{preHandler:guard},async(request:any)=>{const{name,code,email,phone,plan='STARTER',admin}=request.body??{};if(!name||!code||!admin?.email||!admin?.password)throw new AppError(400,'INVALID_INPUT','School and first admin details are required');const school=await School.create({name,code:String(code).toUpperCase(),email,phone,plan,status:'ACTIVE',enabledModules:MODULES});await runWithTenant({schoolId:String(school._id),userId:request.auth.sub},async()=>User.create({email:String(admin.email).toLowerCase(),passwordHash:await bcrypt.hash(admin.password,12),firstName:admin.firstName||'School',lastName:admin.lastName||'Admin',role:'SCHOOL_ADMIN',permissions:DEFAULT_ROLE_PERMISSIONS.SCHOOL_ADMIN,mustChangePassword:true}));return{success:true,data:school}});
 app.patch('/api/platform/schools/:id',{preHandler:guard},async(request:any)=>{const allowed:any={};for(const key of ['name','email','phone','plan','status','enabledModules','academicYearLabel','timezone'])if(request.body?.[key]!==undefined)allowed[key]=request.body[key];const school=await School.findByIdAndUpdate(request.params.id,{$set:{...allowed,updatedAt:new Date()}},{new:true,runValidators:true});if(school)invalidateSchoolAccess(String(school._id));if(!school)throw new AppError(404,'NOT_FOUND','School not found');return{success:true,data:school}});
 app.get('/api/platform/metrics',{preHandler:guard},async()=>{const[total,active,suspended,trial,mfaEnabledAdmins]=await Promise.all([School.countDocuments(),School.countDocuments({status:'ACTIVE'}),School.countDocuments({status:'SUSPENDED'}),School.countDocuments({status:'TRIAL'}),PlatformAdmin.countDocuments({isActive:true,mfaEnabled:true})]);return{success:true,data:{schools:{total,active,suspended,trial},security:{mfaEnabledAdmins}}}});
}
