import type { FastifyInstance } from 'fastify';
import bcrypt from 'bcryptjs';
import { DEFAULT_ROLE_PERMISSIONS } from '@erp/contracts';
import { PlatformAdmin,School } from './models.js';
import { User } from '../identity/models.js';
import { AppError,unauthorized } from '../../core/errors.js';
import { authenticate,requirePlatform } from '../../core/security.js';
import { runWithTenant } from '../../core/tenant-context.js';
import { invalidateSchoolAccess } from './module-access.js';
import { platformMfaRoutes,platformPasswordLogin } from './platform-mfa.js';
import { clampModulesToPlan,modulesForPlan,normalizePlan,validateEnabledModules } from './plans.js';

const clean=(value:any,max=240)=>String(value??'').trim().slice(0,max);
function email(value:any,label='Email'){const result=clean(value,254).toLowerCase();if(result&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(result))throw new AppError(400,'INVALID_EMAIL',`${label} is invalid`);return result||undefined}
function schoolCode(value:any){const code=clean(value,12).toUpperCase();if(!/^[A-Z0-9]{3,12}$/.test(code))throw new AppError(400,'INVALID_SCHOOL_CODE','School code must be 3–12 uppercase letters or numbers');return code}
function timezone(value:any){const zone=clean(value,80);try{new Intl.DateTimeFormat('en-US',{timeZone:zone}).format(new Date())}catch{throw new AppError(400,'INVALID_TIMEZONE','Timezone is invalid')}return zone}
function planValue(value:any){try{return normalizePlan(value)}catch{throw new AppError(400,'INVALID_PLAN','Plan must be STARTER, GROWTH or PRO')}}
function moduleValue(plan:any,value:any){try{return validateEnabledModules(plan,value)}catch(error){const message=error instanceof Error?error.message:'';if(message==='UNKNOWN_MODULE')throw new AppError(400,'UNKNOWN_MODULE','One or more modules are unknown');if(message==='MODULE_NOT_IN_PLAN')throw new AppError(400,'MODULE_NOT_IN_PLAN','One or more modules are not included in this plan');throw new AppError(400,'INVALID_MODULES','enabledModules must be an array')}}

export async function tenancyRoutes(app:FastifyInstance){
 await platformMfaRoutes(app);
 app.post('/api/platform/auth/login',{config:{rateLimit:{max:5,timeWindow:'1 minute'}}},async(request:any)=>{const{email:rawEmail,password}=request.body??{},loginEmail=email(rawEmail);const admin=await PlatformAdmin.findOne({email:loginEmail}).select('+passwordHash');if(!admin?.isActive||!(await bcrypt.compare(String(password||''),admin.passwordHash)))throw unauthorized('Invalid platform credentials');return{success:true,data:await platformPasswordLogin(admin)}});
 const guard=[authenticate,async(request:any)=>requirePlatform(request)];
 app.get('/api/platform/schools',{preHandler:guard},async()=>({success:true,data:await School.find().sort({createdAt:-1}).lean()}));
 app.post('/api/platform/schools',{preHandler:guard},async(request:any)=>{const{name,code,email:schoolEmail,phone,admin}=request.body??{},schoolName=clean(name,180);if(!schoolName||!admin?.email||!admin?.password||!clean(admin?.firstName,100))throw new AppError(400,'INVALID_INPUT','School name and first admin name/email/password are required');if(String(admin.password).length<8)throw new AppError(400,'WEAK_PASSWORD','First admin password must be at least 8 characters');const plan=planValue(request.body?.plan||'STARTER'),enabledModules=request.body?.enabledModules===undefined?modulesForPlan(plan):moduleValue(plan,request.body.enabledModules);let school:any;try{school=await School.create({name:schoolName,code:schoolCode(code),email:email(schoolEmail),phone:clean(phone,30)||undefined,plan,status:request.body?.status==='TRIAL'?'TRIAL':'ACTIVE',enabledModules,academicYearLabel:clean(request.body?.academicYearLabel,40)||undefined,timezone:request.body?.timezone?timezone(request.body.timezone):'Asia/Kolkata'});try{await runWithTenant({schoolId:String(school._id),userId:request.auth.sub,requestId:request.id},async()=>User.create({email:email(admin.email,'Admin email'),username:admin.username?clean(admin.username,80).toLowerCase():undefined,passwordHash:await bcrypt.hash(String(admin.password),12),firstName:clean(admin.firstName,100),lastName:clean(admin.lastName,100),role:'SCHOOL_ADMIN',permissions:DEFAULT_ROLE_PERMISSIONS.SCHOOL_ADMIN,mustChangePassword:true}))}catch(error){await School.deleteOne({_id:school._id}).catch(()=>undefined);throw error}return{success:true,data:school}}catch(error:any){if(error?.code===11000)throw new AppError(409,'SCHOOL_EXISTS','School code already exists');throw error}});
 app.patch('/api/platform/schools/:id',{preHandler:guard},async(request:any)=>{const school:any=await School.findById(request.params.id);if(!school)throw new AppError(404,'NOT_FOUND','School not found');const body=request.body??{},nextPlan=body.plan===undefined?school.plan:planValue(body.plan),allowed:any={};if(body.name!==undefined){const name=clean(body.name,180);if(!name)throw new AppError(400,'INVALID_NAME','School name cannot be empty');allowed.name=name}if(body.email!==undefined)allowed.email=email(body.email);if(body.phone!==undefined)allowed.phone=clean(body.phone,30)||undefined;if(body.academicYearLabel!==undefined)allowed.academicYearLabel=clean(body.academicYearLabel,40)||undefined;if(body.timezone!==undefined)allowed.timezone=timezone(body.timezone);if(body.status!==undefined){const status=String(body.status);if(!['ACTIVE','SUSPENDED','TRIAL'].includes(status))throw new AppError(400,'INVALID_STATUS','School status is invalid');allowed.status=status}if(body.plan!==undefined)allowed.plan=nextPlan;if(body.enabledModules!==undefined)allowed.enabledModules=moduleValue(nextPlan,body.enabledModules);else if(body.plan!==undefined)allowed.enabledModules=clampModulesToPlan(nextPlan,school.enabledModules);allowed.updatedAt=new Date();Object.assign(school,allowed);await school.save();invalidateSchoolAccess(String(school._id));return{success:true,data:school}});
 app.get('/api/platform/plans',{preHandler:guard},async()=>({success:true,data:['STARTER','GROWTH','PRO'].map(plan=>({plan,modules:modulesForPlan(plan as any)}))}));
 app.get('/api/platform/metrics',{preHandler:guard},async()=>{const[total,active,suspended,trial,mfaEnabledAdmins]=await Promise.all([School.countDocuments(),School.countDocuments({status:'ACTIVE'}),School.countDocuments({status:'SUSPENDED'}),School.countDocuments({status:'TRIAL'}),PlatformAdmin.countDocuments({isActive:true,mfaEnabled:true})]);return{success:true,data:{schools:{total,active,suspended,trial},security:{mfaEnabledAdmins}}}});
}
