import type{FastifyInstance}from'fastify';
import{PERMISSIONS}from'@erp/contracts';
import{requirePermission}from'../../core/security.js';
import{AppError}from'../../core/errors.js';
import{SchoolSettings}from'./models.js';
import{writeAudit}from'../../core/audit.js';

const clean=(value:any,max=1000)=>String(value??'').trim().slice(0,max);
const num=(value:any,min:number,max:number,label:string)=>{const n=Number(value);if(!Number.isFinite(n)||n<min||n>max)throw new AppError(400,'INVALID_SETTING',`${label} must be between ${min} and ${max}`);return n};
function safeUrl(value:any,label:string){const v=clean(value,1500);if(!v)return undefined;if(!/^https:\/\//i.test(v))throw new AppError(400,'INVALID_URL',`${label} must use https`);return v}
function safeMixed(value:any,label:string,maxBytes=12000){if(value===undefined)return undefined;if(value===null)return null;if(typeof value!=='object'||Array.isArray(value))throw new AppError(400,'INVALID_SETTING',`${label} must be an object`);const serialized=JSON.stringify(value);if(Buffer.byteLength(serialized,'utf8')>maxBytes)throw new AppError(400,'SETTING_TOO_LARGE',`${label} is too large`);if(/"(?:__proto__|constructor|prototype)"\s*:/.test(serialized))throw new AppError(400,'INVALID_SETTING',`${label} contains forbidden keys`);return JSON.parse(serialized)}
function timeZone(value:any){const v=clean(value,80);try{new Intl.DateTimeFormat('en-US',{timeZone:v}).format(new Date())}catch{throw new AppError(400,'INVALID_TIMEZONE','Timezone is invalid')}return v}
function partialSettings(body:any,current:any={}){if(!body||typeof body!=='object'||Array.isArray(body))throw new AppError(400,'INVALID_SETTINGS','Settings payload must be an object');const allowed=new Set(['branding','academics','attendance','fees','library','documents','locale']),unknown=Object.keys(body).filter(key=>!allowed.has(key));if(unknown.length)throw new AppError(400,'UNKNOWN_SETTINGS',`Unsupported settings: ${unknown.join(', ')}`);const next:any={};
 if(body.branding!==undefined){const src=body.branding||{},base=current.branding||{};const color=src.primaryColor===undefined?base.primaryColor:clean(src.primaryColor,20);if(color&&!/^#[0-9A-Fa-f]{6}$/.test(color))throw new AppError(400,'INVALID_COLOR','primaryColor must be a 6-digit hex color');next.branding={primaryColor:color||'#274abf',logoUrl:src.logoUrl===undefined?base.logoUrl:safeUrl(src.logoUrl,'logoUrl'),letterheadUrl:src.letterheadUrl===undefined?base.letterheadUrl:safeUrl(src.letterheadUrl,'letterheadUrl')}}
 if(body.academics!==undefined){const src=body.academics||{},base=current.academics||{},working=src.workingDays===undefined?(base.workingDays||[]):src.workingDays;if(!Array.isArray(working)||working.length>7||working.some((day:any)=>!Number.isInteger(Number(day))||Number(day)<0||Number(day)>6))throw new AppError(400,'INVALID_WORKING_DAYS','workingDays must contain weekday numbers 0–6');next.academics={periodMinutes:src.periodMinutes===undefined?(base.periodMinutes??45):num(src.periodMinutes,15,180,'periodMinutes'),workingDays:[...new Set(working.map(Number))],gradingScale:src.gradingScale===undefined?base.gradingScale:safeMixed(src.gradingScale,'gradingScale')}}
 if(body.attendance!==undefined){const src=body.attendance||{},base=current.attendance||{},late=src.lateAfter===undefined?base.lateAfter:clean(src.lateAfter,5);if(late&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(late))throw new AppError(400,'INVALID_TIME','lateAfter must use HH:mm');next.attendance={lateAfter:late||undefined,minPercentage:src.minPercentage===undefined?(base.minPercentage??75):num(src.minPercentage,0,100,'minPercentage')}}
 if(body.fees!==undefined){const src=body.fees||{},base=current.fees||{},currency=src.currency===undefined?(base.currency||'INR'):clean(src.currency,3).toUpperCase();if(!/^[A-Z]{3}$/.test(currency))throw new AppError(400,'INVALID_CURRENCY','currency must be a 3-letter code');next.fees={currency,lateFeeRules:src.lateFeeRules===undefined?base.lateFeeRules:safeMixed(src.lateFeeRules,'lateFeeRules')}}
 if(body.library!==undefined){const src=body.library||{},base=current.library||{};next.library={finePerDay:src.finePerDay===undefined?(base.finePerDay??2):num(src.finePerDay,0,10000,'finePerDay'),studentLoanDays:src.studentLoanDays===undefined?(base.studentLoanDays??14):Math.round(num(src.studentLoanDays,1,365,'studentLoanDays')),teacherLoanDays:src.teacherLoanDays===undefined?(base.teacherLoanDays??30):Math.round(num(src.teacherLoanDays,1,365,'teacherLoanDays')),staffLoanDays:src.staffLoanDays===undefined?(base.staffLoanDays??30):Math.round(num(src.staffLoanDays,1,365,'staffLoanDays'))}}
 if(body.documents!==undefined){const src=body.documents||{},base=current.documents||{},urls=src.signatureUrls===undefined?(base.signatureUrls||[]):src.signatureUrls;if(!Array.isArray(urls)||urls.length>10)throw new AppError(400,'INVALID_SIGNATURES','signatureUrls must contain at most 10 entries');const prefix=src.certificatePrefix===undefined?base.certificatePrefix:clean(src.certificatePrefix,20).toUpperCase();if(prefix&&!/^[A-Z0-9_-]{2,20}$/.test(prefix))throw new AppError(400,'INVALID_PREFIX','certificatePrefix may use A-Z, 0-9, underscore and hyphen');next.documents={signatureUrls:urls.map((url:any,index:number)=>safeUrl(url,`signatureUrls[${index}]`)).filter(Boolean),certificatePrefix:prefix||undefined}}
 if(body.locale!==undefined){const src=body.locale||{},base=current.locale||{},format=src.dateFormat===undefined?(base.dateFormat||'DD/MM/YYYY'):clean(src.dateFormat,20);if(!['DD/MM/YYYY','MM/DD/YYYY','YYYY-MM-DD'].includes(format))throw new AppError(400,'INVALID_DATE_FORMAT','Unsupported date format');next.locale={timezone:src.timezone===undefined?(base.timezone||'Asia/Kolkata'):timeZone(src.timezone),dateFormat:format}}
 return next}

export async function settingsRoutes(app:FastifyInstance){
 app.get('/api/settings',{preHandler:requirePermission(PERMISSIONS.SCHOOL_MANAGE)},async()=>({success:true,data:(await SchoolSettings.findOne().lean())||{}}));
 app.patch('/api/settings',{preHandler:requirePermission(PERMISSIONS.SCHOOL_MANAGE)},async(request:any)=>{const before:any=await SchoolSettings.findOne().lean(),patch=partialSettings(request.body,before||{});if(!Object.keys(patch).length)throw new AppError(400,'EMPTY_SETTINGS','No supported settings were supplied');const item=await SchoolSettings.findOneAndUpdate({},{$set:{...patch,updatedAt:new Date()}},{new:true,upsert:true,setDefaultsOnInsert:true});await writeAudit({action:'settings.update',entity:'school-settings',before,after:item?.toObject(),ip:request.ip});return{success:true,data:item}});
}
