import type{FastifyInstance}from'fastify';
import{Types}from'mongoose';
import{PERMISSIONS}from'@erp/contracts';
import{requirePermission}from'../../core/security.js';
import{AppError}from'../../core/errors.js';
import{writeAudit}from'../../core/audit.js';
import{Guardian,Student}from'./models.js';

const validId=(value:any)=>Types.ObjectId.isValid(String(value||''));
export async function guardianLinkRoutes(app:FastifyInstance){
 app.post('/api/guardians/:id/link-students',{preHandler:requirePermission(PERMISSIONS.STUDENT_WRITE)},async(request:any)=>{if(!validId(request.params.id))throw new AppError(400,'INVALID_GUARDIAN','Guardian id is invalid');const guardian:any=await Guardian.findById(request.params.id);if(!guardian)throw new AppError(404,'NOT_FOUND','Guardian not found');const raw=Array.isArray(request.body?.studentIds)?request.body.studentIds:[];if(raw.length>20||raw.some((id:any)=>!validId(id)))throw new AppError(400,'INVALID_STUDENTS','studentIds must contain at most 20 valid IDs');const nextIds=[...new Set(raw.map(String))];if(nextIds.length&&await Student.countDocuments({_id:{$in:nextIds}})!==nextIds.length)throw new AppError(404,'STUDENT_NOT_FOUND','One or more students do not exist in this school');const previousIds=(guardian.studentIds||[]).map(String),removed=previousIds.filter((id:string)=>!nextIds.includes(id)),added=nextIds.filter((id:string)=>!previousIds.includes(id));guardian.studentIds=nextIds.map(id=>new Types.ObjectId(id));guardian.updatedAt=new Date();await guardian.save();try{if(removed.length)await Student.updateMany({_id:{$in:removed}},{$pull:{guardianIds:guardian._id},$set:{updatedAt:new Date()}});if(added.length)await Student.updateMany({_id:{$in:added}},{$addToSet:{guardianIds:guardian._id},$set:{updatedAt:new Date()}})}catch(error){guardian.studentIds=previousIds.map(id=>new Types.ObjectId(id));guardian.updatedAt=new Date();await guardian.save().catch(()=>undefined);throw error}await writeAudit({action:'guardian.link-students',entity:'guardian',entityId:String(guardian._id),before:{studentIds:previousIds},after:{studentIds:nextIds,added,removed},ip:request.ip});return{success:true,data:guardian}});
 app.post('/api/guardians/reconcile-links',{preHandler:requirePermission(PERMISSIONS.STUDENT_WRITE)},async(request:any)=>{const guardians:any[]=await Guardian.find().select('_id studentIds').lean(),expected=new Map<string,Set<string>>();for(const guardian of guardians)for(const studentId of guardian.studentIds||[]){const key=String(studentId);if(!expected.has(key))expected.set(key,new Set());expected.get(key)!.add(String(guardian._id))}const students:any[]=await Student.find().select('_id guardianIds').lean();let changed=0;for(const student of students){const desired=[...(expected.get(String(student._id))||new Set<string>())].sort(),current=(student.guardianIds||[]).map(String).sort();if(JSON.stringify(desired)!==JSON.stringify(current)){await Student.updateOne({_id:student._id},{$set:{guardianIds:desired.map(id=>new Types.ObjectId(id)),updatedAt:new Date()}});changed++}}await writeAudit({action:'guardian.reconcile-links',entity:'guardian',after:{guardians:guardians.length,students:students.length,changed},ip:request.ip});return{success:true,data:{guardians:guardians.length,students:students.length,changed}}});
}
