import type { FastifyInstance } from 'fastify';
import { Types } from 'mongoose';
import { PERMISSIONS } from '@erp/contracts';
import { registerCrud } from '../../core/crud.js';
import { Student,Teacher,Staff,Guardian } from './models.js';
import { requirePermission } from '../../core/security.js';
import { AppError } from '../../core/errors.js';
import { writeAudit } from '../../core/audit.js';
import { guardianReadScope,studentReadProjection,studentReadScope } from './access.js';
import { AcademicClass,Section } from '../academics/models.js';

const validId=(value:any)=>Types.ObjectId.isValid(String(value||''));
const clean=(value:any,max=1000)=>String(value??'').trim().slice(0,max);
function optionalEmail(value:any){const email=clean(value,254).toLowerCase();if(!email)return undefined;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new AppError(400,'INVALID_EMAIL','Email address is invalid');return email}
function optionalPhone(value:any){const phone=clean(value,30);if(!phone)return undefined;if(!/^\+?[0-9][0-9\s()-]{6,28}$/.test(phone))throw new AppError(400,'INVALID_PHONE','Phone number is invalid');return phone}
function optionalDate(value:any,label:string){if(value===undefined||value===null||value==='')return undefined;const date=new Date(value);if(Number.isNaN(date.getTime()))throw new AppError(400,'INVALID_DATE',`${label} is invalid`);return date}
function safeAddress(value:any){if(value===undefined)return undefined;if(value===null)return undefined;if(typeof value!=='object'||Array.isArray(value))throw new AppError(400,'INVALID_ADDRESS','Address must be an object');const out:any={};for(const key of['line1','line2','city','state','pincode','country'])if(value[key]!==undefined){const v=clean(value[key],key==='line1'||key==='line2'?180:100);if(v)out[key]=v}return out}
function safeDocuments(value:any){if(value===undefined)return undefined;if(!Array.isArray(value)||value.length>30)throw new AppError(400,'INVALID_DOCUMENTS','documents must contain at most 30 items');return value.map((row:any,index:number)=>{const name=clean(row?.name,120),url=clean(row?.url,1500);if(!name||!/^https:\/\//i.test(url))throw new AppError(400,'INVALID_DOCUMENT',`Document ${index+1} needs a name and HTTPS URL`);return{name,url,verified:Boolean(row?.verified)}})}
function common(body:any,current:any={}){const firstName=body.firstName===undefined?current.firstName:clean(body.firstName,100);if(!firstName)throw new AppError(400,'INVALID_NAME','First name is required');const gender=body.gender===undefined?current.gender:(body.gender||undefined);if(gender&&!['MALE','FEMALE','OTHER'].includes(gender))throw new AppError(400,'INVALID_GENDER','Gender is invalid');const status=body.status===undefined?(current.status||'ACTIVE'):String(body.status);if(!['ACTIVE','INACTIVE'].includes(status))throw new AppError(400,'INVALID_STATUS','Person status is invalid');return{firstName,lastName:body.lastName===undefined?current.lastName:clean(body.lastName,100),email:body.email===undefined?current.email:optionalEmail(body.email),phone:body.phone===undefined?current.phone:optionalPhone(body.phone),dateOfBirth:body.dateOfBirth===undefined?current.dateOfBirth:optionalDate(body.dateOfBirth,'dateOfBirth'),gender,address:body.address===undefined?current.address:safeAddress(body.address),photoUrl:body.photoUrl===undefined?current.photoUrl:(clean(body.photoUrl,1500)||undefined),documents:body.documents===undefined?current.documents:safeDocuments(body.documents),status,updatedAt:new Date()}}
async function academicPair(classId:any,sectionId:any,optional=false){if(!classId&&!sectionId&&optional)return{};if(!validId(classId)||!validId(sectionId))throw new AppError(400,'ACADEMIC_SCOPE','Valid classId and sectionId are required together');const[klass,section]:any[]=await Promise.all([AcademicClass.findById(classId).select('_id').lean(),Section.findById(sectionId).select('_id classId').lean()]);if(!klass||!section||String(section.classId)!==String(classId))throw new AppError(404,'ACADEMIC_SCOPE','Class and section do not belong together in this school');return{classId:new Types.ObjectId(String(classId)),sectionId:new Types.ObjectId(String(sectionId))}}
async function guardianIds(value:any){if(value===undefined)return undefined;if(!Array.isArray(value)||value.length>10||value.some(id=>!validId(id)))throw new AppError(400,'INVALID_GUARDIANS','guardianIds must contain valid guardian IDs');const ids=[...new Set(value.map(String))];if(ids.length&&await Guardian.countDocuments({_id:{$in:ids}})!==ids.length)throw new AppError(404,'GUARDIAN_NOT_FOUND','One or more guardians do not exist in this school');return ids.map(id=>new Types.ObjectId(id))}
async function studentIds(value:any){if(value===undefined)return undefined;if(!Array.isArray(value)||value.length>20||value.some(id=>!validId(id)))throw new AppError(400,'INVALID_STUDENTS','studentIds must contain valid student IDs');const ids=[...new Set(value.map(String))];if(ids.length&&await Student.countDocuments({_id:{$in:ids}})!==ids.length)throw new AppError(404,'STUDENT_NOT_FOUND','One or more students do not exist in this school');return ids.map(id=>new Types.ObjectId(id))}
async function studentData(request:any,current:any={}){const body=request.body??{},admissionNo=body.admissionNo===undefined?current.admissionNo:clean(body.admissionNo,80);if(!admissionNo)throw new AppError(400,'ADMISSION_NO_REQUIRED','Admission number is required');const hasAcademic=body.classId!==undefined||body.sectionId!==undefined||current.classId||current.sectionId,academic=hasAcademic?await academicPair(body.classId??current.classId,body.sectionId??current.sectionId,true):{};const lifecycle=body.lifecycle===undefined?(current.lifecycle||'ACTIVE'):String(body.lifecycle);if(!['ACTIVE','SUSPENDED','DROPPED','PASSED','ALUMNI'].includes(lifecycle))throw new AppError(400,'INVALID_LIFECYCLE','Invalid student lifecycle');return{...common(body,current),admissionNo,rollNo:body.rollNo===undefined?current.rollNo:clean(body.rollNo,80)||undefined,...academic,admissionDate:body.admissionDate===undefined?current.admissionDate:optionalDate(body.admissionDate,'admissionDate'),guardianIds:body.guardianIds===undefined?current.guardianIds:await guardianIds(body.guardianIds),lifecycle}}
async function teacherData(request:any,current:any={}){const body=request.body??{},employeeNo=body.employeeNo===undefined?current.employeeNo:clean(body.employeeNo,80);if(!employeeNo)throw new AppError(400,'EMPLOYEE_NO_REQUIRED','Employee number is required');let classTeacherOf=body.classTeacherOf===undefined?current.classTeacherOf:(body.classTeacherOf||undefined);if(classTeacherOf&&(!validId(classTeacherOf)||!await Section.findById(classTeacherOf).select('_id').lean()))throw new AppError(404,'SECTION_NOT_FOUND','Class-teacher section not found');return{...common(body,current),employeeNo,department:body.department===undefined?current.department:clean(body.department,120)||undefined,qualification:body.qualification===undefined?current.qualification:clean(body.qualification,240)||undefined,joiningDate:body.joiningDate===undefined?current.joiningDate:optionalDate(body.joiningDate,'joiningDate'),classTeacherOf}}
async function staffData(request:any,current:any={}){const body=request.body??{},employeeNo=body.employeeNo===undefined?current.employeeNo:clean(body.employeeNo,80);if(!employeeNo)throw new AppError(400,'EMPLOYEE_NO_REQUIRED','Employee number is required');return{...common(body,current),employeeNo,department:body.department===undefined?current.department:clean(body.department,120)||undefined,designation:body.designation===undefined?current.designation:clean(body.designation,120)||undefined,joiningDate:body.joiningDate===undefined?current.joiningDate:optionalDate(body.joiningDate,'joiningDate')}}
async function guardianData(request:any,current:any={}){const body=request.body??{},relation=body.relation===undefined?current.relation:clean(body.relation,80);if(!relation)throw new AppError(400,'RELATION_REQUIRED','Guardian relation is required');return{...common(body,current),relation,occupation:body.occupation===undefined?current.occupation:clean(body.occupation,160)||undefined,studentIds:body.studentIds===undefined?current.studentIds:await studentIds(body.studentIds)}}
const updateWith=(Model:any,resolver:any)=>async(request:any)=>{const current=await Model.findById(request.params.id).lean();if(!current)throw new AppError(404,'NOT_FOUND','Person not found');return resolver(request,current)};

export async function peopleRoutes(app:FastifyInstance){
 await registerCrud(app,{prefix:'/api/students',model:Student,entity:'student',readPermission:PERMISSIONS.STUDENT_READ,writePermission:PERMISSIONS.STUDENT_WRITE,searchable:['firstName','lastName','admissionNo','phone'],readScope:studentReadScope,readProjection:studentReadProjection,prepareCreate:studentData,prepareUpdate:updateWith(Student,studentData)});
 await registerCrud(app,{prefix:'/api/teachers',model:Teacher,entity:'teacher',readPermission:PERMISSIONS.TEACHER_READ,writePermission:PERMISSIONS.TEACHER_WRITE,searchable:['firstName','lastName','employeeNo','phone'],prepareCreate:teacherData,prepareUpdate:updateWith(Teacher,teacherData)});
 await registerCrud(app,{prefix:'/api/staff',model:Staff,entity:'staff',readPermission:PERMISSIONS.STAFF_READ,writePermission:PERMISSIONS.STAFF_WRITE,searchable:['firstName','lastName','employeeNo','designation'],prepareCreate:staffData,prepareUpdate:updateWith(Staff,staffData)});
 await registerCrud(app,{prefix:'/api/guardians',model:Guardian,entity:'guardian',readPermission:PERMISSIONS.STUDENT_READ,writePermission:PERMISSIONS.STUDENT_WRITE,searchable:['firstName','lastName','phone'],readScope:guardianReadScope,prepareCreate:guardianData,prepareUpdate:updateWith(Guardian,guardianData)});
 app.post('/api/students/promote',{preHandler:requirePermission(PERMISSIONS.STUDENT_WRITE)},async(request:any)=>{const ids=Array.isArray(request.body?.studentIds)?[...new Set(request.body.studentIds.map(String))]:[];if(!ids.length||ids.length>500||ids.some(id=>!validId(id)))throw new AppError(400,'INVALID_STUDENTS','Select 1 to 500 valid students');const academic=await academicPair(request.body?.classId,request.body?.sectionId);const found=await Student.countDocuments({_id:{$in:ids},lifecycle:'ACTIVE'});if(found!==ids.length)throw new AppError(404,'STUDENT_NOT_FOUND','One or more active students are unavailable');const result=await Student.updateMany({_id:{$in:ids},lifecycle:'ACTIVE'},{$set:{...academic,updatedAt:new Date()}});await writeAudit({action:'student.promote',entity:'student',after:{count:result.modifiedCount,classId:String(academic.classId),sectionId:String(academic.sectionId),studentIds:ids},ip:request.ip});return{success:true,data:{promoted:result.modifiedCount}}});
 app.post('/api/students/:id/lifecycle',{preHandler:requirePermission(PERMISSIONS.STUDENT_WRITE)},async(request:any)=>{const lifecycle=String(request.body?.lifecycle||''),allowed=['ACTIVE','SUSPENDED','DROPPED','PASSED','ALUMNI'];if(!allowed.includes(lifecycle))throw new AppError(400,'INVALID_LIFECYCLE','Invalid lifecycle');const student:any=await Student.findById(request.params.id);if(!student)throw new AppError(404,'NOT_FOUND','Student not found');const before={lifecycle:student.lifecycle};student.lifecycle=lifecycle;student.updatedAt=new Date();await student.save();await writeAudit({action:'student.lifecycle',entity:'student',entityId:String(student._id),before,after:{lifecycle},ip:request.ip});return{success:true,data:student}});
}
