import type { FastifyInstance } from 'fastify';import { PERMISSIONS } from '@erp/contracts';import { registerCrud } from '../../core/crud.js';import { Student,Teacher,Staff,Guardian } from './models.js';import { requirePermission } from '../../core/security.js';import { writeAudit } from '../../core/audit.js';
export async function peopleRoutes(app:FastifyInstance){
 await registerCrud(app,{prefix:'/api/students',model:Student,entity:'student',readPermission:PERMISSIONS.STUDENT_READ,writePermission:PERMISSIONS.STUDENT_WRITE,searchable:['firstName','lastName','admissionNo','phone']});
 await registerCrud(app,{prefix:'/api/teachers',model:Teacher,entity:'teacher',readPermission:PERMISSIONS.TEACHER_READ,writePermission:PERMISSIONS.TEACHER_WRITE,searchable:['firstName','lastName','employeeNo','phone']});
 await registerCrud(app,{prefix:'/api/staff',model:Staff,entity:'staff',readPermission:PERMISSIONS.STAFF_READ,writePermission:PERMISSIONS.STAFF_WRITE,searchable:['firstName','lastName','employeeNo','designation']});
 await registerCrud(app,{prefix:'/api/guardians',model:Guardian,entity:'guardian',readPermission:PERMISSIONS.STUDENT_READ,writePermission:PERMISSIONS.STUDENT_WRITE,searchable:['firstName','lastName','phone']});
 app.post('/api/students/promote',{preHandler:requirePermission(PERMISSIONS.STUDENT_WRITE)},async(request:any)=>{const{studentIds,classId,sectionId}=request.body??{};const result=await Student.updateMany({_id:{$in:studentIds||[]}},{$set:{classId,sectionId,updatedAt:new Date()}});await writeAudit({action:'student.promote',entity:'student',after:{count:result.modifiedCount,classId,sectionId},ip:request.ip});return{success:true,data:{promoted:result.modifiedCount}}});
 app.post('/api/students/:id/lifecycle',{preHandler:requirePermission(PERMISSIONS.STUDENT_WRITE)},async(request:any)=>{const allowed=['ACTIVE','SUSPENDED','DROPPED','PASSED','ALUMNI'];if(!allowed.includes(request.body?.lifecycle))return{success:false,error:{code:'INVALID_LIFECYCLE',message:'Invalid lifecycle'}};return{success:true,data:await Student.findByIdAndUpdate(request.params.id,{$set:{lifecycle:request.body.lifecycle,updatedAt:new Date()}},{new:true})}});
}
